# -*- makefile -*-
# Generated by genmk.rb, please don't edit!

MAINTAINER_CLEANFILES += $(srcdir)/conf/gcry.rmk $(srcdir)/lib/libgcrypt-grub/cipher/ChangeLog $(srcdir)/lib/libgcrypt-grub/cipher/cipher.h $(srcdir)/lib/libgcrypt-grub/cipher/crypto.lst $(srcdir)/lib/libgcrypt-grub/cipher/g10lib.h $(srcdir)/lib/libgcrypt-grub/cipher/memory.h $(srcdir)/lib/libgcrypt-grub/cipher/types.h
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/crc.c
pkglib_MODULES += gcry_crc.mod
gcry_crc_mod_SOURCES = lib/libgcrypt-grub/cipher/crc.c

clean-module-gcry_crc.mod.1:
	rm -f gcry_crc.mod gcry_crc_mod-lib_libgcrypt_grub_cipher_crc.o

CLEAN_MODULE_TARGETS += clean-module-gcry_crc.mod.1

mostlyclean-module-gcry_crc.mod.1:
	rm -f gcry_crc_mod-lib_libgcrypt_grub_cipher_crc.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_crc.mod.1

gcry_crc.mod: $(gcry_crc_mod_DEPENDENCIES) gcry_crc_mod-lib_libgcrypt_grub_cipher_crc.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_crc.mod")

MODFILES += gcry_crc.mod

gcry_crc_mod-lib_libgcrypt_grub_cipher_crc.o: lib/libgcrypt-grub/cipher/crc.c $(lib/libgcrypt-grub/cipher/crc.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_crc_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_crc_mod-lib_libgcrypt_grub_cipher_crc.o")
-include gcry_crc_mod-lib_libgcrypt_grub_cipher_crc.d

gcry_crc_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_crc_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/bithelp.h
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/hash-common.h
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/cast5.c
pkglib_MODULES += gcry_cast5.mod
gcry_cast5_mod_SOURCES = lib/libgcrypt-grub/cipher/cast5.c

clean-module-gcry_cast5.mod.1:
	rm -f gcry_cast5.mod gcry_cast5_mod-lib_libgcrypt_grub_cipher_cast5.o

CLEAN_MODULE_TARGETS += clean-module-gcry_cast5.mod.1

mostlyclean-module-gcry_cast5.mod.1:
	rm -f gcry_cast5_mod-lib_libgcrypt_grub_cipher_cast5.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_cast5.mod.1

gcry_cast5.mod: $(gcry_cast5_mod_DEPENDENCIES) gcry_cast5_mod-lib_libgcrypt_grub_cipher_cast5.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_cast5.mod")

MODFILES += gcry_cast5.mod

gcry_cast5_mod-lib_libgcrypt_grub_cipher_cast5.o: lib/libgcrypt-grub/cipher/cast5.c $(lib/libgcrypt-grub/cipher/cast5.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_cast5_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_cast5_mod-lib_libgcrypt_grub_cipher_cast5.o")
-include gcry_cast5_mod-lib_libgcrypt_grub_cipher_cast5.d

gcry_cast5_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_cast5_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/des.c
pkglib_MODULES += gcry_des.mod
gcry_des_mod_SOURCES = lib/libgcrypt-grub/cipher/des.c

clean-module-gcry_des.mod.1:
	rm -f gcry_des.mod gcry_des_mod-lib_libgcrypt_grub_cipher_des.o

CLEAN_MODULE_TARGETS += clean-module-gcry_des.mod.1

mostlyclean-module-gcry_des.mod.1:
	rm -f gcry_des_mod-lib_libgcrypt_grub_cipher_des.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_des.mod.1

gcry_des.mod: $(gcry_des_mod_DEPENDENCIES) gcry_des_mod-lib_libgcrypt_grub_cipher_des.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_des.mod")

MODFILES += gcry_des.mod

gcry_des_mod-lib_libgcrypt_grub_cipher_des.o: lib/libgcrypt-grub/cipher/des.c $(lib/libgcrypt-grub/cipher/des.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_des_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_des_mod-lib_libgcrypt_grub_cipher_des.o")
-include gcry_des_mod-lib_libgcrypt_grub_cipher_des.d

gcry_des_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_des_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/sha256.c
pkglib_MODULES += gcry_sha256.mod
gcry_sha256_mod_SOURCES = lib/libgcrypt-grub/cipher/sha256.c

clean-module-gcry_sha256.mod.1:
	rm -f gcry_sha256.mod gcry_sha256_mod-lib_libgcrypt_grub_cipher_sha256.o

CLEAN_MODULE_TARGETS += clean-module-gcry_sha256.mod.1

mostlyclean-module-gcry_sha256.mod.1:
	rm -f gcry_sha256_mod-lib_libgcrypt_grub_cipher_sha256.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_sha256.mod.1

gcry_sha256.mod: $(gcry_sha256_mod_DEPENDENCIES) gcry_sha256_mod-lib_libgcrypt_grub_cipher_sha256.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_sha256.mod")

MODFILES += gcry_sha256.mod

gcry_sha256_mod-lib_libgcrypt_grub_cipher_sha256.o: lib/libgcrypt-grub/cipher/sha256.c $(lib/libgcrypt-grub/cipher/sha256.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_sha256_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_sha256_mod-lib_libgcrypt_grub_cipher_sha256.o")
-include gcry_sha256_mod-lib_libgcrypt_grub_cipher_sha256.d

gcry_sha256_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_sha256_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/whirlpool.c
pkglib_MODULES += gcry_whirlpool.mod
gcry_whirlpool_mod_SOURCES = lib/libgcrypt-grub/cipher/whirlpool.c

clean-module-gcry_whirlpool.mod.1:
	rm -f gcry_whirlpool.mod gcry_whirlpool_mod-lib_libgcrypt_grub_cipher_whirlpool.o

CLEAN_MODULE_TARGETS += clean-module-gcry_whirlpool.mod.1

mostlyclean-module-gcry_whirlpool.mod.1:
	rm -f gcry_whirlpool_mod-lib_libgcrypt_grub_cipher_whirlpool.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_whirlpool.mod.1

gcry_whirlpool.mod: $(gcry_whirlpool_mod_DEPENDENCIES) gcry_whirlpool_mod-lib_libgcrypt_grub_cipher_whirlpool.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_whirlpool.mod")

MODFILES += gcry_whirlpool.mod

gcry_whirlpool_mod-lib_libgcrypt_grub_cipher_whirlpool.o: lib/libgcrypt-grub/cipher/whirlpool.c $(lib/libgcrypt-grub/cipher/whirlpool.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_whirlpool_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_whirlpool_mod-lib_libgcrypt_grub_cipher_whirlpool.o")
-include gcry_whirlpool_mod-lib_libgcrypt_grub_cipher_whirlpool.d

gcry_whirlpool_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_whirlpool_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/twofish.c
pkglib_MODULES += gcry_twofish.mod
gcry_twofish_mod_SOURCES = lib/libgcrypt-grub/cipher/twofish.c

clean-module-gcry_twofish.mod.1:
	rm -f gcry_twofish.mod gcry_twofish_mod-lib_libgcrypt_grub_cipher_twofish.o

CLEAN_MODULE_TARGETS += clean-module-gcry_twofish.mod.1

mostlyclean-module-gcry_twofish.mod.1:
	rm -f gcry_twofish_mod-lib_libgcrypt_grub_cipher_twofish.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_twofish.mod.1

gcry_twofish.mod: $(gcry_twofish_mod_DEPENDENCIES) gcry_twofish_mod-lib_libgcrypt_grub_cipher_twofish.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_twofish.mod")

MODFILES += gcry_twofish.mod

gcry_twofish_mod-lib_libgcrypt_grub_cipher_twofish.o: lib/libgcrypt-grub/cipher/twofish.c $(lib/libgcrypt-grub/cipher/twofish.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_twofish_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_twofish_mod-lib_libgcrypt_grub_cipher_twofish.o")
-include gcry_twofish_mod-lib_libgcrypt_grub_cipher_twofish.d

gcry_twofish_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_twofish_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/rijndael-tables.h
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/arcfour.c
pkglib_MODULES += gcry_arcfour.mod
gcry_arcfour_mod_SOURCES = lib/libgcrypt-grub/cipher/arcfour.c

clean-module-gcry_arcfour.mod.1:
	rm -f gcry_arcfour.mod gcry_arcfour_mod-lib_libgcrypt_grub_cipher_arcfour.o

CLEAN_MODULE_TARGETS += clean-module-gcry_arcfour.mod.1

mostlyclean-module-gcry_arcfour.mod.1:
	rm -f gcry_arcfour_mod-lib_libgcrypt_grub_cipher_arcfour.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_arcfour.mod.1

gcry_arcfour.mod: $(gcry_arcfour_mod_DEPENDENCIES) gcry_arcfour_mod-lib_libgcrypt_grub_cipher_arcfour.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_arcfour.mod")

MODFILES += gcry_arcfour.mod

gcry_arcfour_mod-lib_libgcrypt_grub_cipher_arcfour.o: lib/libgcrypt-grub/cipher/arcfour.c $(lib/libgcrypt-grub/cipher/arcfour.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_arcfour_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_arcfour_mod-lib_libgcrypt_grub_cipher_arcfour.o")
-include gcry_arcfour_mod-lib_libgcrypt_grub_cipher_arcfour.d

gcry_arcfour_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_arcfour_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/tiger.c
pkglib_MODULES += gcry_tiger.mod
gcry_tiger_mod_SOURCES = lib/libgcrypt-grub/cipher/tiger.c

clean-module-gcry_tiger.mod.1:
	rm -f gcry_tiger.mod gcry_tiger_mod-lib_libgcrypt_grub_cipher_tiger.o

CLEAN_MODULE_TARGETS += clean-module-gcry_tiger.mod.1

mostlyclean-module-gcry_tiger.mod.1:
	rm -f gcry_tiger_mod-lib_libgcrypt_grub_cipher_tiger.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_tiger.mod.1

gcry_tiger.mod: $(gcry_tiger_mod_DEPENDENCIES) gcry_tiger_mod-lib_libgcrypt_grub_cipher_tiger.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_tiger.mod")

MODFILES += gcry_tiger.mod

gcry_tiger_mod-lib_libgcrypt_grub_cipher_tiger.o: lib/libgcrypt-grub/cipher/tiger.c $(lib/libgcrypt-grub/cipher/tiger.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_tiger_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_tiger_mod-lib_libgcrypt_grub_cipher_tiger.o")
-include gcry_tiger_mod-lib_libgcrypt_grub_cipher_tiger.d

gcry_tiger_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_tiger_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/seed.c
pkglib_MODULES += gcry_seed.mod
gcry_seed_mod_SOURCES = lib/libgcrypt-grub/cipher/seed.c

clean-module-gcry_seed.mod.1:
	rm -f gcry_seed.mod gcry_seed_mod-lib_libgcrypt_grub_cipher_seed.o

CLEAN_MODULE_TARGETS += clean-module-gcry_seed.mod.1

mostlyclean-module-gcry_seed.mod.1:
	rm -f gcry_seed_mod-lib_libgcrypt_grub_cipher_seed.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_seed.mod.1

gcry_seed.mod: $(gcry_seed_mod_DEPENDENCIES) gcry_seed_mod-lib_libgcrypt_grub_cipher_seed.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_seed.mod")

MODFILES += gcry_seed.mod

gcry_seed_mod-lib_libgcrypt_grub_cipher_seed.o: lib/libgcrypt-grub/cipher/seed.c $(lib/libgcrypt-grub/cipher/seed.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_seed_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_seed_mod-lib_libgcrypt_grub_cipher_seed.o")
-include gcry_seed_mod-lib_libgcrypt_grub_cipher_seed.d

gcry_seed_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_seed_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/camellia.h
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/camellia.c
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/serpent.c
pkglib_MODULES += gcry_serpent.mod
gcry_serpent_mod_SOURCES = lib/libgcrypt-grub/cipher/serpent.c

clean-module-gcry_serpent.mod.1:
	rm -f gcry_serpent.mod gcry_serpent_mod-lib_libgcrypt_grub_cipher_serpent.o

CLEAN_MODULE_TARGETS += clean-module-gcry_serpent.mod.1

mostlyclean-module-gcry_serpent.mod.1:
	rm -f gcry_serpent_mod-lib_libgcrypt_grub_cipher_serpent.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_serpent.mod.1

gcry_serpent.mod: $(gcry_serpent_mod_DEPENDENCIES) gcry_serpent_mod-lib_libgcrypt_grub_cipher_serpent.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_serpent.mod")

MODFILES += gcry_serpent.mod

gcry_serpent_mod-lib_libgcrypt_grub_cipher_serpent.o: lib/libgcrypt-grub/cipher/serpent.c $(lib/libgcrypt-grub/cipher/serpent.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_serpent_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_serpent_mod-lib_libgcrypt_grub_cipher_serpent.o")
-include gcry_serpent_mod-lib_libgcrypt_grub_cipher_serpent.d

gcry_serpent_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_serpent_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/sha1.c
pkglib_MODULES += gcry_sha1.mod
gcry_sha1_mod_SOURCES = lib/libgcrypt-grub/cipher/sha1.c

clean-module-gcry_sha1.mod.1:
	rm -f gcry_sha1.mod gcry_sha1_mod-lib_libgcrypt_grub_cipher_sha1.o

CLEAN_MODULE_TARGETS += clean-module-gcry_sha1.mod.1

mostlyclean-module-gcry_sha1.mod.1:
	rm -f gcry_sha1_mod-lib_libgcrypt_grub_cipher_sha1.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_sha1.mod.1

gcry_sha1.mod: $(gcry_sha1_mod_DEPENDENCIES) gcry_sha1_mod-lib_libgcrypt_grub_cipher_sha1.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_sha1.mod")

MODFILES += gcry_sha1.mod

gcry_sha1_mod-lib_libgcrypt_grub_cipher_sha1.o: lib/libgcrypt-grub/cipher/sha1.c $(lib/libgcrypt-grub/cipher/sha1.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_sha1_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_sha1_mod-lib_libgcrypt_grub_cipher_sha1.o")
-include gcry_sha1_mod-lib_libgcrypt_grub_cipher_sha1.d

gcry_sha1_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_sha1_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/md5.c
pkglib_MODULES += gcry_md5.mod
gcry_md5_mod_SOURCES = lib/libgcrypt-grub/cipher/md5.c

clean-module-gcry_md5.mod.1:
	rm -f gcry_md5.mod gcry_md5_mod-lib_libgcrypt_grub_cipher_md5.o

CLEAN_MODULE_TARGETS += clean-module-gcry_md5.mod.1

mostlyclean-module-gcry_md5.mod.1:
	rm -f gcry_md5_mod-lib_libgcrypt_grub_cipher_md5.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_md5.mod.1

gcry_md5.mod: $(gcry_md5_mod_DEPENDENCIES) gcry_md5_mod-lib_libgcrypt_grub_cipher_md5.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_md5.mod")

MODFILES += gcry_md5.mod

gcry_md5_mod-lib_libgcrypt_grub_cipher_md5.o: lib/libgcrypt-grub/cipher/md5.c $(lib/libgcrypt-grub/cipher/md5.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_md5_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_md5_mod-lib_libgcrypt_grub_cipher_md5.o")
-include gcry_md5_mod-lib_libgcrypt_grub_cipher_md5.d

gcry_md5_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_md5_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/blowfish.c
pkglib_MODULES += gcry_blowfish.mod
gcry_blowfish_mod_SOURCES = lib/libgcrypt-grub/cipher/blowfish.c

clean-module-gcry_blowfish.mod.1:
	rm -f gcry_blowfish.mod gcry_blowfish_mod-lib_libgcrypt_grub_cipher_blowfish.o

CLEAN_MODULE_TARGETS += clean-module-gcry_blowfish.mod.1

mostlyclean-module-gcry_blowfish.mod.1:
	rm -f gcry_blowfish_mod-lib_libgcrypt_grub_cipher_blowfish.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_blowfish.mod.1

gcry_blowfish.mod: $(gcry_blowfish_mod_DEPENDENCIES) gcry_blowfish_mod-lib_libgcrypt_grub_cipher_blowfish.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_blowfish.mod")

MODFILES += gcry_blowfish.mod

gcry_blowfish_mod-lib_libgcrypt_grub_cipher_blowfish.o: lib/libgcrypt-grub/cipher/blowfish.c $(lib/libgcrypt-grub/cipher/blowfish.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_blowfish_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_blowfish_mod-lib_libgcrypt_grub_cipher_blowfish.o")
-include gcry_blowfish_mod-lib_libgcrypt_grub_cipher_blowfish.d

gcry_blowfish_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_blowfish_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/dsa.c
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/primegen.c
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/sha512.c
pkglib_MODULES += gcry_sha512.mod
gcry_sha512_mod_SOURCES = lib/libgcrypt-grub/cipher/sha512.c

clean-module-gcry_sha512.mod.1:
	rm -f gcry_sha512.mod gcry_sha512_mod-lib_libgcrypt_grub_cipher_sha512.o

CLEAN_MODULE_TARGETS += clean-module-gcry_sha512.mod.1

mostlyclean-module-gcry_sha512.mod.1:
	rm -f gcry_sha512_mod-lib_libgcrypt_grub_cipher_sha512.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_sha512.mod.1

gcry_sha512.mod: $(gcry_sha512_mod_DEPENDENCIES) gcry_sha512_mod-lib_libgcrypt_grub_cipher_sha512.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_sha512.mod")

MODFILES += gcry_sha512.mod

gcry_sha512_mod-lib_libgcrypt_grub_cipher_sha512.o: lib/libgcrypt-grub/cipher/sha512.c $(lib/libgcrypt-grub/cipher/sha512.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_sha512_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_sha512_mod-lib_libgcrypt_grub_cipher_sha512.o")
-include gcry_sha512_mod-lib_libgcrypt_grub_cipher_sha512.d

gcry_sha512_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_sha512_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/rmd160.c
pkglib_MODULES += gcry_rmd160.mod
gcry_rmd160_mod_SOURCES = lib/libgcrypt-grub/cipher/rmd160.c

clean-module-gcry_rmd160.mod.1:
	rm -f gcry_rmd160.mod gcry_rmd160_mod-lib_libgcrypt_grub_cipher_rmd160.o

CLEAN_MODULE_TARGETS += clean-module-gcry_rmd160.mod.1

mostlyclean-module-gcry_rmd160.mod.1:
	rm -f gcry_rmd160_mod-lib_libgcrypt_grub_cipher_rmd160.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_rmd160.mod.1

gcry_rmd160.mod: $(gcry_rmd160_mod_DEPENDENCIES) gcry_rmd160_mod-lib_libgcrypt_grub_cipher_rmd160.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_rmd160.mod")

MODFILES += gcry_rmd160.mod

gcry_rmd160_mod-lib_libgcrypt_grub_cipher_rmd160.o: lib/libgcrypt-grub/cipher/rmd160.c $(lib/libgcrypt-grub/cipher/rmd160.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_rmd160_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_rmd160_mod-lib_libgcrypt_grub_cipher_rmd160.o")
-include gcry_rmd160_mod-lib_libgcrypt_grub_cipher_rmd160.d

gcry_rmd160_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_rmd160_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/rmd.h
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/rijndael.c
pkglib_MODULES += gcry_rijndael.mod
gcry_rijndael_mod_SOURCES = lib/libgcrypt-grub/cipher/rijndael.c

clean-module-gcry_rijndael.mod.1:
	rm -f gcry_rijndael.mod gcry_rijndael_mod-lib_libgcrypt_grub_cipher_rijndael.o

CLEAN_MODULE_TARGETS += clean-module-gcry_rijndael.mod.1

mostlyclean-module-gcry_rijndael.mod.1:
	rm -f gcry_rijndael_mod-lib_libgcrypt_grub_cipher_rijndael.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_rijndael.mod.1

gcry_rijndael.mod: $(gcry_rijndael_mod_DEPENDENCIES) gcry_rijndael_mod-lib_libgcrypt_grub_cipher_rijndael.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_rijndael.mod")

MODFILES += gcry_rijndael.mod

gcry_rijndael_mod-lib_libgcrypt_grub_cipher_rijndael.o: lib/libgcrypt-grub/cipher/rijndael.c $(lib/libgcrypt-grub/cipher/rijndael.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_rijndael_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_rijndael_mod-lib_libgcrypt_grub_cipher_rijndael.o")
-include gcry_rijndael_mod-lib_libgcrypt_grub_cipher_rijndael.d

gcry_rijndael_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_rijndael_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/rfc2268.c
pkglib_MODULES += gcry_rfc2268.mod
gcry_rfc2268_mod_SOURCES = lib/libgcrypt-grub/cipher/rfc2268.c

clean-module-gcry_rfc2268.mod.1:
	rm -f gcry_rfc2268.mod gcry_rfc2268_mod-lib_libgcrypt_grub_cipher_rfc2268.o

CLEAN_MODULE_TARGETS += clean-module-gcry_rfc2268.mod.1

mostlyclean-module-gcry_rfc2268.mod.1:
	rm -f gcry_rfc2268_mod-lib_libgcrypt_grub_cipher_rfc2268.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_rfc2268.mod.1

gcry_rfc2268.mod: $(gcry_rfc2268_mod_DEPENDENCIES) gcry_rfc2268_mod-lib_libgcrypt_grub_cipher_rfc2268.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_rfc2268.mod")

MODFILES += gcry_rfc2268.mod

gcry_rfc2268_mod-lib_libgcrypt_grub_cipher_rfc2268.o: lib/libgcrypt-grub/cipher/rfc2268.c $(lib/libgcrypt-grub/cipher/rfc2268.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_rfc2268_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_rfc2268_mod-lib_libgcrypt_grub_cipher_rfc2268.o")
-include gcry_rfc2268_mod-lib_libgcrypt_grub_cipher_rfc2268.d

gcry_rfc2268_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_rfc2268_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/elgamal.c
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/md4.c
pkglib_MODULES += gcry_md4.mod
gcry_md4_mod_SOURCES = lib/libgcrypt-grub/cipher/md4.c

clean-module-gcry_md4.mod.1:
	rm -f gcry_md4.mod gcry_md4_mod-lib_libgcrypt_grub_cipher_md4.o

CLEAN_MODULE_TARGETS += clean-module-gcry_md4.mod.1

mostlyclean-module-gcry_md4.mod.1:
	rm -f gcry_md4_mod-lib_libgcrypt_grub_cipher_md4.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_md4.mod.1

gcry_md4.mod: $(gcry_md4_mod_DEPENDENCIES) gcry_md4_mod-lib_libgcrypt_grub_cipher_md4.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_md4.mod")

MODFILES += gcry_md4.mod

gcry_md4_mod-lib_libgcrypt_grub_cipher_md4.o: lib/libgcrypt-grub/cipher/md4.c $(lib/libgcrypt-grub/cipher/md4.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_md4_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_md4_mod-lib_libgcrypt_grub_cipher_md4.o")
-include gcry_md4_mod-lib_libgcrypt_grub_cipher_md4.d

gcry_md4_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_md4_mod_LDFLAGS = $(COMMON_LDFLAGS)

MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/rsa.c
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/ecc.c
MAINTAINER_CLEANFILES += $(srcdir)/lib/libgcrypt-grub/cipher/camellia-glue.c
pkglib_MODULES += gcry_camellia.mod
gcry_camellia_mod_SOURCES = lib/libgcrypt-grub/cipher/camellia-glue.c lib/libgcrypt-grub/cipher/camellia.c

clean-module-gcry_camellia.mod.1:
	rm -f gcry_camellia.mod gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia_glue.o gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia.o

CLEAN_MODULE_TARGETS += clean-module-gcry_camellia.mod.1

mostlyclean-module-gcry_camellia.mod.1:
	rm -f gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia_glue.d gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-gcry_camellia.mod.1

gcry_camellia.mod: $(gcry_camellia_mod_DEPENDENCIES) gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia_glue.o gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   gcry_camellia.mod")

MODFILES += gcry_camellia.mod

gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia_glue.o: lib/libgcrypt-grub/cipher/camellia-glue.c $(lib/libgcrypt-grub/cipher/camellia-glue.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_camellia_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia_glue.o")
-include gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia_glue.d

gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia.o: lib/libgcrypt-grub/cipher/camellia.c $(lib/libgcrypt-grub/cipher/camellia.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/libgcrypt-grub/cipher -I$(srcdir)/lib/libgcrypt-grub/cipher $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(gcry_camellia_mod_CFLAGS) -MD -c -o $@ $<,"  CC    gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia.o")
-include gcry_camellia_mod-lib_libgcrypt_grub_cipher_camellia.d

gcry_camellia_mod_CFLAGS = $(COMMON_CFLAGS) -Wno-missing-field-initializers -Wno-error -I$(srcdir)/lib/libgcrypt_wrap
gcry_camellia_mod_LDFLAGS = $(COMMON_LDFLAGS)

