# -*- makefile -*-
# Generated by genmk.rb, please don't edit!

pkglib_MODULES += cpuid.mod
cpuid_mod_SOURCES = commands/i386/cpuid.c

clean-module-cpuid.mod.1:
	rm -f cpuid.mod cpuid_mod-commands_i386_cpuid.o

CLEAN_MODULE_TARGETS += clean-module-cpuid.mod.1

mostlyclean-module-cpuid.mod.1:
	rm -f cpuid_mod-commands_i386_cpuid.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-cpuid.mod.1

cpuid.mod: $(cpuid_mod_DEPENDENCIES) cpuid_mod-commands_i386_cpuid.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   cpuid.mod")

MODFILES += cpuid.mod

cpuid_mod-commands_i386_cpuid.o: commands/i386/cpuid.c $(commands/i386/cpuid.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386 -I$(srcdir)/commands/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -MD -c -o $@ $<,"  CC    cpuid_mod-commands_i386_cpuid.o")
-include cpuid_mod-commands_i386_cpuid.d

cpuid_mod_CFLAGS = $(COMMON_CFLAGS)
cpuid_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += at_keyboard.mod
at_keyboard_mod_SOURCES = term/at_keyboard.c

clean-module-at_keyboard.mod.1:
	rm -f at_keyboard.mod at_keyboard_mod-term_at_keyboard.o

CLEAN_MODULE_TARGETS += clean-module-at_keyboard.mod.1

mostlyclean-module-at_keyboard.mod.1:
	rm -f at_keyboard_mod-term_at_keyboard.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-at_keyboard.mod.1

at_keyboard.mod: $(at_keyboard_mod_DEPENDENCIES) at_keyboard_mod-term_at_keyboard.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   at_keyboard.mod")

MODFILES += at_keyboard.mod

at_keyboard_mod-term_at_keyboard.o: term/at_keyboard.c $(term/at_keyboard.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -MD -c -o $@ $<,"  CC    at_keyboard_mod-term_at_keyboard.o")
-include at_keyboard_mod-term_at_keyboard.d

at_keyboard_mod_CFLAGS = $(COMMON_CFLAGS)
at_keyboard_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += vga_text.mod
vga_text_mod_SOURCES = term/i386/pc/vga_text.c term/i386/vga_common.c

clean-module-vga_text.mod.1:
	rm -f vga_text.mod vga_text_mod-term_i386_pc_vga_text.o vga_text_mod-term_i386_vga_common.o

CLEAN_MODULE_TARGETS += clean-module-vga_text.mod.1

mostlyclean-module-vga_text.mod.1:
	rm -f vga_text_mod-term_i386_pc_vga_text.d vga_text_mod-term_i386_vga_common.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-vga_text.mod.1

vga_text.mod: $(vga_text_mod_DEPENDENCIES) vga_text_mod-term_i386_pc_vga_text.o vga_text_mod-term_i386_vga_common.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   vga_text.mod")

MODFILES += vga_text.mod

vga_text_mod-term_i386_pc_vga_text.o: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -MD -c -o $@ $<,"  CC    vga_text_mod-term_i386_pc_vga_text.o")
-include vga_text_mod-term_i386_pc_vga_text.d

vga_text_mod-term_i386_vga_common.o: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -MD -c -o $@ $<,"  CC    vga_text_mod-term_i386_vga_common.o")
-include vga_text_mod-term_i386_vga_common.d

vga_text_mod_CFLAGS = $(COMMON_CFLAGS)
vga_text_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += relocator.mod
relocator_mod_SOURCES = lib/i386/relocator.c lib/i386/relocator_asm.S lib/i386/relocator_backward.S

clean-module-relocator.mod.1:
	rm -f relocator.mod relocator_mod-lib_i386_relocator.o relocator_mod-lib_i386_relocator_asm.o relocator_mod-lib_i386_relocator_backward.o

CLEAN_MODULE_TARGETS += clean-module-relocator.mod.1

mostlyclean-module-relocator.mod.1:
	rm -f relocator_mod-lib_i386_relocator.d relocator_mod-lib_i386_relocator_asm.d relocator_mod-lib_i386_relocator_backward.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-relocator.mod.1

relocator.mod: $(relocator_mod_DEPENDENCIES) relocator_mod-lib_i386_relocator.o relocator_mod-lib_i386_relocator_asm.o relocator_mod-lib_i386_relocator_backward.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   relocator.mod")

MODFILES += relocator.mod

relocator_mod-lib_i386_relocator.o: lib/i386/relocator.c $(lib/i386/relocator.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -MD -c -o $@ $<,"  CC    relocator_mod-lib_i386_relocator.o")
-include relocator_mod-lib_i386_relocator.d

relocator_mod-lib_i386_relocator_asm.o: lib/i386/relocator_asm.S $(lib/i386/relocator_asm.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    relocator_mod-lib_i386_relocator_asm.o")
else
	$(call quiet-command,$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    relocator_mod-lib_i386_relocator_asm.o")
endif
-include relocator_mod-lib_i386_relocator_asm.d

relocator_mod-lib_i386_relocator_backward.o: lib/i386/relocator_backward.S $(lib/i386/relocator_backward.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    relocator_mod-lib_i386_relocator_backward.o")
else
	$(call quiet-command,$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    relocator_mod-lib_i386_relocator_backward.o")
endif
-include relocator_mod-lib_i386_relocator_backward.d

relocator_mod_CFLAGS = $(COMMON_CFLAGS)
relocator_mod_ASFLAGS = $(COMMON_ASFLAGS)
relocator_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += relocator16.mod
relocator16_mod_SOURCES = lib/i386/relocator16.c lib/i386/relocator16_asm.S

clean-module-relocator16.mod.1:
	rm -f relocator16.mod relocator16_mod-lib_i386_relocator16.o relocator16_mod-lib_i386_relocator16_asm.o

CLEAN_MODULE_TARGETS += clean-module-relocator16.mod.1

mostlyclean-module-relocator16.mod.1:
	rm -f relocator16_mod-lib_i386_relocator16.d relocator16_mod-lib_i386_relocator16_asm.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-relocator16.mod.1

relocator16.mod: $(relocator16_mod_DEPENDENCIES) relocator16_mod-lib_i386_relocator16.o relocator16_mod-lib_i386_relocator16_asm.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   relocator16.mod")

MODFILES += relocator16.mod

relocator16_mod-lib_i386_relocator16.o: lib/i386/relocator16.c $(lib/i386/relocator16.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(relocator16_mod_CFLAGS) -MD -c -o $@ $<,"  CC    relocator16_mod-lib_i386_relocator16.o")
-include relocator16_mod-lib_i386_relocator16.d

relocator16_mod-lib_i386_relocator16_asm.o: lib/i386/relocator16_asm.S $(lib/i386/relocator16_asm.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator16_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    relocator16_mod-lib_i386_relocator16_asm.o")
else
	$(call quiet-command,$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator16_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    relocator16_mod-lib_i386_relocator16_asm.o")
endif
-include relocator16_mod-lib_i386_relocator16_asm.d

relocator16_mod_CFLAGS = $(COMMON_CFLAGS)
relocator16_mod_ASFLAGS = $(COMMON_ASFLAGS)
relocator16_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += ata.mod
ata_mod_SOURCES = disk/ata.c

clean-module-ata.mod.1:
	rm -f ata.mod ata_mod-disk_ata.o

CLEAN_MODULE_TARGETS += clean-module-ata.mod.1

mostlyclean-module-ata.mod.1:
	rm -f ata_mod-disk_ata.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-ata.mod.1

ata.mod: $(ata_mod_DEPENDENCIES) ata_mod-disk_ata.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   ata.mod")

MODFILES += ata.mod

ata_mod-disk_ata.o: disk/ata.c $(disk/ata.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -MD -c -o $@ $<,"  CC    ata_mod-disk_ata.o")
-include ata_mod-disk_ata.d

ata_mod_CFLAGS = $(COMMON_CFLAGS)
ata_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For setpci.mod
pkglib_MODULES += setpci.mod
setpci_mod_SOURCES = commands/setpci.c

clean-module-setpci.mod.1:
	rm -f setpci.mod setpci_mod-commands_setpci.o

CLEAN_MODULE_TARGETS += clean-module-setpci.mod.1

mostlyclean-module-setpci.mod.1:
	rm -f setpci_mod-commands_setpci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-setpci.mod.1

setpci.mod: $(setpci_mod_DEPENDENCIES) setpci_mod-commands_setpci.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   setpci.mod")

MODFILES += setpci.mod

setpci_mod-commands_setpci.o: commands/setpci.c $(commands/setpci.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -MD -c -o $@ $<,"  CC    setpci_mod-commands_setpci.o")
-include setpci_mod-commands_setpci.d

setpci_mod_CFLAGS = $(COMMON_CFLAGS)
setpci_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += multiboot.mod
multiboot_mod_SOURCES = loader/i386/multiboot.c \
			loader/i386/multiboot_mbi.c \
                        loader/multiboot_loader.c

clean-module-multiboot.mod.1:
	rm -f multiboot.mod multiboot_mod-loader_i386_multiboot.o multiboot_mod-loader_i386_multiboot_mbi.o multiboot_mod-loader_multiboot_loader.o

CLEAN_MODULE_TARGETS += clean-module-multiboot.mod.1

mostlyclean-module-multiboot.mod.1:
	rm -f multiboot_mod-loader_i386_multiboot.d multiboot_mod-loader_i386_multiboot_mbi.d multiboot_mod-loader_multiboot_loader.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-multiboot.mod.1

multiboot.mod: $(multiboot_mod_DEPENDENCIES) multiboot_mod-loader_i386_multiboot.o multiboot_mod-loader_i386_multiboot_mbi.o multiboot_mod-loader_multiboot_loader.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   multiboot.mod")

MODFILES += multiboot.mod

multiboot_mod-loader_i386_multiboot.o: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    multiboot_mod-loader_i386_multiboot.o")
-include multiboot_mod-loader_i386_multiboot.d

multiboot_mod-loader_i386_multiboot_mbi.o: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    multiboot_mod-loader_i386_multiboot_mbi.o")
-include multiboot_mod-loader_i386_multiboot_mbi.d

multiboot_mod-loader_multiboot_loader.o: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    multiboot_mod-loader_multiboot_loader.o")
-include multiboot_mod-loader_multiboot_loader.d

multiboot_mod_CFLAGS = $(COMMON_CFLAGS)
multiboot_mod_LDFLAGS = $(COMMON_LDFLAGS)
multiboot_mod_ASFLAGS = $(COMMON_ASFLAGS)

pkglib_MODULES += multiboot2.mod
multiboot2_mod_SOURCES = loader/i386/multiboot.c \
			 loader/i386/multiboot_mbi.c \
                         loader/multiboot_loader.c

clean-module-multiboot2.mod.1:
	rm -f multiboot2.mod multiboot2_mod-loader_i386_multiboot.o multiboot2_mod-loader_i386_multiboot_mbi.o multiboot2_mod-loader_multiboot_loader.o

CLEAN_MODULE_TARGETS += clean-module-multiboot2.mod.1

mostlyclean-module-multiboot2.mod.1:
	rm -f multiboot2_mod-loader_i386_multiboot.d multiboot2_mod-loader_i386_multiboot_mbi.d multiboot2_mod-loader_multiboot_loader.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-multiboot2.mod.1

multiboot2.mod: $(multiboot2_mod_DEPENDENCIES) multiboot2_mod-loader_i386_multiboot.o multiboot2_mod-loader_i386_multiboot_mbi.o multiboot2_mod-loader_multiboot_loader.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   multiboot2.mod")

MODFILES += multiboot2.mod

multiboot2_mod-loader_i386_multiboot.o: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -MD -c -o $@ $<,"  CC    multiboot2_mod-loader_i386_multiboot.o")
-include multiboot2_mod-loader_i386_multiboot.d

multiboot2_mod-loader_i386_multiboot_mbi.o: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -MD -c -o $@ $<,"  CC    multiboot2_mod-loader_i386_multiboot_mbi.o")
-include multiboot2_mod-loader_i386_multiboot_mbi.d

multiboot2_mod-loader_multiboot_loader.o: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -MD -c -o $@ $<,"  CC    multiboot2_mod-loader_multiboot_loader.o")
-include multiboot2_mod-loader_multiboot_loader.d

multiboot2_mod_CFLAGS = $(COMMON_CFLAGS) -DGRUB_USE_MULTIBOOT2
multiboot2_mod_LDFLAGS = $(COMMON_LDFLAGS)
multiboot2_mod_ASFLAGS = $(COMMON_ASFLAGS)
