# -*- makefile -*-
# Generated by genmk.rb, please don't edit!

GRUB_KERNEL_MACHINE_LINK_ADDR = 0x8200

COMMON_ASFLAGS = -nostdinc -fno-builtin -m32
COMMON_CFLAGS = -fno-builtin -mrtd -mregparm=3 -m32
COMMON_LDFLAGS = -m32 -nostdlib

# Used by various components.  These rules need to precede them.
script/lexer.c_DEPENDENCIES = grub_script.tab.h



bin_UTILITIES += grub-mkisofs
grub_mkisofs_SOURCES = util/mkisofs/eltorito.c 				\
	util/mkisofs/hash.c util/mkisofs/joliet.c			\
	util/mkisofs/match.c util/mkisofs/mkisofs.c			\
	util/mkisofs/multi.c util/mkisofs/name.c			\
	util/mkisofs/rock.c util/mkisofs/tree.c				\
	util/mkisofs/write.c						\
	\
	gnulib/fnmatch.c gnulib/error.c gnulib/progname.c

clean-utility-grub-mkisofs.1:
	rm -f grub-mkisofs$(EXEEXT) grub_mkisofs-util_mkisofs_eltorito.o grub_mkisofs-util_mkisofs_hash.o grub_mkisofs-util_mkisofs_joliet.o grub_mkisofs-util_mkisofs_match.o grub_mkisofs-util_mkisofs_mkisofs.o grub_mkisofs-util_mkisofs_multi.o grub_mkisofs-util_mkisofs_name.o grub_mkisofs-util_mkisofs_rock.o grub_mkisofs-util_mkisofs_tree.o grub_mkisofs-util_mkisofs_write.o grub_mkisofs-gnulib_fnmatch.o grub_mkisofs-gnulib_error.o grub_mkisofs-gnulib_progname.o

CLEAN_UTILITY_TARGETS += clean-utility-grub-mkisofs.1

mostlyclean-utility-grub-mkisofs.1:
	rm -f grub_mkisofs-util_mkisofs_eltorito.d grub_mkisofs-util_mkisofs_hash.d grub_mkisofs-util_mkisofs_joliet.d grub_mkisofs-util_mkisofs_match.d grub_mkisofs-util_mkisofs_mkisofs.d grub_mkisofs-util_mkisofs_multi.d grub_mkisofs-util_mkisofs_name.d grub_mkisofs-util_mkisofs_rock.d grub_mkisofs-util_mkisofs_tree.d grub_mkisofs-util_mkisofs_write.d grub_mkisofs-gnulib_fnmatch.d grub_mkisofs-gnulib_error.d grub_mkisofs-gnulib_progname.d

MOSTLYCLEAN_UTILITY_TARGETS += mostlyclean-utility-grub-mkisofs.1

grub_mkisofs_OBJECTS += grub_mkisofs-util_mkisofs_eltorito.o grub_mkisofs-util_mkisofs_hash.o grub_mkisofs-util_mkisofs_joliet.o grub_mkisofs-util_mkisofs_match.o grub_mkisofs-util_mkisofs_mkisofs.o grub_mkisofs-util_mkisofs_multi.o grub_mkisofs-util_mkisofs_name.o grub_mkisofs-util_mkisofs_rock.o grub_mkisofs-util_mkisofs_tree.o grub_mkisofs-util_mkisofs_write.o grub_mkisofs-gnulib_fnmatch.o grub_mkisofs-gnulib_error.o grub_mkisofs-gnulib_progname.o

grub_mkisofs-util_mkisofs_eltorito.o: util/mkisofs/eltorito.c $(util/mkisofs/eltorito.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_eltorito.o")
-include grub_mkisofs-util_mkisofs_eltorito.d

grub_mkisofs-util_mkisofs_hash.o: util/mkisofs/hash.c $(util/mkisofs/hash.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_hash.o")
-include grub_mkisofs-util_mkisofs_hash.d

grub_mkisofs-util_mkisofs_joliet.o: util/mkisofs/joliet.c $(util/mkisofs/joliet.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_joliet.o")
-include grub_mkisofs-util_mkisofs_joliet.d

grub_mkisofs-util_mkisofs_match.o: util/mkisofs/match.c $(util/mkisofs/match.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_match.o")
-include grub_mkisofs-util_mkisofs_match.d

grub_mkisofs-util_mkisofs_mkisofs.o: util/mkisofs/mkisofs.c $(util/mkisofs/mkisofs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_mkisofs.o")
-include grub_mkisofs-util_mkisofs_mkisofs.d

grub_mkisofs-util_mkisofs_multi.o: util/mkisofs/multi.c $(util/mkisofs/multi.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_multi.o")
-include grub_mkisofs-util_mkisofs_multi.d

grub_mkisofs-util_mkisofs_name.o: util/mkisofs/name.c $(util/mkisofs/name.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_name.o")
-include grub_mkisofs-util_mkisofs_name.d

grub_mkisofs-util_mkisofs_rock.o: util/mkisofs/rock.c $(util/mkisofs/rock.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_rock.o")
-include grub_mkisofs-util_mkisofs_rock.d

grub_mkisofs-util_mkisofs_tree.o: util/mkisofs/tree.c $(util/mkisofs/tree.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_tree.o")
-include grub_mkisofs-util_mkisofs_tree.d

grub_mkisofs-util_mkisofs_write.o: util/mkisofs/write.c $(util/mkisofs/write.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/mkisofs -I$(srcdir)/util/mkisofs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-util_mkisofs_write.o")
-include grub_mkisofs-util_mkisofs_write.d

grub_mkisofs-gnulib_fnmatch.o: gnulib/fnmatch.c $(gnulib/fnmatch.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ignulib -I$(srcdir)/gnulib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-gnulib_fnmatch.o")
-include grub_mkisofs-gnulib_fnmatch.d

grub_mkisofs-gnulib_error.o: gnulib/error.c $(gnulib/error.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ignulib -I$(srcdir)/gnulib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-gnulib_error.o")
-include grub_mkisofs-gnulib_error.d

grub_mkisofs-gnulib_progname.o: gnulib/progname.c $(gnulib/progname.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ignulib -I$(srcdir)/gnulib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkisofs_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkisofs-gnulib_progname.o")
-include grub_mkisofs-gnulib_progname.d

grub_mkisofs_CFLAGS = -D_FILE_OFFSET_BITS=64 				\
	-I$(srcdir)/util/mkisofs/include				\
	-Wno-all -Werror


# Images.
pkglib_IMAGES = boot.img cdboot.img diskboot.img pxeboot.img lnxboot.img

# For boot.img.
boot_img_SOURCES = boot/i386/pc/boot.S

clean-image-boot.img.1:
	rm -f boot.img boot.exec boot_img-boot_i386_pc_boot.o

CLEAN_IMAGE_TARGETS += clean-image-boot.img.1

mostlyclean-image-boot.img.1:
	rm -f boot_img-boot_i386_pc_boot.d

MOSTLYCLEAN_IMAGE_TARGETS += mostlyclean-image-boot.img.1

boot.img: boot_img-boot_i386_pc_boot.o grub-mkimg
	$(call quiet-command,./grub-mkimg -o $@ -b $(boot_img_LINKADDR) $(filter %.o, $^),"  IMG   boot.img")

boot_img-boot_i386_pc_boot.o: boot/i386/pc/boot.S $(boot/i386/pc/boot.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(boot_img_ASFLAGS) -MD -c -o $@ $<,"  AS    boot_img-boot_i386_pc_boot.o")
else
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(boot_img_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    boot_img-boot_i386_pc_boot.o")
endif
-include boot_img-boot_i386_pc_boot.d

boot_img_ASFLAGS = $(COMMON_ASFLAGS)
boot_img_LINKADDR = 0x7C00

# For pxeboot.img
pxeboot_img_SOURCES = boot/i386/pc/pxeboot.S

clean-image-pxeboot.img.1:
	rm -f pxeboot.img pxeboot.exec pxeboot_img-boot_i386_pc_pxeboot.o

CLEAN_IMAGE_TARGETS += clean-image-pxeboot.img.1

mostlyclean-image-pxeboot.img.1:
	rm -f pxeboot_img-boot_i386_pc_pxeboot.d

MOSTLYCLEAN_IMAGE_TARGETS += mostlyclean-image-pxeboot.img.1

pxeboot.img: pxeboot_img-boot_i386_pc_pxeboot.o grub-mkimg
	$(call quiet-command,./grub-mkimg -o $@ -b $(pxeboot_img_LINKADDR) $(filter %.o, $^),"  IMG   pxeboot.img")

pxeboot_img-boot_i386_pc_pxeboot.o: boot/i386/pc/pxeboot.S $(boot/i386/pc/pxeboot.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(pxeboot_img_ASFLAGS) -MD -c -o $@ $<,"  AS    pxeboot_img-boot_i386_pc_pxeboot.o")
else
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(pxeboot_img_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    pxeboot_img-boot_i386_pc_pxeboot.o")
endif
-include pxeboot_img-boot_i386_pc_pxeboot.d

pxeboot_img_ASFLAGS = $(COMMON_ASFLAGS)
pxeboot_img_LINKADDR = 0x7C00

# For diskboot.img.
diskboot_img_SOURCES = boot/i386/pc/diskboot.S

clean-image-diskboot.img.1:
	rm -f diskboot.img diskboot.exec diskboot_img-boot_i386_pc_diskboot.o

CLEAN_IMAGE_TARGETS += clean-image-diskboot.img.1

mostlyclean-image-diskboot.img.1:
	rm -f diskboot_img-boot_i386_pc_diskboot.d

MOSTLYCLEAN_IMAGE_TARGETS += mostlyclean-image-diskboot.img.1

diskboot.img: diskboot_img-boot_i386_pc_diskboot.o grub-mkimg
	$(call quiet-command,./grub-mkimg -o $@ -b $(diskboot_img_LINKADDR) $(filter %.o, $^),"  IMG   diskboot.img")

diskboot_img-boot_i386_pc_diskboot.o: boot/i386/pc/diskboot.S $(boot/i386/pc/diskboot.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(diskboot_img_ASFLAGS) -MD -c -o $@ $<,"  AS    diskboot_img-boot_i386_pc_diskboot.o")
else
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(diskboot_img_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    diskboot_img-boot_i386_pc_diskboot.o")
endif
-include diskboot_img-boot_i386_pc_diskboot.d

diskboot_img_ASFLAGS = $(COMMON_ASFLAGS)
diskboot_img_LINKADDR = 0x8000

# For lnxboot.img.
lnxboot_img_SOURCES = boot/i386/pc/lnxboot.S

clean-image-lnxboot.img.1:
	rm -f lnxboot.img lnxboot.exec lnxboot_img-boot_i386_pc_lnxboot.o

CLEAN_IMAGE_TARGETS += clean-image-lnxboot.img.1

mostlyclean-image-lnxboot.img.1:
	rm -f lnxboot_img-boot_i386_pc_lnxboot.d

MOSTLYCLEAN_IMAGE_TARGETS += mostlyclean-image-lnxboot.img.1

lnxboot.img: lnxboot_img-boot_i386_pc_lnxboot.o grub-mkimg
	$(call quiet-command,./grub-mkimg -o $@ -b $(lnxboot_img_LINKADDR) $(filter %.o, $^),"  IMG   lnxboot.img")

lnxboot_img-boot_i386_pc_lnxboot.o: boot/i386/pc/lnxboot.S $(boot/i386/pc/lnxboot.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(lnxboot_img_ASFLAGS) -MD -c -o $@ $<,"  AS    lnxboot_img-boot_i386_pc_lnxboot.o")
else
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(lnxboot_img_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    lnxboot_img-boot_i386_pc_lnxboot.o")
endif
-include lnxboot_img-boot_i386_pc_lnxboot.d

lnxboot_img_ASFLAGS = $(COMMON_ASFLAGS)
lnxboot_img_LINKADDR = 0x6000

# For cdboot.img.
cdboot_img_SOURCES = boot/i386/pc/cdboot.S

clean-image-cdboot.img.1:
	rm -f cdboot.img cdboot.exec cdboot_img-boot_i386_pc_cdboot.o

CLEAN_IMAGE_TARGETS += clean-image-cdboot.img.1

mostlyclean-image-cdboot.img.1:
	rm -f cdboot_img-boot_i386_pc_cdboot.d

MOSTLYCLEAN_IMAGE_TARGETS += mostlyclean-image-cdboot.img.1

cdboot.img: cdboot_img-boot_i386_pc_cdboot.o grub-mkimg
	$(call quiet-command,./grub-mkimg -o $@ -b $(cdboot_img_LINKADDR) $(filter %.o, $^),"  IMG   cdboot.img")

cdboot_img-boot_i386_pc_cdboot.o: boot/i386/pc/cdboot.S $(boot/i386/pc/cdboot.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(cdboot_img_ASFLAGS) -MD -c -o $@ $<,"  AS    cdboot_img-boot_i386_pc_cdboot.o")
else
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/pc -I$(srcdir)/boot/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(cdboot_img_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    cdboot_img-boot_i386_pc_cdboot.o")
endif
-include cdboot_img-boot_i386_pc_cdboot.d

cdboot_img_ASFLAGS = $(COMMON_ASFLAGS)
cdboot_img_LINKADDR = 0x7C00

# Utilities.
bin_UTILITIES = grub-mkimage
sbin_UTILITIES = grub-setup

# For grub-mkimage.
grub_mkimage_SOURCES = gnulib/progname.c util/grub-mkrawimage.c \
	util/misc.c util/resolve.c lib/LzmaEnc.c lib/LzFind.c util/obj.c \
	kern/list.c

clean-utility-grub-mkimage.1:
	rm -f grub-mkimage$(EXEEXT) grub_mkimage-gnulib_progname.o grub_mkimage-util_grub_mkrawimage.o grub_mkimage-util_misc.o grub_mkimage-util_resolve.o grub_mkimage-lib_LzmaEnc.o grub_mkimage-lib_LzFind.o grub_mkimage-util_obj.o grub_mkimage-kern_list.o

CLEAN_UTILITY_TARGETS += clean-utility-grub-mkimage.1

mostlyclean-utility-grub-mkimage.1:
	rm -f grub_mkimage-gnulib_progname.d grub_mkimage-util_grub_mkrawimage.d grub_mkimage-util_misc.d grub_mkimage-util_resolve.d grub_mkimage-lib_LzmaEnc.d grub_mkimage-lib_LzFind.d grub_mkimage-util_obj.d grub_mkimage-kern_list.d

MOSTLYCLEAN_UTILITY_TARGETS += mostlyclean-utility-grub-mkimage.1

grub_mkimage_OBJECTS += grub_mkimage-gnulib_progname.o grub_mkimage-util_grub_mkrawimage.o grub_mkimage-util_misc.o grub_mkimage-util_resolve.o grub_mkimage-lib_LzmaEnc.o grub_mkimage-lib_LzFind.o grub_mkimage-util_obj.o grub_mkimage-kern_list.o

grub_mkimage-gnulib_progname.o: gnulib/progname.c $(gnulib/progname.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ignulib -I$(srcdir)/gnulib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-gnulib_progname.o")
-include grub_mkimage-gnulib_progname.d

grub_mkimage-util_grub_mkrawimage.o: util/grub-mkrawimage.c $(util/grub-mkrawimage.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_grub_mkrawimage.o")
-include grub_mkimage-util_grub_mkrawimage.d

grub_mkimage-util_misc.o: util/misc.c $(util/misc.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_misc.o")
-include grub_mkimage-util_misc.d

grub_mkimage-util_resolve.o: util/resolve.c $(util/resolve.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_resolve.o")
-include grub_mkimage-util_resolve.d

grub_mkimage-lib_LzmaEnc.o: lib/LzmaEnc.c $(lib/LzmaEnc.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ilib -I$(srcdir)/lib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-lib_LzmaEnc.o")
-include grub_mkimage-lib_LzmaEnc.d

grub_mkimage-lib_LzFind.o: lib/LzFind.c $(lib/LzFind.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ilib -I$(srcdir)/lib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-lib_LzFind.o")
-include grub_mkimage-lib_LzFind.d

grub_mkimage-util_obj.o: util/obj.c $(util/obj.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_obj.o")
-include grub_mkimage-util_obj.d

grub_mkimage-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-kern_list.o")
-include grub_mkimage-kern_list.d

grub_mkimage_CFLAGS = -DGRUB_KERNEL_MACHINE_LINK_ADDR=$(GRUB_KERNEL_MACHINE_LINK_ADDR)
util/grub-mkrawimage.c_DEPENDENCIES = Makefile

# For grub-setup.
util/i386/pc/grub-setup.c_DEPENDENCIES = grub_setup_init.h
grub_setup_SOURCES = gnulib/progname.c \
	util/i386/pc/grub-setup.c util/hostdisk.c	\
	util/misc.c util/getroot.c kern/device.c kern/disk.c	\
	kern/err.c kern/misc.c kern/parser.c kern/partition.c	\
	kern/file.c kern/fs.c kern/env.c fs/fshelp.c		\
	kern/list.c \
	\
	fs/affs.c fs/cpio.c fs/ext2.c fs/fat.c fs/hfs.c		\
	fs/hfsplus.c fs/iso9660.c fs/udf.c fs/jfs.c fs/minix.c	\
	fs/ntfs.c fs/ntfscomp.c fs/reiserfs.c fs/sfs.c		\
	fs/ufs.c fs/ufs2.c fs/xfs.c fs/afs.c fs/afs_be.c	\
	fs/befs.c fs/befs_be.c fs/tar.c			\
	\
	partmap/msdos.c partmap/gpt.c				\
	\
	disk/raid.c disk/mdraid_linux.c disk/lvm.c		\
	util/raid.c util/lvm.c					\
	grub_setup_init.c

clean-utility-grub-setup.1:
	rm -f grub-setup$(EXEEXT) grub_setup-gnulib_progname.o grub_setup-util_i386_pc_grub_setup.o grub_setup-util_hostdisk.o grub_setup-util_misc.o grub_setup-util_getroot.o grub_setup-kern_device.o grub_setup-kern_disk.o grub_setup-kern_err.o grub_setup-kern_misc.o grub_setup-kern_parser.o grub_setup-kern_partition.o grub_setup-kern_file.o grub_setup-kern_fs.o grub_setup-kern_env.o grub_setup-fs_fshelp.o grub_setup-kern_list.o grub_setup-fs_affs.o grub_setup-fs_cpio.o grub_setup-fs_ext2.o grub_setup-fs_fat.o grub_setup-fs_hfs.o grub_setup-fs_hfsplus.o grub_setup-fs_iso9660.o grub_setup-fs_udf.o grub_setup-fs_jfs.o grub_setup-fs_minix.o grub_setup-fs_ntfs.o grub_setup-fs_ntfscomp.o grub_setup-fs_reiserfs.o grub_setup-fs_sfs.o grub_setup-fs_ufs.o grub_setup-fs_ufs2.o grub_setup-fs_xfs.o grub_setup-fs_afs.o grub_setup-fs_afs_be.o grub_setup-fs_befs.o grub_setup-fs_befs_be.o grub_setup-fs_tar.o grub_setup-partmap_msdos.o grub_setup-partmap_gpt.o grub_setup-disk_raid.o grub_setup-disk_mdraid_linux.o grub_setup-disk_lvm.o grub_setup-util_raid.o grub_setup-util_lvm.o grub_setup-grub_setup_init.o

CLEAN_UTILITY_TARGETS += clean-utility-grub-setup.1

mostlyclean-utility-grub-setup.1:
	rm -f grub_setup-gnulib_progname.d grub_setup-util_i386_pc_grub_setup.d grub_setup-util_hostdisk.d grub_setup-util_misc.d grub_setup-util_getroot.d grub_setup-kern_device.d grub_setup-kern_disk.d grub_setup-kern_err.d grub_setup-kern_misc.d grub_setup-kern_parser.d grub_setup-kern_partition.d grub_setup-kern_file.d grub_setup-kern_fs.d grub_setup-kern_env.d grub_setup-fs_fshelp.d grub_setup-kern_list.d grub_setup-fs_affs.d grub_setup-fs_cpio.d grub_setup-fs_ext2.d grub_setup-fs_fat.d grub_setup-fs_hfs.d grub_setup-fs_hfsplus.d grub_setup-fs_iso9660.d grub_setup-fs_udf.d grub_setup-fs_jfs.d grub_setup-fs_minix.d grub_setup-fs_ntfs.d grub_setup-fs_ntfscomp.d grub_setup-fs_reiserfs.d grub_setup-fs_sfs.d grub_setup-fs_ufs.d grub_setup-fs_ufs2.d grub_setup-fs_xfs.d grub_setup-fs_afs.d grub_setup-fs_afs_be.d grub_setup-fs_befs.d grub_setup-fs_befs_be.d grub_setup-fs_tar.d grub_setup-partmap_msdos.d grub_setup-partmap_gpt.d grub_setup-disk_raid.d grub_setup-disk_mdraid_linux.d grub_setup-disk_lvm.d grub_setup-util_raid.d grub_setup-util_lvm.d grub_setup-grub_setup_init.d

MOSTLYCLEAN_UTILITY_TARGETS += mostlyclean-utility-grub-setup.1

grub_setup_OBJECTS += grub_setup-gnulib_progname.o grub_setup-util_i386_pc_grub_setup.o grub_setup-util_hostdisk.o grub_setup-util_misc.o grub_setup-util_getroot.o grub_setup-kern_device.o grub_setup-kern_disk.o grub_setup-kern_err.o grub_setup-kern_misc.o grub_setup-kern_parser.o grub_setup-kern_partition.o grub_setup-kern_file.o grub_setup-kern_fs.o grub_setup-kern_env.o grub_setup-fs_fshelp.o grub_setup-kern_list.o grub_setup-fs_affs.o grub_setup-fs_cpio.o grub_setup-fs_ext2.o grub_setup-fs_fat.o grub_setup-fs_hfs.o grub_setup-fs_hfsplus.o grub_setup-fs_iso9660.o grub_setup-fs_udf.o grub_setup-fs_jfs.o grub_setup-fs_minix.o grub_setup-fs_ntfs.o grub_setup-fs_ntfscomp.o grub_setup-fs_reiserfs.o grub_setup-fs_sfs.o grub_setup-fs_ufs.o grub_setup-fs_ufs2.o grub_setup-fs_xfs.o grub_setup-fs_afs.o grub_setup-fs_afs_be.o grub_setup-fs_befs.o grub_setup-fs_befs_be.o grub_setup-fs_tar.o grub_setup-partmap_msdos.o grub_setup-partmap_gpt.o grub_setup-disk_raid.o grub_setup-disk_mdraid_linux.o grub_setup-disk_lvm.o grub_setup-util_raid.o grub_setup-util_lvm.o grub_setup-grub_setup_init.o

grub_setup-gnulib_progname.o: gnulib/progname.c $(gnulib/progname.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ignulib -I$(srcdir)/gnulib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-gnulib_progname.o")
-include grub_setup-gnulib_progname.d

grub_setup-util_i386_pc_grub_setup.o: util/i386/pc/grub-setup.c $(util/i386/pc/grub-setup.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/i386/pc -I$(srcdir)/util/i386/pc $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-util_i386_pc_grub_setup.o")
-include grub_setup-util_i386_pc_grub_setup.d

grub_setup-util_hostdisk.o: util/hostdisk.c $(util/hostdisk.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-util_hostdisk.o")
-include grub_setup-util_hostdisk.d

grub_setup-util_misc.o: util/misc.c $(util/misc.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-util_misc.o")
-include grub_setup-util_misc.d

grub_setup-util_getroot.o: util/getroot.c $(util/getroot.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-util_getroot.o")
-include grub_setup-util_getroot.d

grub_setup-kern_device.o: kern/device.c $(kern/device.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_device.o")
-include grub_setup-kern_device.d

grub_setup-kern_disk.o: kern/disk.c $(kern/disk.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_disk.o")
-include grub_setup-kern_disk.d

grub_setup-kern_err.o: kern/err.c $(kern/err.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_err.o")
-include grub_setup-kern_err.d

grub_setup-kern_misc.o: kern/misc.c $(kern/misc.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_misc.o")
-include grub_setup-kern_misc.d

grub_setup-kern_parser.o: kern/parser.c $(kern/parser.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_parser.o")
-include grub_setup-kern_parser.d

grub_setup-kern_partition.o: kern/partition.c $(kern/partition.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_partition.o")
-include grub_setup-kern_partition.d

grub_setup-kern_file.o: kern/file.c $(kern/file.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_file.o")
-include grub_setup-kern_file.d

grub_setup-kern_fs.o: kern/fs.c $(kern/fs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_fs.o")
-include grub_setup-kern_fs.d

grub_setup-kern_env.o: kern/env.c $(kern/env.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_env.o")
-include grub_setup-kern_env.d

grub_setup-fs_fshelp.o: fs/fshelp.c $(fs/fshelp.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_fshelp.o")
-include grub_setup-fs_fshelp.d

grub_setup-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-kern_list.o")
-include grub_setup-kern_list.d

grub_setup-fs_affs.o: fs/affs.c $(fs/affs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_affs.o")
-include grub_setup-fs_affs.d

grub_setup-fs_cpio.o: fs/cpio.c $(fs/cpio.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_cpio.o")
-include grub_setup-fs_cpio.d

grub_setup-fs_ext2.o: fs/ext2.c $(fs/ext2.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_ext2.o")
-include grub_setup-fs_ext2.d

grub_setup-fs_fat.o: fs/fat.c $(fs/fat.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_fat.o")
-include grub_setup-fs_fat.d

grub_setup-fs_hfs.o: fs/hfs.c $(fs/hfs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_hfs.o")
-include grub_setup-fs_hfs.d

grub_setup-fs_hfsplus.o: fs/hfsplus.c $(fs/hfsplus.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_hfsplus.o")
-include grub_setup-fs_hfsplus.d

grub_setup-fs_iso9660.o: fs/iso9660.c $(fs/iso9660.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_iso9660.o")
-include grub_setup-fs_iso9660.d

grub_setup-fs_udf.o: fs/udf.c $(fs/udf.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_udf.o")
-include grub_setup-fs_udf.d

grub_setup-fs_jfs.o: fs/jfs.c $(fs/jfs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_jfs.o")
-include grub_setup-fs_jfs.d

grub_setup-fs_minix.o: fs/minix.c $(fs/minix.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_minix.o")
-include grub_setup-fs_minix.d

grub_setup-fs_ntfs.o: fs/ntfs.c $(fs/ntfs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_ntfs.o")
-include grub_setup-fs_ntfs.d

grub_setup-fs_ntfscomp.o: fs/ntfscomp.c $(fs/ntfscomp.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_ntfscomp.o")
-include grub_setup-fs_ntfscomp.d

grub_setup-fs_reiserfs.o: fs/reiserfs.c $(fs/reiserfs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_reiserfs.o")
-include grub_setup-fs_reiserfs.d

grub_setup-fs_sfs.o: fs/sfs.c $(fs/sfs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_sfs.o")
-include grub_setup-fs_sfs.d

grub_setup-fs_ufs.o: fs/ufs.c $(fs/ufs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_ufs.o")
-include grub_setup-fs_ufs.d

grub_setup-fs_ufs2.o: fs/ufs2.c $(fs/ufs2.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_ufs2.o")
-include grub_setup-fs_ufs2.d

grub_setup-fs_xfs.o: fs/xfs.c $(fs/xfs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_xfs.o")
-include grub_setup-fs_xfs.d

grub_setup-fs_afs.o: fs/afs.c $(fs/afs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_afs.o")
-include grub_setup-fs_afs.d

grub_setup-fs_afs_be.o: fs/afs_be.c $(fs/afs_be.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_afs_be.o")
-include grub_setup-fs_afs_be.d

grub_setup-fs_befs.o: fs/befs.c $(fs/befs.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_befs.o")
-include grub_setup-fs_befs.d

grub_setup-fs_befs_be.o: fs/befs_be.c $(fs/befs_be.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_befs_be.o")
-include grub_setup-fs_befs_be.d

grub_setup-fs_tar.o: fs/tar.c $(fs/tar.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ifs -I$(srcdir)/fs $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-fs_tar.o")
-include grub_setup-fs_tar.d

grub_setup-partmap_msdos.o: partmap/msdos.c $(partmap/msdos.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ipartmap -I$(srcdir)/partmap $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-partmap_msdos.o")
-include grub_setup-partmap_msdos.d

grub_setup-partmap_gpt.o: partmap/gpt.c $(partmap/gpt.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ipartmap -I$(srcdir)/partmap $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-partmap_gpt.o")
-include grub_setup-partmap_gpt.d

grub_setup-disk_raid.o: disk/raid.c $(disk/raid.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Idisk -I$(srcdir)/disk $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-disk_raid.o")
-include grub_setup-disk_raid.d

grub_setup-disk_mdraid_linux.o: disk/mdraid_linux.c $(disk/mdraid_linux.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Idisk -I$(srcdir)/disk $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-disk_mdraid_linux.o")
-include grub_setup-disk_mdraid_linux.d

grub_setup-disk_lvm.o: disk/lvm.c $(disk/lvm.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Idisk -I$(srcdir)/disk $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-disk_lvm.o")
-include grub_setup-disk_lvm.d

grub_setup-util_raid.o: util/raid.c $(util/raid.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-util_raid.o")
-include grub_setup-util_raid.d

grub_setup-util_lvm.o: util/lvm.c $(util/lvm.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-util_lvm.o")
-include grub_setup-util_lvm.d

grub_setup-grub_setup_init.o: grub_setup_init.c $(grub_setup_init.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -I. -I$(srcdir)/. $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_setup_CFLAGS) -MD -c -o $@ $<,"  CC    grub_setup-grub_setup_init.o")
-include grub_setup-grub_setup_init.d



bin_SCRIPTS += grub-mkrescue
grub_mkrescue_SOURCES = util/grub-mkrescue.in
CLEANFILES += grub-mkrescue

grub-mkrescue: util/grub-mkrescue.in $(util/grub-mkrescue.in_DEPENDENCIES) config.status
	./config.status --file=-:util/grub-mkrescue.in | sed -e 's,@pkglib_DATA@,$(pkglib_DATA),g' > $@
	chmod +x $@


pkglib_MODULES = kernel.mod biosdisk.mod chain.mod			\
	reboot.mod halt.mod				\
	vbe.mod vbetest.mod vbeinfo.mod play.mod serial.mod		\
	vga.mod memdisk.mod pci.mod lspci.mod				\
	aout.mod bsd.mod pxe.mod pxecmd.mod datetime.mod date.mod 	\
	datehook.mod lsmmap.mod ata_pthru.mod hdparm.mod 		\
	usb.mod uhci.mod ohci.mod usbtest.mod usbms.mod usb_keyboard.mod \
	efiemu.mod mmap.mod acpi.mod drivemap.mod loadbin.mod
# For kernel.mod.
kernel_mod_SOURCES = kern/i386/pc/startup.S \
	kern/i386/misc.S \
	kern/main.c kern/device.c \
	kern/disk.c kern/dl.c kern/file.c kern/fs.c kern/err.c \
	kern/misc.c kern/mm.c kern/term.c \
	kern/rescue_parser.c kern/rescue_reader.c \
	kern/time.c kern/list.c kern/handler.c kern/command.c kern/corecmd.c \
	kern/i386/pc/init.c kern/i386/pc/mmap.c \
	kern/parser.c kern/partition.c \
	kern/i386/tsc.c kern/i386/pit.c \
	kern/generic/rtc_get_time_ms.c \
	kern/generic/millisleep.c \
	kern/env.c \
	term/i386/pc/console.c term/i386/vga_common.c

clean-module-kernel.mod.1:
	rm -f kernel.mod kernel_mod-kern_i386_pc_startup.o kernel_mod-kern_i386_misc.o kernel_mod-kern_main.o kernel_mod-kern_device.o kernel_mod-kern_disk.o kernel_mod-kern_dl.o kernel_mod-kern_file.o kernel_mod-kern_fs.o kernel_mod-kern_err.o kernel_mod-kern_misc.o kernel_mod-kern_mm.o kernel_mod-kern_term.o kernel_mod-kern_rescue_parser.o kernel_mod-kern_rescue_reader.o kernel_mod-kern_time.o kernel_mod-kern_list.o kernel_mod-kern_handler.o kernel_mod-kern_command.o kernel_mod-kern_corecmd.o kernel_mod-kern_i386_pc_init.o kernel_mod-kern_i386_pc_mmap.o kernel_mod-kern_parser.o kernel_mod-kern_partition.o kernel_mod-kern_i386_tsc.o kernel_mod-kern_i386_pit.o kernel_mod-kern_generic_rtc_get_time_ms.o kernel_mod-kern_generic_millisleep.o kernel_mod-kern_env.o kernel_mod-term_i386_pc_console.o kernel_mod-term_i386_vga_common.o

CLEAN_MODULE_TARGETS += clean-module-kernel.mod.1

mostlyclean-module-kernel.mod.1:
	rm -f kernel_mod-kern_i386_pc_startup.d kernel_mod-kern_i386_misc.d kernel_mod-kern_main.d kernel_mod-kern_device.d kernel_mod-kern_disk.d kernel_mod-kern_dl.d kernel_mod-kern_file.d kernel_mod-kern_fs.d kernel_mod-kern_err.d kernel_mod-kern_misc.d kernel_mod-kern_mm.d kernel_mod-kern_term.d kernel_mod-kern_rescue_parser.d kernel_mod-kern_rescue_reader.d kernel_mod-kern_time.d kernel_mod-kern_list.d kernel_mod-kern_handler.d kernel_mod-kern_command.d kernel_mod-kern_corecmd.d kernel_mod-kern_i386_pc_init.d kernel_mod-kern_i386_pc_mmap.d kernel_mod-kern_parser.d kernel_mod-kern_partition.d kernel_mod-kern_i386_tsc.d kernel_mod-kern_i386_pit.d kernel_mod-kern_generic_rtc_get_time_ms.d kernel_mod-kern_generic_millisleep.d kernel_mod-kern_env.d kernel_mod-term_i386_pc_console.d kernel_mod-term_i386_vga_common.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-kernel.mod.1

kernel.mod: $(kernel_mod_DEPENDENCIES) kernel_mod-kern_i386_pc_startup.o kernel_mod-kern_i386_misc.o kernel_mod-kern_main.o kernel_mod-kern_device.o kernel_mod-kern_disk.o kernel_mod-kern_dl.o kernel_mod-kern_file.o kernel_mod-kern_fs.o kernel_mod-kern_err.o kernel_mod-kern_misc.o kernel_mod-kern_mm.o kernel_mod-kern_term.o kernel_mod-kern_rescue_parser.o kernel_mod-kern_rescue_reader.o kernel_mod-kern_time.o kernel_mod-kern_list.o kernel_mod-kern_handler.o kernel_mod-kern_command.o kernel_mod-kern_corecmd.o kernel_mod-kern_i386_pc_init.o kernel_mod-kern_i386_pc_mmap.o kernel_mod-kern_parser.o kernel_mod-kern_partition.o kernel_mod-kern_i386_tsc.o kernel_mod-kern_i386_pit.o kernel_mod-kern_generic_rtc_get_time_ms.o kernel_mod-kern_generic_millisleep.o kernel_mod-kern_env.o kernel_mod-term_i386_pc_console.o kernel_mod-term_i386_vga_common.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   kernel.mod")

MODFILES += kernel.mod

kernel_mod-kern_i386_pc_startup.o: kern/i386/pc/startup.S $(kern/i386/pc/startup.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/pc -I$(srcdir)/kern/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    kernel_mod-kern_i386_pc_startup.o")
else
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/pc -I$(srcdir)/kern/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    kernel_mod-kern_i386_pc_startup.o")
endif
-include kernel_mod-kern_i386_pc_startup.d

kernel_mod-kern_i386_misc.o: kern/i386/misc.S $(kern/i386/misc.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    kernel_mod-kern_i386_misc.o")
else
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    kernel_mod-kern_i386_misc.o")
endif
-include kernel_mod-kern_i386_misc.d

kernel_mod-kern_main.o: kern/main.c $(kern/main.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_main.o")
-include kernel_mod-kern_main.d

kernel_mod-kern_device.o: kern/device.c $(kern/device.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_device.o")
-include kernel_mod-kern_device.d

kernel_mod-kern_disk.o: kern/disk.c $(kern/disk.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_disk.o")
-include kernel_mod-kern_disk.d

kernel_mod-kern_dl.o: kern/dl.c $(kern/dl.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_dl.o")
-include kernel_mod-kern_dl.d

kernel_mod-kern_file.o: kern/file.c $(kern/file.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_file.o")
-include kernel_mod-kern_file.d

kernel_mod-kern_fs.o: kern/fs.c $(kern/fs.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_fs.o")
-include kernel_mod-kern_fs.d

kernel_mod-kern_err.o: kern/err.c $(kern/err.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_err.o")
-include kernel_mod-kern_err.d

kernel_mod-kern_misc.o: kern/misc.c $(kern/misc.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_misc.o")
-include kernel_mod-kern_misc.d

kernel_mod-kern_mm.o: kern/mm.c $(kern/mm.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_mm.o")
-include kernel_mod-kern_mm.d

kernel_mod-kern_term.o: kern/term.c $(kern/term.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_term.o")
-include kernel_mod-kern_term.d

kernel_mod-kern_rescue_parser.o: kern/rescue_parser.c $(kern/rescue_parser.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_rescue_parser.o")
-include kernel_mod-kern_rescue_parser.d

kernel_mod-kern_rescue_reader.o: kern/rescue_reader.c $(kern/rescue_reader.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_rescue_reader.o")
-include kernel_mod-kern_rescue_reader.d

kernel_mod-kern_time.o: kern/time.c $(kern/time.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_time.o")
-include kernel_mod-kern_time.d

kernel_mod-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_list.o")
-include kernel_mod-kern_list.d

kernel_mod-kern_handler.o: kern/handler.c $(kern/handler.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_handler.o")
-include kernel_mod-kern_handler.d

kernel_mod-kern_command.o: kern/command.c $(kern/command.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_command.o")
-include kernel_mod-kern_command.d

kernel_mod-kern_corecmd.o: kern/corecmd.c $(kern/corecmd.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_corecmd.o")
-include kernel_mod-kern_corecmd.d

kernel_mod-kern_i386_pc_init.o: kern/i386/pc/init.c $(kern/i386/pc/init.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/pc -I$(srcdir)/kern/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_pc_init.o")
-include kernel_mod-kern_i386_pc_init.d

kernel_mod-kern_i386_pc_mmap.o: kern/i386/pc/mmap.c $(kern/i386/pc/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/pc -I$(srcdir)/kern/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_pc_mmap.o")
-include kernel_mod-kern_i386_pc_mmap.d

kernel_mod-kern_parser.o: kern/parser.c $(kern/parser.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_parser.o")
-include kernel_mod-kern_parser.d

kernel_mod-kern_partition.o: kern/partition.c $(kern/partition.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_partition.o")
-include kernel_mod-kern_partition.d

kernel_mod-kern_i386_tsc.o: kern/i386/tsc.c $(kern/i386/tsc.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_tsc.o")
-include kernel_mod-kern_i386_tsc.d

kernel_mod-kern_i386_pit.o: kern/i386/pit.c $(kern/i386/pit.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_pit.o")
-include kernel_mod-kern_i386_pit.d

kernel_mod-kern_generic_rtc_get_time_ms.o: kern/generic/rtc_get_time_ms.c $(kern/generic/rtc_get_time_ms.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/generic -I$(srcdir)/kern/generic $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_generic_rtc_get_time_ms.o")
-include kernel_mod-kern_generic_rtc_get_time_ms.d

kernel_mod-kern_generic_millisleep.o: kern/generic/millisleep.c $(kern/generic/millisleep.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/generic -I$(srcdir)/kern/generic $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_generic_millisleep.o")
-include kernel_mod-kern_generic_millisleep.d

kernel_mod-kern_env.o: kern/env.c $(kern/env.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_env.o")
-include kernel_mod-kern_env.d

kernel_mod-term_i386_pc_console.o: term/i386/pc/console.c $(term/i386/pc/console.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-term_i386_pc_console.o")
-include kernel_mod-term_i386_pc_console.d

kernel_mod-term_i386_vga_common.o: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-term_i386_vga_common.o")
-include kernel_mod-term_i386_vga_common.d

kernel_mod_CFLAGS = $(COMMON_CFLAGS)  $(TARGET_IMG_CFLAGS)
kernel_mod_ASFLAGS = $(COMMON_ASFLAGS)

# For boot.mod.
pkglib_MODULES += boot.mod
boot_mod_SOURCES = commands/boot.c lib/i386/pc/biosnum.c

clean-module-boot.mod.1:
	rm -f boot.mod boot_mod-commands_boot.o boot_mod-lib_i386_pc_biosnum.o

CLEAN_MODULE_TARGETS += clean-module-boot.mod.1

mostlyclean-module-boot.mod.1:
	rm -f boot_mod-commands_boot.d boot_mod-lib_i386_pc_biosnum.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-boot.mod.1

boot.mod: $(boot_mod_DEPENDENCIES) boot_mod-commands_boot.o boot_mod-lib_i386_pc_biosnum.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   boot.mod")

MODFILES += boot.mod

boot_mod-commands_boot.o: commands/boot.c $(commands/boot.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(boot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    boot_mod-commands_boot.o")
-include boot_mod-commands_boot.d

boot_mod-lib_i386_pc_biosnum.o: lib/i386/pc/biosnum.c $(lib/i386/pc/biosnum.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/i386/pc -I$(srcdir)/lib/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(boot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    boot_mod-lib_i386_pc_biosnum.o")
-include boot_mod-lib_i386_pc_biosnum.d

boot_mod_CFLAGS = $(COMMON_CFLAGS)
boot_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For drivemap.mod.
drivemap_mod_SOURCES = commands/i386/pc/drivemap.c \
                       commands/i386/pc/drivemap_int13h.S

clean-module-drivemap.mod.1:
	rm -f drivemap.mod drivemap_mod-commands_i386_pc_drivemap.o drivemap_mod-commands_i386_pc_drivemap_int13h.o

CLEAN_MODULE_TARGETS += clean-module-drivemap.mod.1

mostlyclean-module-drivemap.mod.1:
	rm -f drivemap_mod-commands_i386_pc_drivemap.d drivemap_mod-commands_i386_pc_drivemap_int13h.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-drivemap.mod.1

drivemap.mod: $(drivemap_mod_DEPENDENCIES) drivemap_mod-commands_i386_pc_drivemap.o drivemap_mod-commands_i386_pc_drivemap_int13h.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   drivemap.mod")

MODFILES += drivemap.mod

drivemap_mod-commands_i386_pc_drivemap.o: commands/i386/pc/drivemap.c $(commands/i386/pc/drivemap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(drivemap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    drivemap_mod-commands_i386_pc_drivemap.o")
-include drivemap_mod-commands_i386_pc_drivemap.d

drivemap_mod-commands_i386_pc_drivemap_int13h.o: commands/i386/pc/drivemap_int13h.S $(commands/i386/pc/drivemap_int13h.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(drivemap_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    drivemap_mod-commands_i386_pc_drivemap_int13h.o")
else
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(drivemap_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    drivemap_mod-commands_i386_pc_drivemap_int13h.o")
endif
-include drivemap_mod-commands_i386_pc_drivemap_int13h.d

drivemap_mod_ASFLAGS = $(COMMON_ASFLAGS)
drivemap_mod_CFLAGS = $(COMMON_CFLAGS)
drivemap_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For efiemu.mod.
efiemu_mod_SOURCES = efiemu/main.c efiemu/i386/loadcore32.c \
		     efiemu/i386/loadcore64.c efiemu/i386/pc/cfgtables.c \
		     efiemu/mm.c efiemu/loadcore_common.c efiemu/symbols.c \
		     efiemu/loadcore32.c efiemu/loadcore64.c \
		     efiemu/prepare32.c efiemu/prepare64.c efiemu/pnvram.c \
		     efiemu/i386/coredetect.c

clean-module-efiemu.mod.1:
	rm -f efiemu.mod efiemu_mod-efiemu_main.o efiemu_mod-efiemu_i386_loadcore32.o efiemu_mod-efiemu_i386_loadcore64.o efiemu_mod-efiemu_i386_pc_cfgtables.o efiemu_mod-efiemu_mm.o efiemu_mod-efiemu_loadcore_common.o efiemu_mod-efiemu_symbols.o efiemu_mod-efiemu_loadcore32.o efiemu_mod-efiemu_loadcore64.o efiemu_mod-efiemu_prepare32.o efiemu_mod-efiemu_prepare64.o efiemu_mod-efiemu_pnvram.o efiemu_mod-efiemu_i386_coredetect.o

CLEAN_MODULE_TARGETS += clean-module-efiemu.mod.1

mostlyclean-module-efiemu.mod.1:
	rm -f efiemu_mod-efiemu_main.d efiemu_mod-efiemu_i386_loadcore32.d efiemu_mod-efiemu_i386_loadcore64.d efiemu_mod-efiemu_i386_pc_cfgtables.d efiemu_mod-efiemu_mm.d efiemu_mod-efiemu_loadcore_common.d efiemu_mod-efiemu_symbols.d efiemu_mod-efiemu_loadcore32.d efiemu_mod-efiemu_loadcore64.d efiemu_mod-efiemu_prepare32.d efiemu_mod-efiemu_prepare64.d efiemu_mod-efiemu_pnvram.d efiemu_mod-efiemu_i386_coredetect.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-efiemu.mod.1

efiemu.mod: $(efiemu_mod_DEPENDENCIES) efiemu_mod-efiemu_main.o efiemu_mod-efiemu_i386_loadcore32.o efiemu_mod-efiemu_i386_loadcore64.o efiemu_mod-efiemu_i386_pc_cfgtables.o efiemu_mod-efiemu_mm.o efiemu_mod-efiemu_loadcore_common.o efiemu_mod-efiemu_symbols.o efiemu_mod-efiemu_loadcore32.o efiemu_mod-efiemu_loadcore64.o efiemu_mod-efiemu_prepare32.o efiemu_mod-efiemu_prepare64.o efiemu_mod-efiemu_pnvram.o efiemu_mod-efiemu_i386_coredetect.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   efiemu.mod")

MODFILES += efiemu.mod

efiemu_mod-efiemu_main.o: efiemu/main.c $(efiemu/main.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu -I$(srcdir)/efiemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_main.o")
-include efiemu_mod-efiemu_main.d

efiemu_mod-efiemu_i386_loadcore32.o: efiemu/i386/loadcore32.c $(efiemu/i386/loadcore32.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu/i386 -I$(srcdir)/efiemu/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_i386_loadcore32.o")
-include efiemu_mod-efiemu_i386_loadcore32.d

efiemu_mod-efiemu_i386_loadcore64.o: efiemu/i386/loadcore64.c $(efiemu/i386/loadcore64.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu/i386 -I$(srcdir)/efiemu/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_i386_loadcore64.o")
-include efiemu_mod-efiemu_i386_loadcore64.d

efiemu_mod-efiemu_i386_pc_cfgtables.o: efiemu/i386/pc/cfgtables.c $(efiemu/i386/pc/cfgtables.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu/i386/pc -I$(srcdir)/efiemu/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_i386_pc_cfgtables.o")
-include efiemu_mod-efiemu_i386_pc_cfgtables.d

efiemu_mod-efiemu_mm.o: efiemu/mm.c $(efiemu/mm.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu -I$(srcdir)/efiemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_mm.o")
-include efiemu_mod-efiemu_mm.d

efiemu_mod-efiemu_loadcore_common.o: efiemu/loadcore_common.c $(efiemu/loadcore_common.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu -I$(srcdir)/efiemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_loadcore_common.o")
-include efiemu_mod-efiemu_loadcore_common.d

efiemu_mod-efiemu_symbols.o: efiemu/symbols.c $(efiemu/symbols.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu -I$(srcdir)/efiemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_symbols.o")
-include efiemu_mod-efiemu_symbols.d

efiemu_mod-efiemu_loadcore32.o: efiemu/loadcore32.c $(efiemu/loadcore32.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu -I$(srcdir)/efiemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_loadcore32.o")
-include efiemu_mod-efiemu_loadcore32.d

efiemu_mod-efiemu_loadcore64.o: efiemu/loadcore64.c $(efiemu/loadcore64.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu -I$(srcdir)/efiemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_loadcore64.o")
-include efiemu_mod-efiemu_loadcore64.d

efiemu_mod-efiemu_prepare32.o: efiemu/prepare32.c $(efiemu/prepare32.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu -I$(srcdir)/efiemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_prepare32.o")
-include efiemu_mod-efiemu_prepare32.d

efiemu_mod-efiemu_prepare64.o: efiemu/prepare64.c $(efiemu/prepare64.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu -I$(srcdir)/efiemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_prepare64.o")
-include efiemu_mod-efiemu_prepare64.d

efiemu_mod-efiemu_pnvram.o: efiemu/pnvram.c $(efiemu/pnvram.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu -I$(srcdir)/efiemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_pnvram.o")
-include efiemu_mod-efiemu_pnvram.d

efiemu_mod-efiemu_i386_coredetect.o: efiemu/i386/coredetect.c $(efiemu/i386/coredetect.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iefiemu/i386 -I$(srcdir)/efiemu/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efiemu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efiemu_mod-efiemu_i386_coredetect.o")
-include efiemu_mod-efiemu_i386_coredetect.d

efiemu_mod_CFLAGS = $(COMMON_CFLAGS)
efiemu_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For acpi.mod.
acpi_mod_SOURCES = commands/acpi.c commands/i386/pc/acpi.c

clean-module-acpi.mod.1:
	rm -f acpi.mod acpi_mod-commands_acpi.o acpi_mod-commands_i386_pc_acpi.o

CLEAN_MODULE_TARGETS += clean-module-acpi.mod.1

mostlyclean-module-acpi.mod.1:
	rm -f acpi_mod-commands_acpi.d acpi_mod-commands_i386_pc_acpi.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-acpi.mod.1

acpi.mod: $(acpi_mod_DEPENDENCIES) acpi_mod-commands_acpi.o acpi_mod-commands_i386_pc_acpi.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   acpi.mod")

MODFILES += acpi.mod

acpi_mod-commands_acpi.o: commands/acpi.c $(commands/acpi.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(acpi_mod_CFLAGS) -MD -c -o $@ $<,"  CC    acpi_mod-commands_acpi.o")
-include acpi_mod-commands_acpi.d

acpi_mod-commands_i386_pc_acpi.o: commands/i386/pc/acpi.c $(commands/i386/pc/acpi.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(acpi_mod_CFLAGS) -MD -c -o $@ $<,"  CC    acpi_mod-commands_i386_pc_acpi.o")
-include acpi_mod-commands_i386_pc_acpi.d

acpi_mod_CFLAGS = $(COMMON_CFLAGS)
acpi_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For mmap.mod.
mmap_mod_SOURCES = mmap/mmap.c mmap/i386/uppermem.c mmap/i386/mmap.c \
		   mmap/i386/pc/mmap.c mmap/i386/pc/mmap_helper.S

clean-module-mmap.mod.1:
	rm -f mmap.mod mmap_mod-mmap_mmap.o mmap_mod-mmap_i386_uppermem.o mmap_mod-mmap_i386_mmap.o mmap_mod-mmap_i386_pc_mmap.o mmap_mod-mmap_i386_pc_mmap_helper.o

CLEAN_MODULE_TARGETS += clean-module-mmap.mod.1

mostlyclean-module-mmap.mod.1:
	rm -f mmap_mod-mmap_mmap.d mmap_mod-mmap_i386_uppermem.d mmap_mod-mmap_i386_mmap.d mmap_mod-mmap_i386_pc_mmap.d mmap_mod-mmap_i386_pc_mmap_helper.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-mmap.mod.1

mmap.mod: $(mmap_mod_DEPENDENCIES) mmap_mod-mmap_mmap.o mmap_mod-mmap_i386_uppermem.o mmap_mod-mmap_i386_mmap.o mmap_mod-mmap_i386_pc_mmap.o mmap_mod-mmap_i386_pc_mmap_helper.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   mmap.mod")

MODFILES += mmap.mod

mmap_mod-mmap_mmap.o: mmap/mmap.c $(mmap/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap -I$(srcdir)/mmap $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_mmap.o")
-include mmap_mod-mmap_mmap.d

mmap_mod-mmap_i386_uppermem.o: mmap/i386/uppermem.c $(mmap/i386/uppermem.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap/i386 -I$(srcdir)/mmap/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_i386_uppermem.o")
-include mmap_mod-mmap_i386_uppermem.d

mmap_mod-mmap_i386_mmap.o: mmap/i386/mmap.c $(mmap/i386/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap/i386 -I$(srcdir)/mmap/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_i386_mmap.o")
-include mmap_mod-mmap_i386_mmap.d

mmap_mod-mmap_i386_pc_mmap.o: mmap/i386/pc/mmap.c $(mmap/i386/pc/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap/i386/pc -I$(srcdir)/mmap/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_i386_pc_mmap.o")
-include mmap_mod-mmap_i386_pc_mmap.d

mmap_mod-mmap_i386_pc_mmap_helper.o: mmap/i386/pc/mmap_helper.S $(mmap/i386/pc/mmap_helper.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Immap/i386/pc -I$(srcdir)/mmap/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(mmap_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    mmap_mod-mmap_i386_pc_mmap_helper.o")
else
	$(call quiet-command,$(TARGET_CC) -Immap/i386/pc -I$(srcdir)/mmap/i386/pc $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(mmap_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    mmap_mod-mmap_i386_pc_mmap_helper.o")
endif
-include mmap_mod-mmap_i386_pc_mmap_helper.d

mmap_mod_CFLAGS = $(COMMON_CFLAGS)
mmap_mod_LDFLAGS = $(COMMON_LDFLAGS)
mmap_mod_ASFLAGS = $(COMMON_ASFLAGS)

# For biosdisk.mod.
biosdisk_mod_SOURCES = disk/i386/pc/biosdisk.c

clean-module-biosdisk.mod.1:
	rm -f biosdisk.mod biosdisk_mod-disk_i386_pc_biosdisk.o

CLEAN_MODULE_TARGETS += clean-module-biosdisk.mod.1

mostlyclean-module-biosdisk.mod.1:
	rm -f biosdisk_mod-disk_i386_pc_biosdisk.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-biosdisk.mod.1

biosdisk.mod: $(biosdisk_mod_DEPENDENCIES) biosdisk_mod-disk_i386_pc_biosdisk.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   biosdisk.mod")

MODFILES += biosdisk.mod

biosdisk_mod-disk_i386_pc_biosdisk.o: disk/i386/pc/biosdisk.c $(disk/i386/pc/biosdisk.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Idisk/i386/pc -I$(srcdir)/disk/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(biosdisk_mod_CFLAGS) -MD -c -o $@ $<,"  CC    biosdisk_mod-disk_i386_pc_biosdisk.o")
-include biosdisk_mod-disk_i386_pc_biosdisk.d

biosdisk_mod_CFLAGS = $(COMMON_CFLAGS)
biosdisk_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For chain.mod.
chain_mod_SOURCES = loader/i386/pc/chainloader.c

clean-module-chain.mod.1:
	rm -f chain.mod chain_mod-loader_i386_pc_chainloader.o

CLEAN_MODULE_TARGETS += clean-module-chain.mod.1

mostlyclean-module-chain.mod.1:
	rm -f chain_mod-loader_i386_pc_chainloader.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-chain.mod.1

chain.mod: $(chain_mod_DEPENDENCIES) chain_mod-loader_i386_pc_chainloader.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   chain.mod")

MODFILES += chain.mod

chain_mod-loader_i386_pc_chainloader.o: loader/i386/pc/chainloader.c $(loader/i386/pc/chainloader.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386/pc -I$(srcdir)/loader/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(chain_mod_CFLAGS) -MD -c -o $@ $<,"  CC    chain_mod-loader_i386_pc_chainloader.o")
-include chain_mod-loader_i386_pc_chainloader.d

chain_mod_CFLAGS = $(COMMON_CFLAGS)
chain_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += linux16.mod
linux16_mod_SOURCES = loader/i386/pc/linux.c

clean-module-linux16.mod.1:
	rm -f linux16.mod linux16_mod-loader_i386_pc_linux.o

CLEAN_MODULE_TARGETS += clean-module-linux16.mod.1

mostlyclean-module-linux16.mod.1:
	rm -f linux16_mod-loader_i386_pc_linux.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-linux16.mod.1

linux16.mod: $(linux16_mod_DEPENDENCIES) linux16_mod-loader_i386_pc_linux.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   linux16.mod")

MODFILES += linux16.mod

linux16_mod-loader_i386_pc_linux.o: loader/i386/pc/linux.c $(loader/i386/pc/linux.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386/pc -I$(srcdir)/loader/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(linux16_mod_CFLAGS) -MD -c -o $@ $<,"  CC    linux16_mod-loader_i386_pc_linux.o")
-include linux16_mod-loader_i386_pc_linux.d

linux16_mod_CFLAGS = $(COMMON_CFLAGS)
linux16_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += linux.mod
linux_mod_SOURCES = loader/i386/linux.c

clean-module-linux.mod.1:
	rm -f linux.mod linux_mod-loader_i386_linux.o

CLEAN_MODULE_TARGETS += clean-module-linux.mod.1

mostlyclean-module-linux.mod.1:
	rm -f linux_mod-loader_i386_linux.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-linux.mod.1

linux.mod: $(linux_mod_DEPENDENCIES) linux_mod-loader_i386_linux.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   linux.mod")

MODFILES += linux.mod

linux_mod-loader_i386_linux.o: loader/i386/linux.c $(loader/i386/linux.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(linux_mod_CFLAGS) -MD -c -o $@ $<,"  CC    linux_mod-loader_i386_linux.o")
-include linux_mod-loader_i386_linux.d

linux_mod_CFLAGS = $(COMMON_CFLAGS)
linux_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += xnu.mod
xnu_mod_SOURCES = loader/xnu_resume.c loader/i386/xnu.c loader/i386/pc/xnu.c \
	 loader/macho32.c loader/macho64.c loader/macho.c loader/xnu.c

clean-module-xnu.mod.1:
	rm -f xnu.mod xnu_mod-loader_xnu_resume.o xnu_mod-loader_i386_xnu.o xnu_mod-loader_i386_pc_xnu.o xnu_mod-loader_macho32.o xnu_mod-loader_macho64.o xnu_mod-loader_macho.o xnu_mod-loader_xnu.o

CLEAN_MODULE_TARGETS += clean-module-xnu.mod.1

mostlyclean-module-xnu.mod.1:
	rm -f xnu_mod-loader_xnu_resume.d xnu_mod-loader_i386_xnu.d xnu_mod-loader_i386_pc_xnu.d xnu_mod-loader_macho32.d xnu_mod-loader_macho64.d xnu_mod-loader_macho.d xnu_mod-loader_xnu.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-xnu.mod.1

xnu.mod: $(xnu_mod_DEPENDENCIES) xnu_mod-loader_xnu_resume.o xnu_mod-loader_i386_xnu.o xnu_mod-loader_i386_pc_xnu.o xnu_mod-loader_macho32.o xnu_mod-loader_macho64.o xnu_mod-loader_macho.o xnu_mod-loader_xnu.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   xnu.mod")

MODFILES += xnu.mod

xnu_mod-loader_xnu_resume.o: loader/xnu_resume.c $(loader/xnu_resume.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_xnu_resume.o")
-include xnu_mod-loader_xnu_resume.d

xnu_mod-loader_i386_xnu.o: loader/i386/xnu.c $(loader/i386/xnu.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_i386_xnu.o")
-include xnu_mod-loader_i386_xnu.d

xnu_mod-loader_i386_pc_xnu.o: loader/i386/pc/xnu.c $(loader/i386/pc/xnu.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386/pc -I$(srcdir)/loader/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_i386_pc_xnu.o")
-include xnu_mod-loader_i386_pc_xnu.d

xnu_mod-loader_macho32.o: loader/macho32.c $(loader/macho32.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_macho32.o")
-include xnu_mod-loader_macho32.d

xnu_mod-loader_macho64.o: loader/macho64.c $(loader/macho64.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_macho64.o")
-include xnu_mod-loader_macho64.d

xnu_mod-loader_macho.o: loader/macho.c $(loader/macho.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_macho.o")
-include xnu_mod-loader_macho.d

xnu_mod-loader_xnu.o: loader/xnu.c $(loader/xnu.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_xnu.o")
-include xnu_mod-loader_xnu.d

xnu_mod_CFLAGS = $(COMMON_CFLAGS)
xnu_mod_LDFLAGS = $(COMMON_LDFLAGS)
xnu_mod_ASFLAGS = $(COMMON_ASFLAGS)

# For reboot.mod.
reboot_mod_SOURCES = commands/reboot.c

clean-module-reboot.mod.1:
	rm -f reboot.mod reboot_mod-commands_reboot.o

CLEAN_MODULE_TARGETS += clean-module-reboot.mod.1

mostlyclean-module-reboot.mod.1:
	rm -f reboot_mod-commands_reboot.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-reboot.mod.1

reboot.mod: $(reboot_mod_DEPENDENCIES) reboot_mod-commands_reboot.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   reboot.mod")

MODFILES += reboot.mod

reboot_mod-commands_reboot.o: commands/reboot.c $(commands/reboot.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(reboot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    reboot_mod-commands_reboot.o")
-include reboot_mod-commands_reboot.d

reboot_mod_CFLAGS = $(COMMON_CFLAGS)
reboot_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For halt.mod.
halt_mod_SOURCES = commands/i386/pc/halt.c

clean-module-halt.mod.1:
	rm -f halt.mod halt_mod-commands_i386_pc_halt.o

CLEAN_MODULE_TARGETS += clean-module-halt.mod.1

mostlyclean-module-halt.mod.1:
	rm -f halt_mod-commands_i386_pc_halt.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-halt.mod.1

halt.mod: $(halt_mod_DEPENDENCIES) halt_mod-commands_i386_pc_halt.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   halt.mod")

MODFILES += halt.mod

halt_mod-commands_i386_pc_halt.o: commands/i386/pc/halt.c $(commands/i386/pc/halt.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(halt_mod_CFLAGS) -MD -c -o $@ $<,"  CC    halt_mod-commands_i386_pc_halt.o")
-include halt_mod-commands_i386_pc_halt.d

halt_mod_CFLAGS = $(COMMON_CFLAGS)
halt_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For serial.mod.
serial_mod_SOURCES = term/serial.c

clean-module-serial.mod.1:
	rm -f serial.mod serial_mod-term_serial.o

CLEAN_MODULE_TARGETS += clean-module-serial.mod.1

mostlyclean-module-serial.mod.1:
	rm -f serial_mod-term_serial.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-serial.mod.1

serial.mod: $(serial_mod_DEPENDENCIES) serial_mod-term_serial.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   serial.mod")

MODFILES += serial.mod

serial_mod-term_serial.o: term/serial.c $(term/serial.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(serial_mod_CFLAGS) -MD -c -o $@ $<,"  CC    serial_mod-term_serial.o")
-include serial_mod-term_serial.d

serial_mod_CFLAGS = $(COMMON_CFLAGS)
serial_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For vbe.mod.
vbe_mod_SOURCES = video/i386/pc/vbe.c

clean-module-vbe.mod.1:
	rm -f vbe.mod vbe_mod-video_i386_pc_vbe.o

CLEAN_MODULE_TARGETS += clean-module-vbe.mod.1

mostlyclean-module-vbe.mod.1:
	rm -f vbe_mod-video_i386_pc_vbe.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-vbe.mod.1

vbe.mod: $(vbe_mod_DEPENDENCIES) vbe_mod-video_i386_pc_vbe.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   vbe.mod")

MODFILES += vbe.mod

vbe_mod-video_i386_pc_vbe.o: video/i386/pc/vbe.c $(video/i386/pc/vbe.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ivideo/i386/pc -I$(srcdir)/video/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(vbe_mod_CFLAGS) -MD -c -o $@ $<,"  CC    vbe_mod-video_i386_pc_vbe.o")
-include vbe_mod-video_i386_pc_vbe.d

vbe_mod_CFLAGS = $(COMMON_CFLAGS)
vbe_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For vbeinfo.mod.
vbeinfo_mod_SOURCES = commands/i386/pc/vbeinfo.c

clean-module-vbeinfo.mod.1:
	rm -f vbeinfo.mod vbeinfo_mod-commands_i386_pc_vbeinfo.o

CLEAN_MODULE_TARGETS += clean-module-vbeinfo.mod.1

mostlyclean-module-vbeinfo.mod.1:
	rm -f vbeinfo_mod-commands_i386_pc_vbeinfo.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-vbeinfo.mod.1

vbeinfo.mod: $(vbeinfo_mod_DEPENDENCIES) vbeinfo_mod-commands_i386_pc_vbeinfo.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   vbeinfo.mod")

MODFILES += vbeinfo.mod

vbeinfo_mod-commands_i386_pc_vbeinfo.o: commands/i386/pc/vbeinfo.c $(commands/i386/pc/vbeinfo.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(vbeinfo_mod_CFLAGS) -MD -c -o $@ $<,"  CC    vbeinfo_mod-commands_i386_pc_vbeinfo.o")
-include vbeinfo_mod-commands_i386_pc_vbeinfo.d

vbeinfo_mod_CFLAGS = $(COMMON_CFLAGS)
vbeinfo_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For vbetest.mod.
vbetest_mod_SOURCES = commands/i386/pc/vbetest.c

clean-module-vbetest.mod.1:
	rm -f vbetest.mod vbetest_mod-commands_i386_pc_vbetest.o

CLEAN_MODULE_TARGETS += clean-module-vbetest.mod.1

mostlyclean-module-vbetest.mod.1:
	rm -f vbetest_mod-commands_i386_pc_vbetest.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-vbetest.mod.1

vbetest.mod: $(vbetest_mod_DEPENDENCIES) vbetest_mod-commands_i386_pc_vbetest.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   vbetest.mod")

MODFILES += vbetest.mod

vbetest_mod-commands_i386_pc_vbetest.o: commands/i386/pc/vbetest.c $(commands/i386/pc/vbetest.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(vbetest_mod_CFLAGS) -MD -c -o $@ $<,"  CC    vbetest_mod-commands_i386_pc_vbetest.o")
-include vbetest_mod-commands_i386_pc_vbetest.d

vbetest_mod_CFLAGS = $(COMMON_CFLAGS)
vbetest_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For play.mod.
play_mod_SOURCES = commands/i386/pc/play.c

clean-module-play.mod.1:
	rm -f play.mod play_mod-commands_i386_pc_play.o

CLEAN_MODULE_TARGETS += clean-module-play.mod.1

mostlyclean-module-play.mod.1:
	rm -f play_mod-commands_i386_pc_play.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-play.mod.1

play.mod: $(play_mod_DEPENDENCIES) play_mod-commands_i386_pc_play.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   play.mod")

MODFILES += play.mod

play_mod-commands_i386_pc_play.o: commands/i386/pc/play.c $(commands/i386/pc/play.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(play_mod_CFLAGS) -MD -c -o $@ $<,"  CC    play_mod-commands_i386_pc_play.o")
-include play_mod-commands_i386_pc_play.d

play_mod_CFLAGS = $(COMMON_CFLAGS)
play_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For vga.mod.
vga_mod_SOURCES = term/i386/pc/vga.c

clean-module-vga.mod.1:
	rm -f vga.mod vga_mod-term_i386_pc_vga.o

CLEAN_MODULE_TARGETS += clean-module-vga.mod.1

mostlyclean-module-vga.mod.1:
	rm -f vga_mod-term_i386_pc_vga.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-vga.mod.1

vga.mod: $(vga_mod_DEPENDENCIES) vga_mod-term_i386_pc_vga.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   vga.mod")

MODFILES += vga.mod

vga_mod-term_i386_pc_vga.o: term/i386/pc/vga.c $(term/i386/pc/vga.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(vga_mod_CFLAGS) -MD -c -o $@ $<,"  CC    vga_mod-term_i386_pc_vga.o")
-include vga_mod-term_i386_pc_vga.d

vga_mod_CFLAGS = $(COMMON_CFLAGS)
vga_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For memdisk.mod.
memdisk_mod_SOURCES = disk/memdisk.c

clean-module-memdisk.mod.1:
	rm -f memdisk.mod memdisk_mod-disk_memdisk.o

CLEAN_MODULE_TARGETS += clean-module-memdisk.mod.1

mostlyclean-module-memdisk.mod.1:
	rm -f memdisk_mod-disk_memdisk.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-memdisk.mod.1

memdisk.mod: $(memdisk_mod_DEPENDENCIES) memdisk_mod-disk_memdisk.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   memdisk.mod")

MODFILES += memdisk.mod

memdisk_mod-disk_memdisk.o: disk/memdisk.c $(disk/memdisk.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(memdisk_mod_CFLAGS) -MD -c -o $@ $<,"  CC    memdisk_mod-disk_memdisk.o")
-include memdisk_mod-disk_memdisk.d

memdisk_mod_CFLAGS = $(COMMON_CFLAGS)
memdisk_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For pci.mod
pci_mod_SOURCES = bus/pci.c

clean-module-pci.mod.1:
	rm -f pci.mod pci_mod-bus_pci.o

CLEAN_MODULE_TARGETS += clean-module-pci.mod.1

mostlyclean-module-pci.mod.1:
	rm -f pci_mod-bus_pci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-pci.mod.1

pci.mod: $(pci_mod_DEPENDENCIES) pci_mod-bus_pci.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   pci.mod")

MODFILES += pci.mod

pci_mod-bus_pci.o: bus/pci.c $(bus/pci.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ibus -I$(srcdir)/bus $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(pci_mod_CFLAGS) -MD -c -o $@ $<,"  CC    pci_mod-bus_pci.o")
-include pci_mod-bus_pci.d

pci_mod_CFLAGS = $(COMMON_CFLAGS)
pci_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For lspci.mod
lspci_mod_SOURCES = commands/lspci.c

clean-module-lspci.mod.1:
	rm -f lspci.mod lspci_mod-commands_lspci.o

CLEAN_MODULE_TARGETS += clean-module-lspci.mod.1

mostlyclean-module-lspci.mod.1:
	rm -f lspci_mod-commands_lspci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-lspci.mod.1

lspci.mod: $(lspci_mod_DEPENDENCIES) lspci_mod-commands_lspci.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   lspci.mod")

MODFILES += lspci.mod

lspci_mod-commands_lspci.o: commands/lspci.c $(commands/lspci.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(lspci_mod_CFLAGS) -MD -c -o $@ $<,"  CC    lspci_mod-commands_lspci.o")
-include lspci_mod-commands_lspci.d

lspci_mod_CFLAGS = $(COMMON_CFLAGS)
lspci_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For aout.mod
aout_mod_SOURCES = loader/aout.c

clean-module-aout.mod.1:
	rm -f aout.mod aout_mod-loader_aout.o

CLEAN_MODULE_TARGETS += clean-module-aout.mod.1

mostlyclean-module-aout.mod.1:
	rm -f aout_mod-loader_aout.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-aout.mod.1

aout.mod: $(aout_mod_DEPENDENCIES) aout_mod-loader_aout.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   aout.mod")

MODFILES += aout.mod

aout_mod-loader_aout.o: loader/aout.c $(loader/aout.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(aout_mod_CFLAGS) -MD -c -o $@ $<,"  CC    aout_mod-loader_aout.o")
-include aout_mod-loader_aout.d

aout_mod_CFLAGS = $(COMMON_CFLAGS)
aout_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For bsd.mod
bsd_mod_SOURCES = loader/i386/bsd.c loader/i386/bsd32.c loader/i386/bsd64.c loader/i386/bsd_helper.S loader/i386/bsd_trampoline.S

clean-module-bsd.mod.1:
	rm -f bsd.mod bsd_mod-loader_i386_bsd.o bsd_mod-loader_i386_bsd32.o bsd_mod-loader_i386_bsd64.o bsd_mod-loader_i386_bsd_helper.o bsd_mod-loader_i386_bsd_trampoline.o

CLEAN_MODULE_TARGETS += clean-module-bsd.mod.1

mostlyclean-module-bsd.mod.1:
	rm -f bsd_mod-loader_i386_bsd.d bsd_mod-loader_i386_bsd32.d bsd_mod-loader_i386_bsd64.d bsd_mod-loader_i386_bsd_helper.d bsd_mod-loader_i386_bsd_trampoline.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-bsd.mod.1

bsd.mod: $(bsd_mod_DEPENDENCIES) bsd_mod-loader_i386_bsd.o bsd_mod-loader_i386_bsd32.o bsd_mod-loader_i386_bsd64.o bsd_mod-loader_i386_bsd_helper.o bsd_mod-loader_i386_bsd_trampoline.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   bsd.mod")

MODFILES += bsd.mod

bsd_mod-loader_i386_bsd.o: loader/i386/bsd.c $(loader/i386/bsd.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(bsd_mod_CFLAGS) -MD -c -o $@ $<,"  CC    bsd_mod-loader_i386_bsd.o")
-include bsd_mod-loader_i386_bsd.d

bsd_mod-loader_i386_bsd32.o: loader/i386/bsd32.c $(loader/i386/bsd32.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(bsd_mod_CFLAGS) -MD -c -o $@ $<,"  CC    bsd_mod-loader_i386_bsd32.o")
-include bsd_mod-loader_i386_bsd32.d

bsd_mod-loader_i386_bsd64.o: loader/i386/bsd64.c $(loader/i386/bsd64.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(bsd_mod_CFLAGS) -MD -c -o $@ $<,"  CC    bsd_mod-loader_i386_bsd64.o")
-include bsd_mod-loader_i386_bsd64.d

bsd_mod-loader_i386_bsd_helper.o: loader/i386/bsd_helper.S $(loader/i386/bsd_helper.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(bsd_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    bsd_mod-loader_i386_bsd_helper.o")
else
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(bsd_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    bsd_mod-loader_i386_bsd_helper.o")
endif
-include bsd_mod-loader_i386_bsd_helper.d

bsd_mod-loader_i386_bsd_trampoline.o: loader/i386/bsd_trampoline.S $(loader/i386/bsd_trampoline.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(bsd_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    bsd_mod-loader_i386_bsd_trampoline.o")
else
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(bsd_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    bsd_mod-loader_i386_bsd_trampoline.o")
endif
-include bsd_mod-loader_i386_bsd_trampoline.d

bsd_mod_CFLAGS = $(COMMON_CFLAGS)
bsd_mod_LDFLAGS = $(COMMON_LDFLAGS)
bsd_mod_ASFLAGS = $(COMMON_ASFLAGS)

# For usb.mod
usb_mod_SOURCES = bus/usb/usb.c bus/usb/usbtrans.c bus/usb/usbhub.c

clean-module-usb.mod.1:
	rm -f usb.mod usb_mod-bus_usb_usb.o usb_mod-bus_usb_usbtrans.o usb_mod-bus_usb_usbhub.o

CLEAN_MODULE_TARGETS += clean-module-usb.mod.1

mostlyclean-module-usb.mod.1:
	rm -f usb_mod-bus_usb_usb.d usb_mod-bus_usb_usbtrans.d usb_mod-bus_usb_usbhub.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-usb.mod.1

usb.mod: $(usb_mod_DEPENDENCIES) usb_mod-bus_usb_usb.o usb_mod-bus_usb_usbtrans.o usb_mod-bus_usb_usbhub.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   usb.mod")

MODFILES += usb.mod

usb_mod-bus_usb_usb.o: bus/usb/usb.c $(bus/usb/usb.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ibus/usb -I$(srcdir)/bus/usb $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(usb_mod_CFLAGS) -MD -c -o $@ $<,"  CC    usb_mod-bus_usb_usb.o")
-include usb_mod-bus_usb_usb.d

usb_mod-bus_usb_usbtrans.o: bus/usb/usbtrans.c $(bus/usb/usbtrans.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ibus/usb -I$(srcdir)/bus/usb $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(usb_mod_CFLAGS) -MD -c -o $@ $<,"  CC    usb_mod-bus_usb_usbtrans.o")
-include usb_mod-bus_usb_usbtrans.d

usb_mod-bus_usb_usbhub.o: bus/usb/usbhub.c $(bus/usb/usbhub.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ibus/usb -I$(srcdir)/bus/usb $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(usb_mod_CFLAGS) -MD -c -o $@ $<,"  CC    usb_mod-bus_usb_usbhub.o")
-include usb_mod-bus_usb_usbhub.d

usb_mod_CFLAGS = $(COMMON_CFLAGS)
usb_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For usbtest.mod
usbtest_mod_SOURCES = commands/usbtest.c

clean-module-usbtest.mod.1:
	rm -f usbtest.mod usbtest_mod-commands_usbtest.o

CLEAN_MODULE_TARGETS += clean-module-usbtest.mod.1

mostlyclean-module-usbtest.mod.1:
	rm -f usbtest_mod-commands_usbtest.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-usbtest.mod.1

usbtest.mod: $(usbtest_mod_DEPENDENCIES) usbtest_mod-commands_usbtest.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   usbtest.mod")

MODFILES += usbtest.mod

usbtest_mod-commands_usbtest.o: commands/usbtest.c $(commands/usbtest.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(usbtest_mod_CFLAGS) -MD -c -o $@ $<,"  CC    usbtest_mod-commands_usbtest.o")
-include usbtest_mod-commands_usbtest.d

usbtest_mod_CFLAGS = $(COMMON_CFLAGS)
usbtest_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For uhci.mod
uhci_mod_SOURCES = bus/usb/uhci.c

clean-module-uhci.mod.1:
	rm -f uhci.mod uhci_mod-bus_usb_uhci.o

CLEAN_MODULE_TARGETS += clean-module-uhci.mod.1

mostlyclean-module-uhci.mod.1:
	rm -f uhci_mod-bus_usb_uhci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-uhci.mod.1

uhci.mod: $(uhci_mod_DEPENDENCIES) uhci_mod-bus_usb_uhci.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   uhci.mod")

MODFILES += uhci.mod

uhci_mod-bus_usb_uhci.o: bus/usb/uhci.c $(bus/usb/uhci.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ibus/usb -I$(srcdir)/bus/usb $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(uhci_mod_CFLAGS) -MD -c -o $@ $<,"  CC    uhci_mod-bus_usb_uhci.o")
-include uhci_mod-bus_usb_uhci.d

uhci_mod_CFLAGS = $(COMMON_CFLAGS)
uhci_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For ohci.mod
ohci_mod_SOURCES = bus/usb/ohci.c

clean-module-ohci.mod.1:
	rm -f ohci.mod ohci_mod-bus_usb_ohci.o

CLEAN_MODULE_TARGETS += clean-module-ohci.mod.1

mostlyclean-module-ohci.mod.1:
	rm -f ohci_mod-bus_usb_ohci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-ohci.mod.1

ohci.mod: $(ohci_mod_DEPENDENCIES) ohci_mod-bus_usb_ohci.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   ohci.mod")

MODFILES += ohci.mod

ohci_mod-bus_usb_ohci.o: bus/usb/ohci.c $(bus/usb/ohci.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ibus/usb -I$(srcdir)/bus/usb $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(ohci_mod_CFLAGS) -MD -c -o $@ $<,"  CC    ohci_mod-bus_usb_ohci.o")
-include ohci_mod-bus_usb_ohci.d

ohci_mod_CFLAGS = $(COMMON_CFLAGS)
ohci_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For usbms.mod
usbms_mod_SOURCES = disk/usbms.c

clean-module-usbms.mod.1:
	rm -f usbms.mod usbms_mod-disk_usbms.o

CLEAN_MODULE_TARGETS += clean-module-usbms.mod.1

mostlyclean-module-usbms.mod.1:
	rm -f usbms_mod-disk_usbms.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-usbms.mod.1

usbms.mod: $(usbms_mod_DEPENDENCIES) usbms_mod-disk_usbms.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   usbms.mod")

MODFILES += usbms.mod

usbms_mod-disk_usbms.o: disk/usbms.c $(disk/usbms.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(usbms_mod_CFLAGS) -MD -c -o $@ $<,"  CC    usbms_mod-disk_usbms.o")
-include usbms_mod-disk_usbms.d

usbms_mod_CFLAGS = $(COMMON_CFLAGS)
usbms_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For usb_keyboard.mod
usb_keyboard_mod_SOURCES = term/usb_keyboard.c

clean-module-usb_keyboard.mod.1:
	rm -f usb_keyboard.mod usb_keyboard_mod-term_usb_keyboard.o

CLEAN_MODULE_TARGETS += clean-module-usb_keyboard.mod.1

mostlyclean-module-usb_keyboard.mod.1:
	rm -f usb_keyboard_mod-term_usb_keyboard.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-usb_keyboard.mod.1

usb_keyboard.mod: $(usb_keyboard_mod_DEPENDENCIES) usb_keyboard_mod-term_usb_keyboard.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   usb_keyboard.mod")

MODFILES += usb_keyboard.mod

usb_keyboard_mod-term_usb_keyboard.o: term/usb_keyboard.c $(term/usb_keyboard.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(usb_keyboard_mod_CFLAGS) -MD -c -o $@ $<,"  CC    usb_keyboard_mod-term_usb_keyboard.o")
-include usb_keyboard_mod-term_usb_keyboard.d

usb_keyboard_mod_CFLAGS = $(COMMON_CFLAGS)
usb_keyboard_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For pxe.mod
pxe_mod_SOURCES = fs/i386/pc/pxe.c

clean-module-pxe.mod.1:
	rm -f pxe.mod pxe_mod-fs_i386_pc_pxe.o

CLEAN_MODULE_TARGETS += clean-module-pxe.mod.1

mostlyclean-module-pxe.mod.1:
	rm -f pxe_mod-fs_i386_pc_pxe.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-pxe.mod.1

pxe.mod: $(pxe_mod_DEPENDENCIES) pxe_mod-fs_i386_pc_pxe.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   pxe.mod")

MODFILES += pxe.mod

pxe_mod-fs_i386_pc_pxe.o: fs/i386/pc/pxe.c $(fs/i386/pc/pxe.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ifs/i386/pc -I$(srcdir)/fs/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(pxe_mod_CFLAGS) -MD -c -o $@ $<,"  CC    pxe_mod-fs_i386_pc_pxe.o")
-include pxe_mod-fs_i386_pc_pxe.d

pxe_mod_CFLAGS = $(COMMON_CFLAGS)
pxe_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For pxecmd.mod
pxecmd_mod_SOURCES = commands/i386/pc/pxecmd.c

clean-module-pxecmd.mod.1:
	rm -f pxecmd.mod pxecmd_mod-commands_i386_pc_pxecmd.o

CLEAN_MODULE_TARGETS += clean-module-pxecmd.mod.1

mostlyclean-module-pxecmd.mod.1:
	rm -f pxecmd_mod-commands_i386_pc_pxecmd.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-pxecmd.mod.1

pxecmd.mod: $(pxecmd_mod_DEPENDENCIES) pxecmd_mod-commands_i386_pc_pxecmd.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   pxecmd.mod")

MODFILES += pxecmd.mod

pxecmd_mod-commands_i386_pc_pxecmd.o: commands/i386/pc/pxecmd.c $(commands/i386/pc/pxecmd.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(pxecmd_mod_CFLAGS) -MD -c -o $@ $<,"  CC    pxecmd_mod-commands_i386_pc_pxecmd.o")
-include pxecmd_mod-commands_i386_pc_pxecmd.d

pxecmd_mod_CFLAGS = $(COMMON_CFLAGS)
pxecmd_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For pxecfg.mod
pxecfg_mod_SOURCES = commands/i386/pc/pxecfg.c
pxecfg_mod_CFLAGS = $(COMMON_CFLAGS)
pxecfg_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For datetime.mod
datetime_mod_SOURCES = lib/cmos_datetime.c

clean-module-datetime.mod.1:
	rm -f datetime.mod datetime_mod-lib_cmos_datetime.o

CLEAN_MODULE_TARGETS += clean-module-datetime.mod.1

mostlyclean-module-datetime.mod.1:
	rm -f datetime_mod-lib_cmos_datetime.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-datetime.mod.1

datetime.mod: $(datetime_mod_DEPENDENCIES) datetime_mod-lib_cmos_datetime.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   datetime.mod")

MODFILES += datetime.mod

datetime_mod-lib_cmos_datetime.o: lib/cmos_datetime.c $(lib/cmos_datetime.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib -I$(srcdir)/lib $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(datetime_mod_CFLAGS) -MD -c -o $@ $<,"  CC    datetime_mod-lib_cmos_datetime.o")
-include datetime_mod-lib_cmos_datetime.d

datetime_mod_CFLAGS = $(COMMON_CFLAGS)
datetime_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For date.mod
date_mod_SOURCES = commands/date.c

clean-module-date.mod.1:
	rm -f date.mod date_mod-commands_date.o

CLEAN_MODULE_TARGETS += clean-module-date.mod.1

mostlyclean-module-date.mod.1:
	rm -f date_mod-commands_date.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-date.mod.1

date.mod: $(date_mod_DEPENDENCIES) date_mod-commands_date.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   date.mod")

MODFILES += date.mod

date_mod-commands_date.o: commands/date.c $(commands/date.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(date_mod_CFLAGS) -MD -c -o $@ $<,"  CC    date_mod-commands_date.o")
-include date_mod-commands_date.d

date_mod_CFLAGS = $(COMMON_CFLAGS)
date_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For datehook.mod
datehook_mod_SOURCES = hook/datehook.c

clean-module-datehook.mod.1:
	rm -f datehook.mod datehook_mod-hook_datehook.o

CLEAN_MODULE_TARGETS += clean-module-datehook.mod.1

mostlyclean-module-datehook.mod.1:
	rm -f datehook_mod-hook_datehook.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-datehook.mod.1

datehook.mod: $(datehook_mod_DEPENDENCIES) datehook_mod-hook_datehook.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   datehook.mod")

MODFILES += datehook.mod

datehook_mod-hook_datehook.o: hook/datehook.c $(hook/datehook.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ihook -I$(srcdir)/hook $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(datehook_mod_CFLAGS) -MD -c -o $@ $<,"  CC    datehook_mod-hook_datehook.o")
-include datehook_mod-hook_datehook.d

datehook_mod_CFLAGS = $(COMMON_CFLAGS)
datehook_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For lsmmap.mod
lsmmap_mod_SOURCES = commands/lsmmap.c

clean-module-lsmmap.mod.1:
	rm -f lsmmap.mod lsmmap_mod-commands_lsmmap.o

CLEAN_MODULE_TARGETS += clean-module-lsmmap.mod.1

mostlyclean-module-lsmmap.mod.1:
	rm -f lsmmap_mod-commands_lsmmap.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-lsmmap.mod.1

lsmmap.mod: $(lsmmap_mod_DEPENDENCIES) lsmmap_mod-commands_lsmmap.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   lsmmap.mod")

MODFILES += lsmmap.mod

lsmmap_mod-commands_lsmmap.o: commands/lsmmap.c $(commands/lsmmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(lsmmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    lsmmap_mod-commands_lsmmap.o")
-include lsmmap_mod-commands_lsmmap.d

lsmmap_mod_CFLAGS = $(COMMON_CFLAGS)
lsmmap_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For ata_pthru.mod.
ata_pthru_mod_SOURCES = disk/ata_pthru.c

clean-module-ata_pthru.mod.1:
	rm -f ata_pthru.mod ata_pthru_mod-disk_ata_pthru.o

CLEAN_MODULE_TARGETS += clean-module-ata_pthru.mod.1

mostlyclean-module-ata_pthru.mod.1:
	rm -f ata_pthru_mod-disk_ata_pthru.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-ata_pthru.mod.1

ata_pthru.mod: $(ata_pthru_mod_DEPENDENCIES) ata_pthru_mod-disk_ata_pthru.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   ata_pthru.mod")

MODFILES += ata_pthru.mod

ata_pthru_mod-disk_ata_pthru.o: disk/ata_pthru.c $(disk/ata_pthru.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(ata_pthru_mod_CFLAGS) -MD -c -o $@ $<,"  CC    ata_pthru_mod-disk_ata_pthru.o")
-include ata_pthru_mod-disk_ata_pthru.d

ata_pthru_mod_CFLAGS = $(COMMON_CFLAGS)
ata_pthru_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For hdparm.mod.
hdparm_mod_SOURCES = commands/hdparm.c

clean-module-hdparm.mod.1:
	rm -f hdparm.mod hdparm_mod-commands_hdparm.o

CLEAN_MODULE_TARGETS += clean-module-hdparm.mod.1

mostlyclean-module-hdparm.mod.1:
	rm -f hdparm_mod-commands_hdparm.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-hdparm.mod.1

hdparm.mod: $(hdparm_mod_DEPENDENCIES) hdparm_mod-commands_hdparm.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   hdparm.mod")

MODFILES += hdparm.mod

hdparm_mod-commands_hdparm.o: commands/hdparm.c $(commands/hdparm.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(hdparm_mod_CFLAGS) -MD -c -o $@ $<,"  CC    hdparm_mod-commands_hdparm.o")
-include hdparm_mod-commands_hdparm.d

hdparm_mod_CFLAGS = $(COMMON_CFLAGS)
hdparm_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For loadbin.mod.
loadbin_mod_SOURCES = loader/i386/pc/loadbin.c

clean-module-loadbin.mod.1:
	rm -f loadbin.mod loadbin_mod-loader_i386_pc_loadbin.o

CLEAN_MODULE_TARGETS += clean-module-loadbin.mod.1

mostlyclean-module-loadbin.mod.1:
	rm -f loadbin_mod-loader_i386_pc_loadbin.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-loadbin.mod.1

loadbin.mod: $(loadbin_mod_DEPENDENCIES) loadbin_mod-loader_i386_pc_loadbin.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   loadbin.mod")

MODFILES += loadbin.mod

loadbin_mod-loader_i386_pc_loadbin.o: loader/i386/pc/loadbin.c $(loader/i386/pc/loadbin.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386/pc -I$(srcdir)/loader/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(loadbin_mod_CFLAGS) -MD -c -o $@ $<,"  CC    loadbin_mod-loader_i386_pc_loadbin.o")
-include loadbin_mod-loader_i386_pc_loadbin.d

loadbin_mod_CFLAGS = $(COMMON_CFLAGS)
loadbin_mod_LDFLAGS = $(COMMON_LDFLAGS)

ifeq ($(enable_efiemu), yes)

efiemu32.o: efiemu/runtime/efiemu.c $(TARGET_OBJ2ELF)
	-rm -f $@
ifeq ($(TARGET_APPLE_CC), 1)
	-rm -f $@.bin
	$(TARGET_CC) -c -m32 -DELF32 -DAPPLE_CC -o $@.bin -Wall -Werror $< -nostdlib -O2 -I$(srcdir)/efiemu/runtime -I$(srcdir)/include -Iinclude
	$(OBJCONV) -felf32 -nu -nd $@.bin $@
	-rm -f $@.bin
else
	$(TARGET_CC) -c -m32 -DELF32 -o $@ -Wall -Werror $< -nostdlib -O2 -I$(srcdir)/efiemu/runtime -I$(srcdir)/include -Iinclude
	if test ! -z $(TARGET_OBJ2ELF); then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
endif

efiemu64_c.o: efiemu/runtime/efiemu.c
ifeq ($(TARGET_APPLE_CC), 1)
	$(TARGET_CC) -c -m64 -DAPPLE_CC=1 -DELF64 -o $@ -Wall -Werror $< -nostdlib -mno-red-zone -O2 -I$(srcdir)/efiemu/runtime -I$(srcdir)/include -Iinclude
else
	$(TARGET_CC) -c -m64 -DELF64 -o $@ -Wall -Werror $< -nostdlib  -mcmodel=large -mno-red-zone -O2 -I$(srcdir)/efiemu/runtime -I$(srcdir)/include -Iinclude
endif

efiemu64_s.o: efiemu/runtime/efiemu.S
	-rm -f $@
ifeq ($(TARGET_APPLE_CC), 1)
	$(TARGET_CC) -c -m64 -DAPPLE_CC=1 -DELF64 -o $@ -Wall -Werror $< -nostdlib -mno-red-zone -O2 -I$(srcdir)/efiemu/runtime -I$(srcdir)/include -Iinclude
else
	$(TARGET_CC) -c -m64 -DELF64 -o $@ -Wall -Werror $< -nostdlib  -mcmodel=large -mno-red-zone -O2 -I$(srcdir)/efiemu/runtime -I$(srcdir)/include -Iinclude
endif

efiemu64.o: efiemu64_c.o efiemu64_s.o  $(TARGET_OBJ2ELF)
	-rm -f $@
ifeq ($(TARGET_APPLE_CC), 1)
	-rm -f $@.bin
	$(TARGET_CC) -m64 -o $@.bin -r $^ -nostdlib
	$(OBJCONV) -felf64 -nu -nd $@.bin $@
	-rm -f $@.bin
else
	$(TARGET_CC) -m64 -o $@ -r $^ -nostdlib
	if test ! -z $(TARGET_OBJ2ELF); then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
endif

CLEANFILES += efiemu32.o efiemu64.o efiemu64_c.o efiemu64_s.o
pkglib_DATA += efiemu32.o efiemu64.o

endif

include $(srcdir)/conf/i386.mk
include $(srcdir)/conf/common.mk
grub-mkisofs: $(grub_mkisofs_DEPENDENCIES) $(grub_mkisofs_OBJECTS)
	$(call quiet-command,$(CC) -o $@ $(grub_mkisofs_OBJECTS) $(LDFLAGS) $(grub_mkisofs_LDFLAGS),"  LINK  grub-mkisofs")

grub-mkimage: $(grub_mkimage_DEPENDENCIES) $(grub_mkimage_OBJECTS)
	$(call quiet-command,$(CC) -o $@ $(grub_mkimage_OBJECTS) $(LDFLAGS) $(grub_mkimage_LDFLAGS),"  LINK  grub-mkimage")

grub-setup: $(grub_setup_DEPENDENCIES) $(grub_setup_OBJECTS)
	$(call quiet-command,$(CC) -o $@ $(grub_setup_OBJECTS) $(LDFLAGS) $(grub_setup_LDFLAGS),"  LINK  grub-setup")

