# -*- makefile -*-
# Generated by genmk.rb, please don't edit!

COMMON_ASFLAGS	= -nostdinc -fno-builtin -m32
COMMON_CFLAGS = -fno-builtin -mrtd -mregparm=3 -m32
COMMON_LDFLAGS	= -m32 -nostdlib

# Used by various components.  These rules need to precede them.
script/lexer.c_DEPENDENCIES = grub_script.tab.h

# Images.

GRUB_KERNEL_MACHINE_LINK_ADDR	= 0x8200

ifeq ($(platform), coreboot)

pkglib_MODULES += kernel.mod
kernel_mod_SOURCES = kern/i386/coreboot/startup.S \
	kern/i386/misc.S \
	kern/i386/coreboot/init.c \
	kern/i386/multiboot_mmap.c \
	kern/i386/halt.c \
	kern/main.c kern/device.c \
	kern/disk.c kern/dl.c kern/file.c kern/fs.c kern/err.c \
	kern/misc.c kern/mm.c kern/term.c \
	kern/rescue_parser.c kern/rescue_reader.c \
	kern/time.c kern/list.c kern/handler.c kern/command.c kern/corecmd.c \
	kern/parser.c kern/partition.c \
	kern/i386/tsc.c kern/i386/pit.c \
	kern/generic/rtc_get_time_ms.c \
	kern/generic/millisleep.c \
	kern/env.c \
	term/i386/pc/vga_text.c term/i386/vga_common.c

clean-module-kernel.mod.1:
	rm -f kernel.mod kernel_mod-kern_i386_coreboot_startup.o kernel_mod-kern_i386_misc.o kernel_mod-kern_i386_coreboot_init.o kernel_mod-kern_i386_multiboot_mmap.o kernel_mod-kern_i386_halt.o kernel_mod-kern_main.o kernel_mod-kern_device.o kernel_mod-kern_disk.o kernel_mod-kern_dl.o kernel_mod-kern_file.o kernel_mod-kern_fs.o kernel_mod-kern_err.o kernel_mod-kern_misc.o kernel_mod-kern_mm.o kernel_mod-kern_term.o kernel_mod-kern_rescue_parser.o kernel_mod-kern_rescue_reader.o kernel_mod-kern_time.o kernel_mod-kern_list.o kernel_mod-kern_handler.o kernel_mod-kern_command.o kernel_mod-kern_corecmd.o kernel_mod-kern_parser.o kernel_mod-kern_partition.o kernel_mod-kern_i386_tsc.o kernel_mod-kern_i386_pit.o kernel_mod-kern_generic_rtc_get_time_ms.o kernel_mod-kern_generic_millisleep.o kernel_mod-kern_env.o kernel_mod-term_i386_pc_vga_text.o kernel_mod-term_i386_vga_common.o

CLEAN_MODULE_TARGETS += clean-module-kernel.mod.1

mostlyclean-module-kernel.mod.1:
	rm -f kernel_mod-kern_i386_coreboot_startup.d kernel_mod-kern_i386_misc.d kernel_mod-kern_i386_coreboot_init.d kernel_mod-kern_i386_multiboot_mmap.d kernel_mod-kern_i386_halt.d kernel_mod-kern_main.d kernel_mod-kern_device.d kernel_mod-kern_disk.d kernel_mod-kern_dl.d kernel_mod-kern_file.d kernel_mod-kern_fs.d kernel_mod-kern_err.d kernel_mod-kern_misc.d kernel_mod-kern_mm.d kernel_mod-kern_term.d kernel_mod-kern_rescue_parser.d kernel_mod-kern_rescue_reader.d kernel_mod-kern_time.d kernel_mod-kern_list.d kernel_mod-kern_handler.d kernel_mod-kern_command.d kernel_mod-kern_corecmd.d kernel_mod-kern_parser.d kernel_mod-kern_partition.d kernel_mod-kern_i386_tsc.d kernel_mod-kern_i386_pit.d kernel_mod-kern_generic_rtc_get_time_ms.d kernel_mod-kern_generic_millisleep.d kernel_mod-kern_env.d kernel_mod-term_i386_pc_vga_text.d kernel_mod-term_i386_vga_common.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-kernel.mod.1

kernel.mod: $(kernel_mod_DEPENDENCIES) kernel_mod-kern_i386_coreboot_startup.o kernel_mod-kern_i386_misc.o kernel_mod-kern_i386_coreboot_init.o kernel_mod-kern_i386_multiboot_mmap.o kernel_mod-kern_i386_halt.o kernel_mod-kern_main.o kernel_mod-kern_device.o kernel_mod-kern_disk.o kernel_mod-kern_dl.o kernel_mod-kern_file.o kernel_mod-kern_fs.o kernel_mod-kern_err.o kernel_mod-kern_misc.o kernel_mod-kern_mm.o kernel_mod-kern_term.o kernel_mod-kern_rescue_parser.o kernel_mod-kern_rescue_reader.o kernel_mod-kern_time.o kernel_mod-kern_list.o kernel_mod-kern_handler.o kernel_mod-kern_command.o kernel_mod-kern_corecmd.o kernel_mod-kern_parser.o kernel_mod-kern_partition.o kernel_mod-kern_i386_tsc.o kernel_mod-kern_i386_pit.o kernel_mod-kern_generic_rtc_get_time_ms.o kernel_mod-kern_generic_millisleep.o kernel_mod-kern_env.o kernel_mod-term_i386_pc_vga_text.o kernel_mod-term_i386_vga_common.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   kernel.mod")

MODFILES += kernel.mod

kernel_mod-kern_i386_coreboot_startup.o: kern/i386/coreboot/startup.S $(kern/i386/coreboot/startup.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/coreboot -I$(srcdir)/kern/i386/coreboot $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    kernel_mod-kern_i386_coreboot_startup.o")
else
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/coreboot -I$(srcdir)/kern/i386/coreboot $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    kernel_mod-kern_i386_coreboot_startup.o")
endif
-include kernel_mod-kern_i386_coreboot_startup.d

kernel_mod-kern_i386_misc.o: kern/i386/misc.S $(kern/i386/misc.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    kernel_mod-kern_i386_misc.o")
else
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    kernel_mod-kern_i386_misc.o")
endif
-include kernel_mod-kern_i386_misc.d

kernel_mod-kern_i386_coreboot_init.o: kern/i386/coreboot/init.c $(kern/i386/coreboot/init.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/coreboot -I$(srcdir)/kern/i386/coreboot $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_coreboot_init.o")
-include kernel_mod-kern_i386_coreboot_init.d

kernel_mod-kern_i386_multiboot_mmap.o: kern/i386/multiboot_mmap.c $(kern/i386/multiboot_mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_multiboot_mmap.o")
-include kernel_mod-kern_i386_multiboot_mmap.d

kernel_mod-kern_i386_halt.o: kern/i386/halt.c $(kern/i386/halt.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_halt.o")
-include kernel_mod-kern_i386_halt.d

kernel_mod-kern_main.o: kern/main.c $(kern/main.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_main.o")
-include kernel_mod-kern_main.d

kernel_mod-kern_device.o: kern/device.c $(kern/device.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_device.o")
-include kernel_mod-kern_device.d

kernel_mod-kern_disk.o: kern/disk.c $(kern/disk.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_disk.o")
-include kernel_mod-kern_disk.d

kernel_mod-kern_dl.o: kern/dl.c $(kern/dl.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_dl.o")
-include kernel_mod-kern_dl.d

kernel_mod-kern_file.o: kern/file.c $(kern/file.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_file.o")
-include kernel_mod-kern_file.d

kernel_mod-kern_fs.o: kern/fs.c $(kern/fs.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_fs.o")
-include kernel_mod-kern_fs.d

kernel_mod-kern_err.o: kern/err.c $(kern/err.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_err.o")
-include kernel_mod-kern_err.d

kernel_mod-kern_misc.o: kern/misc.c $(kern/misc.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_misc.o")
-include kernel_mod-kern_misc.d

kernel_mod-kern_mm.o: kern/mm.c $(kern/mm.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_mm.o")
-include kernel_mod-kern_mm.d

kernel_mod-kern_term.o: kern/term.c $(kern/term.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_term.o")
-include kernel_mod-kern_term.d

kernel_mod-kern_rescue_parser.o: kern/rescue_parser.c $(kern/rescue_parser.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_rescue_parser.o")
-include kernel_mod-kern_rescue_parser.d

kernel_mod-kern_rescue_reader.o: kern/rescue_reader.c $(kern/rescue_reader.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_rescue_reader.o")
-include kernel_mod-kern_rescue_reader.d

kernel_mod-kern_time.o: kern/time.c $(kern/time.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_time.o")
-include kernel_mod-kern_time.d

kernel_mod-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_list.o")
-include kernel_mod-kern_list.d

kernel_mod-kern_handler.o: kern/handler.c $(kern/handler.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_handler.o")
-include kernel_mod-kern_handler.d

kernel_mod-kern_command.o: kern/command.c $(kern/command.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_command.o")
-include kernel_mod-kern_command.d

kernel_mod-kern_corecmd.o: kern/corecmd.c $(kern/corecmd.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_corecmd.o")
-include kernel_mod-kern_corecmd.d

kernel_mod-kern_parser.o: kern/parser.c $(kern/parser.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_parser.o")
-include kernel_mod-kern_parser.d

kernel_mod-kern_partition.o: kern/partition.c $(kern/partition.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_partition.o")
-include kernel_mod-kern_partition.d

kernel_mod-kern_i386_tsc.o: kern/i386/tsc.c $(kern/i386/tsc.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_tsc.o")
-include kernel_mod-kern_i386_tsc.d

kernel_mod-kern_i386_pit.o: kern/i386/pit.c $(kern/i386/pit.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_pit.o")
-include kernel_mod-kern_i386_pit.d

kernel_mod-kern_generic_rtc_get_time_ms.o: kern/generic/rtc_get_time_ms.c $(kern/generic/rtc_get_time_ms.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/generic -I$(srcdir)/kern/generic $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_generic_rtc_get_time_ms.o")
-include kernel_mod-kern_generic_rtc_get_time_ms.d

kernel_mod-kern_generic_millisleep.o: kern/generic/millisleep.c $(kern/generic/millisleep.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/generic -I$(srcdir)/kern/generic $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_generic_millisleep.o")
-include kernel_mod-kern_generic_millisleep.d

kernel_mod-kern_env.o: kern/env.c $(kern/env.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_env.o")
-include kernel_mod-kern_env.d

kernel_mod-term_i386_pc_vga_text.o: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-term_i386_pc_vga_text.o")
-include kernel_mod-term_i386_pc_vga_text.d

kernel_mod-term_i386_vga_common.o: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-term_i386_vga_common.o")
-include kernel_mod-term_i386_vga_common.d

kernel_mod_CFLAGS = $(COMMON_CFLAGS)
kernel_mod_ASFLAGS = $(COMMON_ASFLAGS)

endif

ifeq ($(platform), qemu)

GRUB_BOOT_MACHINE_LINK_ADDR	= 0xffe00

pkglib_IMAGES += boot.img
boot_img_SOURCES = boot/i386/qemu/boot.S

clean-image-boot.img.1:
	rm -f boot.img boot.exec boot_img-boot_i386_qemu_boot.o

CLEAN_IMAGE_TARGETS += clean-image-boot.img.1

mostlyclean-image-boot.img.1:
	rm -f boot_img-boot_i386_qemu_boot.d

MOSTLYCLEAN_IMAGE_TARGETS += mostlyclean-image-boot.img.1

boot.img: boot_img-boot_i386_qemu_boot.o grub-mkimg
	$(call quiet-command,./grub-mkimg -o $@ -b $(boot_img_LINKADDR) $(filter %.o, $^),"  IMG   boot.img")

boot_img-boot_i386_qemu_boot.o: boot/i386/qemu/boot.S $(boot/i386/qemu/boot.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/qemu -I$(srcdir)/boot/i386/qemu $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(boot_img_ASFLAGS) -MD -c -o $@ $<,"  AS    boot_img-boot_i386_qemu_boot.o")
else
	$(call quiet-command,$(TARGET_CC) -Iboot/i386/qemu -I$(srcdir)/boot/i386/qemu $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(boot_img_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    boot_img-boot_i386_qemu_boot.o")
endif
-include boot_img-boot_i386_qemu_boot.d

boot_img_ASFLAGS = $(COMMON_ASFLAGS) -DGRUB_BOOT_MACHINE_LINK_ADDR=$(GRUB_BOOT_MACHINE_LINK_ADDR)
boot_img_LINKADDR = $(GRUB_BOOT_MACHINE_LINK_ADDR)

bin_UTILITIES += grub-mkimage
grub_mkimage_SOURCES = gnulib/progname.c util/grub-mkrawimage.c \
	util/misc.c util/resolve.c util/obj.c kern/list.c

clean-utility-grub-mkimage.1:
	rm -f grub-mkimage$(EXEEXT) grub_mkimage-gnulib_progname.o grub_mkimage-util_grub_mkrawimage.o grub_mkimage-util_misc.o grub_mkimage-util_resolve.o grub_mkimage-util_obj.o grub_mkimage-kern_list.o

CLEAN_UTILITY_TARGETS += clean-utility-grub-mkimage.1

mostlyclean-utility-grub-mkimage.1:
	rm -f grub_mkimage-gnulib_progname.d grub_mkimage-util_grub_mkrawimage.d grub_mkimage-util_misc.d grub_mkimage-util_resolve.d grub_mkimage-util_obj.d grub_mkimage-kern_list.d

MOSTLYCLEAN_UTILITY_TARGETS += mostlyclean-utility-grub-mkimage.1

grub_mkimage_OBJECTS += grub_mkimage-gnulib_progname.o grub_mkimage-util_grub_mkrawimage.o grub_mkimage-util_misc.o grub_mkimage-util_resolve.o grub_mkimage-util_obj.o grub_mkimage-kern_list.o

grub_mkimage-gnulib_progname.o: gnulib/progname.c $(gnulib/progname.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ignulib -I$(srcdir)/gnulib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-gnulib_progname.o")
-include grub_mkimage-gnulib_progname.d

grub_mkimage-util_grub_mkrawimage.o: util/grub-mkrawimage.c $(util/grub-mkrawimage.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_grub_mkrawimage.o")
-include grub_mkimage-util_grub_mkrawimage.d

grub_mkimage-util_misc.o: util/misc.c $(util/misc.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_misc.o")
-include grub_mkimage-util_misc.d

grub_mkimage-util_resolve.o: util/resolve.c $(util/resolve.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_resolve.o")
-include grub_mkimage-util_resolve.d

grub_mkimage-util_obj.o: util/obj.c $(util/obj.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_obj.o")
-include grub_mkimage-util_obj.d

grub_mkimage-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-kern_list.o")
-include grub_mkimage-kern_list.d

grub_mkimage_CFLAGS = -DGRUB_KERNEL_MACHINE_LINK_ADDR=$(GRUB_KERNEL_MACHINE_LINK_ADDR)
util/grub-mkrawimage.c_DEPENDENCIES = Makefile


pkglib_MODULES += kernel.mod
kernel_mod_SOURCES = kern/i386/qemu/startup.S \
	kern/i386/misc.S \
	kern/i386/coreboot/init.c \
	kern/i386/qemu/mmap.c \
	kern/i386/halt.c \
	kern/main.c kern/device.c \
	kern/disk.c kern/dl.c kern/file.c kern/fs.c kern/err.c \
	kern/misc.c kern/mm.c kern/term.c \
	kern/rescue_parser.c kern/rescue_reader.c \
	kern/time.c kern/list.c kern/handler.c kern/command.c kern/corecmd.c \
	kern/parser.c kern/partition.c \
	kern/i386/tsc.c kern/i386/pit.c \
	kern/generic/rtc_get_time_ms.c \
	kern/generic/millisleep.c \
	kern/env.c \
	term/i386/pc/vga_text.c term/i386/vga_common.c

clean-module-kernel.mod.2:
	rm -f kernel.mod kernel_mod-kern_i386_qemu_startup.o kernel_mod-kern_i386_misc.o kernel_mod-kern_i386_coreboot_init.o kernel_mod-kern_i386_qemu_mmap.o kernel_mod-kern_i386_halt.o kernel_mod-kern_main.o kernel_mod-kern_device.o kernel_mod-kern_disk.o kernel_mod-kern_dl.o kernel_mod-kern_file.o kernel_mod-kern_fs.o kernel_mod-kern_err.o kernel_mod-kern_misc.o kernel_mod-kern_mm.o kernel_mod-kern_term.o kernel_mod-kern_rescue_parser.o kernel_mod-kern_rescue_reader.o kernel_mod-kern_time.o kernel_mod-kern_list.o kernel_mod-kern_handler.o kernel_mod-kern_command.o kernel_mod-kern_corecmd.o kernel_mod-kern_parser.o kernel_mod-kern_partition.o kernel_mod-kern_i386_tsc.o kernel_mod-kern_i386_pit.o kernel_mod-kern_generic_rtc_get_time_ms.o kernel_mod-kern_generic_millisleep.o kernel_mod-kern_env.o kernel_mod-term_i386_pc_vga_text.o kernel_mod-term_i386_vga_common.o

CLEAN_MODULE_TARGETS += clean-module-kernel.mod.2

mostlyclean-module-kernel.mod.2:
	rm -f kernel_mod-kern_i386_qemu_startup.d kernel_mod-kern_i386_misc.d kernel_mod-kern_i386_coreboot_init.d kernel_mod-kern_i386_qemu_mmap.d kernel_mod-kern_i386_halt.d kernel_mod-kern_main.d kernel_mod-kern_device.d kernel_mod-kern_disk.d kernel_mod-kern_dl.d kernel_mod-kern_file.d kernel_mod-kern_fs.d kernel_mod-kern_err.d kernel_mod-kern_misc.d kernel_mod-kern_mm.d kernel_mod-kern_term.d kernel_mod-kern_rescue_parser.d kernel_mod-kern_rescue_reader.d kernel_mod-kern_time.d kernel_mod-kern_list.d kernel_mod-kern_handler.d kernel_mod-kern_command.d kernel_mod-kern_corecmd.d kernel_mod-kern_parser.d kernel_mod-kern_partition.d kernel_mod-kern_i386_tsc.d kernel_mod-kern_i386_pit.d kernel_mod-kern_generic_rtc_get_time_ms.d kernel_mod-kern_generic_millisleep.d kernel_mod-kern_env.d kernel_mod-term_i386_pc_vga_text.d kernel_mod-term_i386_vga_common.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-kernel.mod.2

kernel.mod: $(kernel_mod_DEPENDENCIES) kernel_mod-kern_i386_qemu_startup.o kernel_mod-kern_i386_misc.o kernel_mod-kern_i386_coreboot_init.o kernel_mod-kern_i386_qemu_mmap.o kernel_mod-kern_i386_halt.o kernel_mod-kern_main.o kernel_mod-kern_device.o kernel_mod-kern_disk.o kernel_mod-kern_dl.o kernel_mod-kern_file.o kernel_mod-kern_fs.o kernel_mod-kern_err.o kernel_mod-kern_misc.o kernel_mod-kern_mm.o kernel_mod-kern_term.o kernel_mod-kern_rescue_parser.o kernel_mod-kern_rescue_reader.o kernel_mod-kern_time.o kernel_mod-kern_list.o kernel_mod-kern_handler.o kernel_mod-kern_command.o kernel_mod-kern_corecmd.o kernel_mod-kern_parser.o kernel_mod-kern_partition.o kernel_mod-kern_i386_tsc.o kernel_mod-kern_i386_pit.o kernel_mod-kern_generic_rtc_get_time_ms.o kernel_mod-kern_generic_millisleep.o kernel_mod-kern_env.o kernel_mod-term_i386_pc_vga_text.o kernel_mod-term_i386_vga_common.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   kernel.mod")

MODFILES += kernel.mod

kernel_mod-kern_i386_qemu_startup.o: kern/i386/qemu/startup.S $(kern/i386/qemu/startup.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/qemu -I$(srcdir)/kern/i386/qemu $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    kernel_mod-kern_i386_qemu_startup.o")
else
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/qemu -I$(srcdir)/kern/i386/qemu $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    kernel_mod-kern_i386_qemu_startup.o")
endif
-include kernel_mod-kern_i386_qemu_startup.d

kernel_mod-kern_i386_misc.o: kern/i386/misc.S $(kern/i386/misc.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    kernel_mod-kern_i386_misc.o")
else
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    kernel_mod-kern_i386_misc.o")
endif
-include kernel_mod-kern_i386_misc.d

kernel_mod-kern_i386_coreboot_init.o: kern/i386/coreboot/init.c $(kern/i386/coreboot/init.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/coreboot -I$(srcdir)/kern/i386/coreboot $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_coreboot_init.o")
-include kernel_mod-kern_i386_coreboot_init.d

kernel_mod-kern_i386_qemu_mmap.o: kern/i386/qemu/mmap.c $(kern/i386/qemu/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/qemu -I$(srcdir)/kern/i386/qemu $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_qemu_mmap.o")
-include kernel_mod-kern_i386_qemu_mmap.d

kernel_mod-kern_i386_halt.o: kern/i386/halt.c $(kern/i386/halt.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_halt.o")
-include kernel_mod-kern_i386_halt.d

kernel_mod-kern_main.o: kern/main.c $(kern/main.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_main.o")
-include kernel_mod-kern_main.d

kernel_mod-kern_device.o: kern/device.c $(kern/device.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_device.o")
-include kernel_mod-kern_device.d

kernel_mod-kern_disk.o: kern/disk.c $(kern/disk.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_disk.o")
-include kernel_mod-kern_disk.d

kernel_mod-kern_dl.o: kern/dl.c $(kern/dl.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_dl.o")
-include kernel_mod-kern_dl.d

kernel_mod-kern_file.o: kern/file.c $(kern/file.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_file.o")
-include kernel_mod-kern_file.d

kernel_mod-kern_fs.o: kern/fs.c $(kern/fs.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_fs.o")
-include kernel_mod-kern_fs.d

kernel_mod-kern_err.o: kern/err.c $(kern/err.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_err.o")
-include kernel_mod-kern_err.d

kernel_mod-kern_misc.o: kern/misc.c $(kern/misc.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_misc.o")
-include kernel_mod-kern_misc.d

kernel_mod-kern_mm.o: kern/mm.c $(kern/mm.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_mm.o")
-include kernel_mod-kern_mm.d

kernel_mod-kern_term.o: kern/term.c $(kern/term.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_term.o")
-include kernel_mod-kern_term.d

kernel_mod-kern_rescue_parser.o: kern/rescue_parser.c $(kern/rescue_parser.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_rescue_parser.o")
-include kernel_mod-kern_rescue_parser.d

kernel_mod-kern_rescue_reader.o: kern/rescue_reader.c $(kern/rescue_reader.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_rescue_reader.o")
-include kernel_mod-kern_rescue_reader.d

kernel_mod-kern_time.o: kern/time.c $(kern/time.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_time.o")
-include kernel_mod-kern_time.d

kernel_mod-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_list.o")
-include kernel_mod-kern_list.d

kernel_mod-kern_handler.o: kern/handler.c $(kern/handler.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_handler.o")
-include kernel_mod-kern_handler.d

kernel_mod-kern_command.o: kern/command.c $(kern/command.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_command.o")
-include kernel_mod-kern_command.d

kernel_mod-kern_corecmd.o: kern/corecmd.c $(kern/corecmd.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_corecmd.o")
-include kernel_mod-kern_corecmd.d

kernel_mod-kern_parser.o: kern/parser.c $(kern/parser.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_parser.o")
-include kernel_mod-kern_parser.d

kernel_mod-kern_partition.o: kern/partition.c $(kern/partition.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_partition.o")
-include kernel_mod-kern_partition.d

kernel_mod-kern_i386_tsc.o: kern/i386/tsc.c $(kern/i386/tsc.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_tsc.o")
-include kernel_mod-kern_i386_tsc.d

kernel_mod-kern_i386_pit.o: kern/i386/pit.c $(kern/i386/pit.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_pit.o")
-include kernel_mod-kern_i386_pit.d

kernel_mod-kern_generic_rtc_get_time_ms.o: kern/generic/rtc_get_time_ms.c $(kern/generic/rtc_get_time_ms.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/generic -I$(srcdir)/kern/generic $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_generic_rtc_get_time_ms.o")
-include kernel_mod-kern_generic_rtc_get_time_ms.d

kernel_mod-kern_generic_millisleep.o: kern/generic/millisleep.c $(kern/generic/millisleep.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/generic -I$(srcdir)/kern/generic $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_generic_millisleep.o")
-include kernel_mod-kern_generic_millisleep.d

kernel_mod-kern_env.o: kern/env.c $(kern/env.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_env.o")
-include kernel_mod-kern_env.d

kernel_mod-term_i386_pc_vga_text.o: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-term_i386_pc_vga_text.o")
-include kernel_mod-term_i386_pc_vga_text.d

kernel_mod-term_i386_vga_common.o: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-term_i386_vga_common.o")
-include kernel_mod-term_i386_vga_common.d

kernel_mod_CFLAGS = $(COMMON_CFLAGS) -DGRUB_BOOT_MACHINE_LINK_ADDR=$(GRUB_BOOT_MACHINE_LINK_ADDR)
kernel_mod_ASFLAGS = $(COMMON_ASFLAGS) -DGRUB_KERNEL_MACHINE_LINK_ADDR=$(GRUB_KERNEL_MACHINE_LINK_ADDR)
endif

sbin_SCRIPTS += grub-install
grub_install_SOURCES = util/grub-install.in
CLEANFILES += grub-install

grub-install: util/grub-install.in $(util/grub-install.in_DEPENDENCIES) config.status
	./config.status --file=-:util/grub-install.in | sed -e 's,@pkglib_DATA@,$(pkglib_DATA),g' > $@
	chmod +x $@


bin_SCRIPTS += grub-mkrescue
grub_mkrescue_SOURCES = util/grub-mkrescue.in
CLEANFILES += grub-mkrescue

grub-mkrescue: util/grub-mkrescue.in $(util/grub-mkrescue.in_DEPENDENCIES) config.status
	./config.status --file=-:util/grub-mkrescue.in | sed -e 's,@pkglib_DATA@,$(pkglib_DATA),g' > $@
	chmod +x $@


# Modules.
pkglib_MODULES = linux.mod 				\
	aout.mod play.mod serial.mod 			\
	memdisk.mod pci.mod lspci.mod reboot.mod	\
	halt.mod datetime.mod date.mod datehook.mod	\
	lsmmap.mod mmap.mod

# For boot.mod.
pkglib_MODULES += boot.mod
boot_mod_SOURCES = commands/boot.c

clean-module-boot.mod.1:
	rm -f boot.mod boot_mod-commands_boot.o

CLEAN_MODULE_TARGETS += clean-module-boot.mod.1

mostlyclean-module-boot.mod.1:
	rm -f boot_mod-commands_boot.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-boot.mod.1

boot.mod: $(boot_mod_DEPENDENCIES) boot_mod-commands_boot.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   boot.mod")

MODFILES += boot.mod

boot_mod-commands_boot.o: commands/boot.c $(commands/boot.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(boot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    boot_mod-commands_boot.o")
-include boot_mod-commands_boot.d

boot_mod_CFLAGS = $(COMMON_CFLAGS)
boot_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For mmap.mod.
mmap_mod_SOURCES = mmap/mmap.c mmap/i386/uppermem.c mmap/i386/mmap.c

clean-module-mmap.mod.1:
	rm -f mmap.mod mmap_mod-mmap_mmap.o mmap_mod-mmap_i386_uppermem.o mmap_mod-mmap_i386_mmap.o

CLEAN_MODULE_TARGETS += clean-module-mmap.mod.1

mostlyclean-module-mmap.mod.1:
	rm -f mmap_mod-mmap_mmap.d mmap_mod-mmap_i386_uppermem.d mmap_mod-mmap_i386_mmap.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-mmap.mod.1

mmap.mod: $(mmap_mod_DEPENDENCIES) mmap_mod-mmap_mmap.o mmap_mod-mmap_i386_uppermem.o mmap_mod-mmap_i386_mmap.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   mmap.mod")

MODFILES += mmap.mod

mmap_mod-mmap_mmap.o: mmap/mmap.c $(mmap/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap -I$(srcdir)/mmap $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_mmap.o")
-include mmap_mod-mmap_mmap.d

mmap_mod-mmap_i386_uppermem.o: mmap/i386/uppermem.c $(mmap/i386/uppermem.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap/i386 -I$(srcdir)/mmap/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_i386_uppermem.o")
-include mmap_mod-mmap_i386_uppermem.d

mmap_mod-mmap_i386_mmap.o: mmap/i386/mmap.c $(mmap/i386/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap/i386 -I$(srcdir)/mmap/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_i386_mmap.o")
-include mmap_mod-mmap_i386_mmap.d

mmap_mod_CFLAGS = $(COMMON_CFLAGS)
mmap_mod_LDFLAGS = $(COMMON_LDFLAGS)
mmap_mod_ASFLAGS = $(COMMON_ASFLAGS)

# For linux.mod.
linux_mod_SOURCES = loader/i386/linux.c

clean-module-linux.mod.1:
	rm -f linux.mod linux_mod-loader_i386_linux.o

CLEAN_MODULE_TARGETS += clean-module-linux.mod.1

mostlyclean-module-linux.mod.1:
	rm -f linux_mod-loader_i386_linux.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-linux.mod.1

linux.mod: $(linux_mod_DEPENDENCIES) linux_mod-loader_i386_linux.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   linux.mod")

MODFILES += linux.mod

linux_mod-loader_i386_linux.o: loader/i386/linux.c $(loader/i386/linux.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(linux_mod_CFLAGS) -MD -c -o $@ $<,"  CC    linux_mod-loader_i386_linux.o")
-include linux_mod-loader_i386_linux.d

linux_mod_CFLAGS = $(COMMON_CFLAGS)
linux_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For reboot.mod.
reboot_mod_SOURCES = commands/reboot.c

clean-module-reboot.mod.1:
	rm -f reboot.mod reboot_mod-commands_reboot.o

CLEAN_MODULE_TARGETS += clean-module-reboot.mod.1

mostlyclean-module-reboot.mod.1:
	rm -f reboot_mod-commands_reboot.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-reboot.mod.1

reboot.mod: $(reboot_mod_DEPENDENCIES) reboot_mod-commands_reboot.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   reboot.mod")

MODFILES += reboot.mod

reboot_mod-commands_reboot.o: commands/reboot.c $(commands/reboot.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(reboot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    reboot_mod-commands_reboot.o")
-include reboot_mod-commands_reboot.d

reboot_mod_CFLAGS = $(COMMON_CFLAGS)
reboot_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For halt.mod.
halt_mod_SOURCES = commands/halt.c

clean-module-halt.mod.1:
	rm -f halt.mod halt_mod-commands_halt.o

CLEAN_MODULE_TARGETS += clean-module-halt.mod.1

mostlyclean-module-halt.mod.1:
	rm -f halt_mod-commands_halt.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-halt.mod.1

halt.mod: $(halt_mod_DEPENDENCIES) halt_mod-commands_halt.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   halt.mod")

MODFILES += halt.mod

halt_mod-commands_halt.o: commands/halt.c $(commands/halt.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(halt_mod_CFLAGS) -MD -c -o $@ $<,"  CC    halt_mod-commands_halt.o")
-include halt_mod-commands_halt.d

halt_mod_CFLAGS = $(COMMON_CFLAGS)
halt_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For serial.mod.
serial_mod_SOURCES = term/serial.c

clean-module-serial.mod.1:
	rm -f serial.mod serial_mod-term_serial.o

CLEAN_MODULE_TARGETS += clean-module-serial.mod.1

mostlyclean-module-serial.mod.1:
	rm -f serial_mod-term_serial.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-serial.mod.1

serial.mod: $(serial_mod_DEPENDENCIES) serial_mod-term_serial.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   serial.mod")

MODFILES += serial.mod

serial_mod-term_serial.o: term/serial.c $(term/serial.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(serial_mod_CFLAGS) -MD -c -o $@ $<,"  CC    serial_mod-term_serial.o")
-include serial_mod-term_serial.d

serial_mod_CFLAGS = $(COMMON_CFLAGS)
serial_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For aout.mod.
aout_mod_SOURCES = loader/aout.c

clean-module-aout.mod.1:
	rm -f aout.mod aout_mod-loader_aout.o

CLEAN_MODULE_TARGETS += clean-module-aout.mod.1

mostlyclean-module-aout.mod.1:
	rm -f aout_mod-loader_aout.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-aout.mod.1

aout.mod: $(aout_mod_DEPENDENCIES) aout_mod-loader_aout.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   aout.mod")

MODFILES += aout.mod

aout_mod-loader_aout.o: loader/aout.c $(loader/aout.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(aout_mod_CFLAGS) -MD -c -o $@ $<,"  CC    aout_mod-loader_aout.o")
-include aout_mod-loader_aout.d

aout_mod_CFLAGS = $(COMMON_CFLAGS)
aout_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For bsd.mod
pkglib_MODULES += bsd.mod
bsd_mod_SOURCES = loader/i386/bsd.c loader/i386/bsd32.c loader/i386/bsd64.c loader/i386/bsd_helper.S loader/i386/bsd_trampoline.S

clean-module-bsd.mod.1:
	rm -f bsd.mod bsd_mod-loader_i386_bsd.o bsd_mod-loader_i386_bsd32.o bsd_mod-loader_i386_bsd64.o bsd_mod-loader_i386_bsd_helper.o bsd_mod-loader_i386_bsd_trampoline.o

CLEAN_MODULE_TARGETS += clean-module-bsd.mod.1

mostlyclean-module-bsd.mod.1:
	rm -f bsd_mod-loader_i386_bsd.d bsd_mod-loader_i386_bsd32.d bsd_mod-loader_i386_bsd64.d bsd_mod-loader_i386_bsd_helper.d bsd_mod-loader_i386_bsd_trampoline.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-bsd.mod.1

bsd.mod: $(bsd_mod_DEPENDENCIES) bsd_mod-loader_i386_bsd.o bsd_mod-loader_i386_bsd32.o bsd_mod-loader_i386_bsd64.o bsd_mod-loader_i386_bsd_helper.o bsd_mod-loader_i386_bsd_trampoline.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   bsd.mod")

MODFILES += bsd.mod

bsd_mod-loader_i386_bsd.o: loader/i386/bsd.c $(loader/i386/bsd.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(bsd_mod_CFLAGS) -MD -c -o $@ $<,"  CC    bsd_mod-loader_i386_bsd.o")
-include bsd_mod-loader_i386_bsd.d

bsd_mod-loader_i386_bsd32.o: loader/i386/bsd32.c $(loader/i386/bsd32.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(bsd_mod_CFLAGS) -MD -c -o $@ $<,"  CC    bsd_mod-loader_i386_bsd32.o")
-include bsd_mod-loader_i386_bsd32.d

bsd_mod-loader_i386_bsd64.o: loader/i386/bsd64.c $(loader/i386/bsd64.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(bsd_mod_CFLAGS) -MD -c -o $@ $<,"  CC    bsd_mod-loader_i386_bsd64.o")
-include bsd_mod-loader_i386_bsd64.d

bsd_mod-loader_i386_bsd_helper.o: loader/i386/bsd_helper.S $(loader/i386/bsd_helper.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(bsd_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    bsd_mod-loader_i386_bsd_helper.o")
else
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(bsd_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    bsd_mod-loader_i386_bsd_helper.o")
endif
-include bsd_mod-loader_i386_bsd_helper.d

bsd_mod-loader_i386_bsd_trampoline.o: loader/i386/bsd_trampoline.S $(loader/i386/bsd_trampoline.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(bsd_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    bsd_mod-loader_i386_bsd_trampoline.o")
else
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(bsd_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    bsd_mod-loader_i386_bsd_trampoline.o")
endif
-include bsd_mod-loader_i386_bsd_trampoline.d

bsd_mod_CFLAGS = $(COMMON_CFLAGS)
bsd_mod_LDFLAGS = $(COMMON_LDFLAGS)
bsd_mod_ASFLAGS = $(COMMON_ASFLAGS)

# For play.mod.
play_mod_SOURCES = commands/i386/pc/play.c

clean-module-play.mod.1:
	rm -f play.mod play_mod-commands_i386_pc_play.o

CLEAN_MODULE_TARGETS += clean-module-play.mod.1

mostlyclean-module-play.mod.1:
	rm -f play_mod-commands_i386_pc_play.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-play.mod.1

play.mod: $(play_mod_DEPENDENCIES) play_mod-commands_i386_pc_play.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   play.mod")

MODFILES += play.mod

play_mod-commands_i386_pc_play.o: commands/i386/pc/play.c $(commands/i386/pc/play.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/i386/pc -I$(srcdir)/commands/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(play_mod_CFLAGS) -MD -c -o $@ $<,"  CC    play_mod-commands_i386_pc_play.o")
-include play_mod-commands_i386_pc_play.d

play_mod_CFLAGS = $(COMMON_CFLAGS)
play_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For memdisk.mod.
memdisk_mod_SOURCES = disk/memdisk.c

clean-module-memdisk.mod.1:
	rm -f memdisk.mod memdisk_mod-disk_memdisk.o

CLEAN_MODULE_TARGETS += clean-module-memdisk.mod.1

mostlyclean-module-memdisk.mod.1:
	rm -f memdisk_mod-disk_memdisk.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-memdisk.mod.1

memdisk.mod: $(memdisk_mod_DEPENDENCIES) memdisk_mod-disk_memdisk.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   memdisk.mod")

MODFILES += memdisk.mod

memdisk_mod-disk_memdisk.o: disk/memdisk.c $(disk/memdisk.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(memdisk_mod_CFLAGS) -MD -c -o $@ $<,"  CC    memdisk_mod-disk_memdisk.o")
-include memdisk_mod-disk_memdisk.d

memdisk_mod_CFLAGS = $(COMMON_CFLAGS)
memdisk_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For pci.mod
pci_mod_SOURCES = bus/pci.c

clean-module-pci.mod.1:
	rm -f pci.mod pci_mod-bus_pci.o

CLEAN_MODULE_TARGETS += clean-module-pci.mod.1

mostlyclean-module-pci.mod.1:
	rm -f pci_mod-bus_pci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-pci.mod.1

pci.mod: $(pci_mod_DEPENDENCIES) pci_mod-bus_pci.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   pci.mod")

MODFILES += pci.mod

pci_mod-bus_pci.o: bus/pci.c $(bus/pci.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ibus -I$(srcdir)/bus $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(pci_mod_CFLAGS) -MD -c -o $@ $<,"  CC    pci_mod-bus_pci.o")
-include pci_mod-bus_pci.d

pci_mod_CFLAGS = $(COMMON_CFLAGS)
pci_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For lspci.mod
lspci_mod_SOURCES = commands/lspci.c

clean-module-lspci.mod.1:
	rm -f lspci.mod lspci_mod-commands_lspci.o

CLEAN_MODULE_TARGETS += clean-module-lspci.mod.1

mostlyclean-module-lspci.mod.1:
	rm -f lspci_mod-commands_lspci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-lspci.mod.1

lspci.mod: $(lspci_mod_DEPENDENCIES) lspci_mod-commands_lspci.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   lspci.mod")

MODFILES += lspci.mod

lspci_mod-commands_lspci.o: commands/lspci.c $(commands/lspci.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(lspci_mod_CFLAGS) -MD -c -o $@ $<,"  CC    lspci_mod-commands_lspci.o")
-include lspci_mod-commands_lspci.d

lspci_mod_CFLAGS = $(COMMON_CFLAGS)
lspci_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For datetime.mod
datetime_mod_SOURCES = lib/cmos_datetime.c

clean-module-datetime.mod.1:
	rm -f datetime.mod datetime_mod-lib_cmos_datetime.o

CLEAN_MODULE_TARGETS += clean-module-datetime.mod.1

mostlyclean-module-datetime.mod.1:
	rm -f datetime_mod-lib_cmos_datetime.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-datetime.mod.1

datetime.mod: $(datetime_mod_DEPENDENCIES) datetime_mod-lib_cmos_datetime.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   datetime.mod")

MODFILES += datetime.mod

datetime_mod-lib_cmos_datetime.o: lib/cmos_datetime.c $(lib/cmos_datetime.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib -I$(srcdir)/lib $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(datetime_mod_CFLAGS) -MD -c -o $@ $<,"  CC    datetime_mod-lib_cmos_datetime.o")
-include datetime_mod-lib_cmos_datetime.d

datetime_mod_CFLAGS = $(COMMON_CFLAGS)
datetime_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For date.mod
date_mod_SOURCES = commands/date.c

clean-module-date.mod.1:
	rm -f date.mod date_mod-commands_date.o

CLEAN_MODULE_TARGETS += clean-module-date.mod.1

mostlyclean-module-date.mod.1:
	rm -f date_mod-commands_date.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-date.mod.1

date.mod: $(date_mod_DEPENDENCIES) date_mod-commands_date.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   date.mod")

MODFILES += date.mod

date_mod-commands_date.o: commands/date.c $(commands/date.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(date_mod_CFLAGS) -MD -c -o $@ $<,"  CC    date_mod-commands_date.o")
-include date_mod-commands_date.d

date_mod_CFLAGS = $(COMMON_CFLAGS)
date_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For datehook.mod
datehook_mod_SOURCES = hook/datehook.c

clean-module-datehook.mod.1:
	rm -f datehook.mod datehook_mod-hook_datehook.o

CLEAN_MODULE_TARGETS += clean-module-datehook.mod.1

mostlyclean-module-datehook.mod.1:
	rm -f datehook_mod-hook_datehook.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-datehook.mod.1

datehook.mod: $(datehook_mod_DEPENDENCIES) datehook_mod-hook_datehook.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   datehook.mod")

MODFILES += datehook.mod

datehook_mod-hook_datehook.o: hook/datehook.c $(hook/datehook.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ihook -I$(srcdir)/hook $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(datehook_mod_CFLAGS) -MD -c -o $@ $<,"  CC    datehook_mod-hook_datehook.o")
-include datehook_mod-hook_datehook.d

datehook_mod_CFLAGS = $(COMMON_CFLAGS)
datehook_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For lsmmap.mod
lsmmap_mod_SOURCES = commands/lsmmap.c

clean-module-lsmmap.mod.1:
	rm -f lsmmap.mod lsmmap_mod-commands_lsmmap.o

CLEAN_MODULE_TARGETS += clean-module-lsmmap.mod.1

mostlyclean-module-lsmmap.mod.1:
	rm -f lsmmap_mod-commands_lsmmap.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-lsmmap.mod.1

lsmmap.mod: $(lsmmap_mod_DEPENDENCIES) lsmmap_mod-commands_lsmmap.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   lsmmap.mod")

MODFILES += lsmmap.mod

lsmmap_mod-commands_lsmmap.o: commands/lsmmap.c $(commands/lsmmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(lsmmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    lsmmap_mod-commands_lsmmap.o")
-include lsmmap_mod-commands_lsmmap.d

lsmmap_mod_CFLAGS = $(COMMON_CFLAGS)
lsmmap_mod_LDFLAGS = $(COMMON_LDFLAGS)

include $(srcdir)/conf/i386.mk
include $(srcdir)/conf/common.mk
grub-mkimage: $(grub_mkimage_DEPENDENCIES) $(grub_mkimage_OBJECTS)
	$(call quiet-command,$(CC) -o $@ $(grub_mkimage_OBJECTS) $(LDFLAGS) $(grub_mkimage_LDFLAGS),"  LINK  grub-mkimage")

