# -*- makefile -*-
# Generated by genmk.rb, please don't edit!

# For grub-shell
grub-shell: tests/util/grub-shell.in config.status
	./config.status --file=$@:$<
	chmod +x $@
check_SCRIPTS += grub-shell
CLEANFILES += grub-shell

# For grub-shell-tester
grub-shell-tester: tests/util/grub-shell-tester.in config.status
	./config.status --file=$@:$<
	chmod +x $@
check_SCRIPTS += grub-shell-tester
CLEANFILES += grub-shell-tester

pkglib_MODULES += functional_test.mod
functional_test_mod_SOURCES = tests/lib/functional_test.c tests/lib/test.c

clean-module-functional_test.mod.1:
	rm -f functional_test.mod functional_test_mod-tests_lib_functional_test.o functional_test_mod-tests_lib_test.o

CLEAN_MODULE_TARGETS += clean-module-functional_test.mod.1

mostlyclean-module-functional_test.mod.1:
	rm -f functional_test_mod-tests_lib_functional_test.d functional_test_mod-tests_lib_test.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-functional_test.mod.1

functional_test.mod: $(functional_test_mod_DEPENDENCIES) functional_test_mod-tests_lib_functional_test.o functional_test_mod-tests_lib_test.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   functional_test.mod")

MODFILES += functional_test.mod

functional_test_mod-tests_lib_functional_test.o: tests/lib/functional_test.c $(tests/lib/functional_test.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -MD -c -o $@ $<,"  CC    functional_test_mod-tests_lib_functional_test.o")
-include functional_test_mod-tests_lib_functional_test.d

functional_test_mod-tests_lib_test.o: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -MD -c -o $@ $<,"  CC    functional_test_mod-tests_lib_test.o")
-include functional_test_mod-tests_lib_test.d

functional_test_mod_CFLAGS  = $(COMMON_CFLAGS)
functional_test_mod_LDFLAGS = $(COMMON_LDFLAGS)

# Rules for unit tests
check_UTILITIES += example_unit_test
example_unit_test_SOURCES = tests/example_unit_test.c kern/list.c kern/misc.c tests/lib/test.c tests/lib/unit_test.c

clean-utility-example_unit_test.1:
	rm -f example_unit_test$(EXEEXT) example_unit_test-tests_example_unit_test.o example_unit_test-kern_list.o example_unit_test-kern_misc.o example_unit_test-tests_lib_test.o example_unit_test-tests_lib_unit_test.o

CLEAN_UTILITY_TARGETS += clean-utility-example_unit_test.1

mostlyclean-utility-example_unit_test.1:
	rm -f example_unit_test-tests_example_unit_test.d example_unit_test-kern_list.d example_unit_test-kern_misc.d example_unit_test-tests_lib_test.d example_unit_test-tests_lib_unit_test.d

MOSTLYCLEAN_UTILITY_TARGETS += mostlyclean-utility-example_unit_test.1

example_unit_test_OBJECTS += example_unit_test-tests_example_unit_test.o example_unit_test-kern_list.o example_unit_test-kern_misc.o example_unit_test-tests_lib_test.o example_unit_test-tests_lib_unit_test.o

example_unit_test-tests_example_unit_test.o: tests/example_unit_test.c $(tests/example_unit_test.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Itests -I$(srcdir)/tests $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<,"  CC    example_unit_test-tests_example_unit_test.o")
-include example_unit_test-tests_example_unit_test.d

example_unit_test-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<,"  CC    example_unit_test-kern_list.o")
-include example_unit_test-kern_list.d

example_unit_test-kern_misc.o: kern/misc.c $(kern/misc.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<,"  CC    example_unit_test-kern_misc.o")
-include example_unit_test-kern_misc.d

example_unit_test-tests_lib_test.o: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Itests/lib -I$(srcdir)/tests/lib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<,"  CC    example_unit_test-tests_lib_test.o")
-include example_unit_test-tests_lib_test.d

example_unit_test-tests_lib_unit_test.o: tests/lib/unit_test.c $(tests/lib/unit_test.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Itests/lib -I$(srcdir)/tests/lib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<,"  CC    example_unit_test-tests_lib_unit_test.o")
-include example_unit_test-tests_lib_unit_test.d

example_unit_test_CFLAGS  = -Wno-format

# Rules for functional tests
pkglib_MODULES += example_functional_test.mod
example_functional_test_mod_SOURCES = tests/example_functional_test.c

clean-module-example_functional_test.mod.1:
	rm -f example_functional_test.mod example_functional_test_mod-tests_example_functional_test.o

CLEAN_MODULE_TARGETS += clean-module-example_functional_test.mod.1

mostlyclean-module-example_functional_test.mod.1:
	rm -f example_functional_test_mod-tests_example_functional_test.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-example_functional_test.mod.1

example_functional_test.mod: $(example_functional_test_mod_DEPENDENCIES) example_functional_test_mod-tests_example_functional_test.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   example_functional_test.mod")

MODFILES += example_functional_test.mod

example_functional_test_mod-tests_example_functional_test.o: tests/example_functional_test.c $(tests/example_functional_test.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Itests -I$(srcdir)/tests $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -MD -c -o $@ $<,"  CC    example_functional_test_mod-tests_example_functional_test.o")
-include example_functional_test_mod-tests_example_functional_test.d

example_functional_test_mod_CFLAGS  = -Wno-format $(COMMON_CFLAGS)
example_functional_test_mod_LDFLAGS = $(COMMON_LDFLAGS)

# Rules for scripted tests
check_SCRIPTS += example_scripted_test
example_scripted_test_SOURCES = tests/example_scripted_test.in
CLEANFILES += example_scripted_test

example_scripted_test: tests/example_scripted_test.in $(tests/example_scripted_test.in_DEPENDENCIES) config.status
	./config.status --file=-:tests/example_scripted_test.in | sed -e 's,@pkglib_DATA@,$(pkglib_DATA),g' > $@
	chmod +x $@


check_SCRIPTS += example_grub_script_test
example_grub_script_test_SOURCES = tests/example_grub_script_test.in
CLEANFILES += example_grub_script_test

example_grub_script_test: tests/example_grub_script_test.in $(tests/example_grub_script_test.in_DEPENDENCIES) config.status
	./config.status --file=-:tests/example_grub_script_test.in | sed -e 's,@pkglib_DATA@,$(pkglib_DATA),g' > $@
	chmod +x $@



# List of tests to execute on "make check"
SCRIPTED_TESTS    = example_scripted_test
SCRIPTED_TESTS   += example_grub_script_test
UNIT_TESTS        = example_unit_test
FUNCTIONAL_TESTS  = example_functional_test.mod

# dependencies between tests and testing-tools
$(SCRIPTED_TESTS): grub-shell grub-shell-tester
$(FUNCTIONAL_TESTS): functional_test.mod

example_unit_test: $(example_unit_test_DEPENDENCIES) $(example_unit_test_OBJECTS)
	$(call quiet-command,$(CC) -o $@ $(example_unit_test_OBJECTS) $(LDFLAGS) $(example_unit_test_LDFLAGS),"  LINK  example_unit_test")

