# -*- makefile -*-
# Generated by genmk.rb, please don't edit!

COMMON_ASFLAGS = -nostdinc -fno-unwind-tables -mcmodel=large  -fPIC -fno-pie -mno-red-zone -fno-stack-protector -Wno-error=trampolines -Wtrampolines -fno-builtin -Werror  -ffreestanding -m64
COMMON_CFLAGS = -fno-builtin -fno-unwind-tables -mcmodel=large  -fPIC -fno-pie -mno-red-zone -fno-stack-protector -Wno-error=trampolines -Wtrampolines -Werror   -ffreestanding -m64
COMMON_LDFLAGS = -melf_x86_64 -fPIC -fno-unwind-tables -mcmodel=large  -fno-pie -mno-red-zone -fno-stack-protector -Wno-error=trampolines -Wtrampolines -Werror  -ffreestanding -nostdlib

# Used by various components.  These rules need to precede them.
script/lexer.c_DEPENDENCIES = grub_script.tab.h

# Utilities.
bin_UTILITIES = grub-mkimage

# For grub-mkimage.
grub_mkimage_SOURCES = gnulib/progname.c util/efi/grub-mkimage.c util/misc.c \
	util/resolve.c util/obj.c kern/list.c

clean-utility-grub-mkimage.1:
	rm -f grub-mkimage$(EXEEXT) grub_mkimage-gnulib_progname.o grub_mkimage-util_efi_grub_mkimage.o grub_mkimage-util_misc.o grub_mkimage-util_resolve.o grub_mkimage-util_obj.o grub_mkimage-kern_list.o

CLEAN_UTILITY_TARGETS += clean-utility-grub-mkimage.1

mostlyclean-utility-grub-mkimage.1:
	rm -f grub_mkimage-gnulib_progname.d grub_mkimage-util_efi_grub_mkimage.d grub_mkimage-util_misc.d grub_mkimage-util_resolve.d grub_mkimage-util_obj.d grub_mkimage-kern_list.d

MOSTLYCLEAN_UTILITY_TARGETS += mostlyclean-utility-grub-mkimage.1

grub_mkimage_OBJECTS += grub_mkimage-gnulib_progname.o grub_mkimage-util_efi_grub_mkimage.o grub_mkimage-util_misc.o grub_mkimage-util_resolve.o grub_mkimage-util_obj.o grub_mkimage-kern_list.o

grub_mkimage-gnulib_progname.o: gnulib/progname.c $(gnulib/progname.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ignulib -I$(srcdir)/gnulib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-gnulib_progname.o")
-include grub_mkimage-gnulib_progname.d

grub_mkimage-util_efi_grub_mkimage.o: util/efi/grub-mkimage.c $(util/efi/grub-mkimage.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil/efi -I$(srcdir)/util/efi $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_efi_grub_mkimage.o")
-include grub_mkimage-util_efi_grub_mkimage.d

grub_mkimage-util_misc.o: util/misc.c $(util/misc.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_misc.o")
-include grub_mkimage-util_misc.d

grub_mkimage-util_resolve.o: util/resolve.c $(util/resolve.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_resolve.o")
-include grub_mkimage-util_resolve.d

grub_mkimage-util_obj.o: util/obj.c $(util/obj.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Iutil -I$(srcdir)/util $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-util_obj.o")
-include grub_mkimage-util_obj.d

grub_mkimage-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(call quiet-command,$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(grub_mkimage_CFLAGS) -MD -c -o $@ $<,"  CC    grub_mkimage-kern_list.o")
-include grub_mkimage-kern_list.d


# For grub-setup.
#grub_setup_SOURCES = util/i386/pc/grub-setup.c util/hostdisk.c	\
#	util/misc.c util/getroot.c kern/device.c kern/disk.c	\
#	kern/err.c kern/misc.c fs/fat.c fs/ext2.c fs/xfs.c fs/affs.c	\
#	fs/sfs.c kern/parser.c kern/partition.c partmap/msdos.c		\
#	fs/ufs.c fs/ufs2.c fs/minix.c fs/hfs.c fs/jfs.c fs/hfsplus.c kern/file.c	\
#	kern/fs.c kern/env.c fs/fshelp.c

# For grub-mkrescue
bin_SCRIPTS += grub-mkrescue

grub_mkrescue_SOURCES = util/grub-mkrescue.in
CLEANFILES += grub-mkrescue

grub-mkrescue: util/grub-mkrescue.in $(util/grub-mkrescue.in_DEPENDENCIES) config.status
	./config.status --file=-:util/grub-mkrescue.in | sed -e 's,@pkglib_DATA@,$(pkglib_DATA),g' > $@
	chmod +x $@


# Modules.
pkglib_MODULES = kernel.mod chain.mod appleldr.mod 	\
	halt.mod reboot.mod linux.mod pci.mod lspci.mod \
	datetime.mod date.mod datehook.mod loadbios.mod \
	fixvideo.mod fwsetup.mod mmap.mod acpi.mod efi_gop.mod efi_uga.mod

# For kernel.mod.
kernel_mod_SOURCES = kern/x86_64/efi/startup.S kern/x86_64/efi/callwrap.S \
	kern/main.c kern/device.c \
	kern/disk.c kern/dl.c kern/file.c kern/fs.c kern/err.c \
	kern/misc.c kern/mm.c kern/term.c \
	kern/rescue_parser.c kern/rescue_reader.c \
	kern/i386/efi/init.c kern/parser.c kern/partition.c \
	kern/env.c kern/efi/efi.c kern/efi/init.c kern/efi/mm.c \
	kern/time.c kern/list.c kern/handler.c kern/command.c kern/corecmd.c \
	kern/i386/tsc.c kern/i386/pit.c \
	kern/generic/millisleep.c kern/generic/rtc_get_time_ms.c \
	term/efi/console.c disk/efi/efidisk.c lib/charset.c

clean-module-kernel.mod.1:
	rm -f kernel.mod kernel_mod-kern_x86_64_efi_startup.o kernel_mod-kern_x86_64_efi_callwrap.o kernel_mod-kern_main.o kernel_mod-kern_device.o kernel_mod-kern_disk.o kernel_mod-kern_dl.o kernel_mod-kern_file.o kernel_mod-kern_fs.o kernel_mod-kern_err.o kernel_mod-kern_misc.o kernel_mod-kern_mm.o kernel_mod-kern_term.o kernel_mod-kern_rescue_parser.o kernel_mod-kern_rescue_reader.o kernel_mod-kern_i386_efi_init.o kernel_mod-kern_parser.o kernel_mod-kern_partition.o kernel_mod-kern_env.o kernel_mod-kern_efi_efi.o kernel_mod-kern_efi_init.o kernel_mod-kern_efi_mm.o kernel_mod-kern_time.o kernel_mod-kern_list.o kernel_mod-kern_handler.o kernel_mod-kern_command.o kernel_mod-kern_corecmd.o kernel_mod-kern_i386_tsc.o kernel_mod-kern_i386_pit.o kernel_mod-kern_generic_millisleep.o kernel_mod-kern_generic_rtc_get_time_ms.o kernel_mod-term_efi_console.o kernel_mod-disk_efi_efidisk.o kernel_mod-lib_charset.o

CLEAN_MODULE_TARGETS += clean-module-kernel.mod.1

mostlyclean-module-kernel.mod.1:
	rm -f kernel_mod-kern_x86_64_efi_startup.d kernel_mod-kern_x86_64_efi_callwrap.d kernel_mod-kern_main.d kernel_mod-kern_device.d kernel_mod-kern_disk.d kernel_mod-kern_dl.d kernel_mod-kern_file.d kernel_mod-kern_fs.d kernel_mod-kern_err.d kernel_mod-kern_misc.d kernel_mod-kern_mm.d kernel_mod-kern_term.d kernel_mod-kern_rescue_parser.d kernel_mod-kern_rescue_reader.d kernel_mod-kern_i386_efi_init.d kernel_mod-kern_parser.d kernel_mod-kern_partition.d kernel_mod-kern_env.d kernel_mod-kern_efi_efi.d kernel_mod-kern_efi_init.d kernel_mod-kern_efi_mm.d kernel_mod-kern_time.d kernel_mod-kern_list.d kernel_mod-kern_handler.d kernel_mod-kern_command.d kernel_mod-kern_corecmd.d kernel_mod-kern_i386_tsc.d kernel_mod-kern_i386_pit.d kernel_mod-kern_generic_millisleep.d kernel_mod-kern_generic_rtc_get_time_ms.d kernel_mod-term_efi_console.d kernel_mod-disk_efi_efidisk.d kernel_mod-lib_charset.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-kernel.mod.1

kernel.mod: $(kernel_mod_DEPENDENCIES) kernel_mod-kern_x86_64_efi_startup.o kernel_mod-kern_x86_64_efi_callwrap.o kernel_mod-kern_main.o kernel_mod-kern_device.o kernel_mod-kern_disk.o kernel_mod-kern_dl.o kernel_mod-kern_file.o kernel_mod-kern_fs.o kernel_mod-kern_err.o kernel_mod-kern_misc.o kernel_mod-kern_mm.o kernel_mod-kern_term.o kernel_mod-kern_rescue_parser.o kernel_mod-kern_rescue_reader.o kernel_mod-kern_i386_efi_init.o kernel_mod-kern_parser.o kernel_mod-kern_partition.o kernel_mod-kern_env.o kernel_mod-kern_efi_efi.o kernel_mod-kern_efi_init.o kernel_mod-kern_efi_mm.o kernel_mod-kern_time.o kernel_mod-kern_list.o kernel_mod-kern_handler.o kernel_mod-kern_command.o kernel_mod-kern_corecmd.o kernel_mod-kern_i386_tsc.o kernel_mod-kern_i386_pit.o kernel_mod-kern_generic_millisleep.o kernel_mod-kern_generic_rtc_get_time_ms.o kernel_mod-term_efi_console.o kernel_mod-disk_efi_efidisk.o kernel_mod-lib_charset.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   kernel.mod")

MODFILES += kernel.mod

kernel_mod-kern_x86_64_efi_startup.o: kern/x86_64/efi/startup.S $(kern/x86_64/efi/startup.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ikern/x86_64/efi -I$(srcdir)/kern/x86_64/efi $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    kernel_mod-kern_x86_64_efi_startup.o")
else
	$(call quiet-command,$(TARGET_CC) -Ikern/x86_64/efi -I$(srcdir)/kern/x86_64/efi $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    kernel_mod-kern_x86_64_efi_startup.o")
endif
-include kernel_mod-kern_x86_64_efi_startup.d

kernel_mod-kern_x86_64_efi_callwrap.o: kern/x86_64/efi/callwrap.S $(kern/x86_64/efi/callwrap.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Ikern/x86_64/efi -I$(srcdir)/kern/x86_64/efi $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    kernel_mod-kern_x86_64_efi_callwrap.o")
else
	$(call quiet-command,$(TARGET_CC) -Ikern/x86_64/efi -I$(srcdir)/kern/x86_64/efi $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(kernel_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    kernel_mod-kern_x86_64_efi_callwrap.o")
endif
-include kernel_mod-kern_x86_64_efi_callwrap.d

kernel_mod-kern_main.o: kern/main.c $(kern/main.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_main.o")
-include kernel_mod-kern_main.d

kernel_mod-kern_device.o: kern/device.c $(kern/device.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_device.o")
-include kernel_mod-kern_device.d

kernel_mod-kern_disk.o: kern/disk.c $(kern/disk.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_disk.o")
-include kernel_mod-kern_disk.d

kernel_mod-kern_dl.o: kern/dl.c $(kern/dl.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_dl.o")
-include kernel_mod-kern_dl.d

kernel_mod-kern_file.o: kern/file.c $(kern/file.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_file.o")
-include kernel_mod-kern_file.d

kernel_mod-kern_fs.o: kern/fs.c $(kern/fs.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_fs.o")
-include kernel_mod-kern_fs.d

kernel_mod-kern_err.o: kern/err.c $(kern/err.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_err.o")
-include kernel_mod-kern_err.d

kernel_mod-kern_misc.o: kern/misc.c $(kern/misc.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_misc.o")
-include kernel_mod-kern_misc.d

kernel_mod-kern_mm.o: kern/mm.c $(kern/mm.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_mm.o")
-include kernel_mod-kern_mm.d

kernel_mod-kern_term.o: kern/term.c $(kern/term.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_term.o")
-include kernel_mod-kern_term.d

kernel_mod-kern_rescue_parser.o: kern/rescue_parser.c $(kern/rescue_parser.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_rescue_parser.o")
-include kernel_mod-kern_rescue_parser.d

kernel_mod-kern_rescue_reader.o: kern/rescue_reader.c $(kern/rescue_reader.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_rescue_reader.o")
-include kernel_mod-kern_rescue_reader.d

kernel_mod-kern_i386_efi_init.o: kern/i386/efi/init.c $(kern/i386/efi/init.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386/efi -I$(srcdir)/kern/i386/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_efi_init.o")
-include kernel_mod-kern_i386_efi_init.d

kernel_mod-kern_parser.o: kern/parser.c $(kern/parser.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_parser.o")
-include kernel_mod-kern_parser.d

kernel_mod-kern_partition.o: kern/partition.c $(kern/partition.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_partition.o")
-include kernel_mod-kern_partition.d

kernel_mod-kern_env.o: kern/env.c $(kern/env.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_env.o")
-include kernel_mod-kern_env.d

kernel_mod-kern_efi_efi.o: kern/efi/efi.c $(kern/efi/efi.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/efi -I$(srcdir)/kern/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_efi_efi.o")
-include kernel_mod-kern_efi_efi.d

kernel_mod-kern_efi_init.o: kern/efi/init.c $(kern/efi/init.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/efi -I$(srcdir)/kern/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_efi_init.o")
-include kernel_mod-kern_efi_init.d

kernel_mod-kern_efi_mm.o: kern/efi/mm.c $(kern/efi/mm.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/efi -I$(srcdir)/kern/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_efi_mm.o")
-include kernel_mod-kern_efi_mm.d

kernel_mod-kern_time.o: kern/time.c $(kern/time.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_time.o")
-include kernel_mod-kern_time.d

kernel_mod-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_list.o")
-include kernel_mod-kern_list.d

kernel_mod-kern_handler.o: kern/handler.c $(kern/handler.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_handler.o")
-include kernel_mod-kern_handler.d

kernel_mod-kern_command.o: kern/command.c $(kern/command.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_command.o")
-include kernel_mod-kern_command.d

kernel_mod-kern_corecmd.o: kern/corecmd.c $(kern/corecmd.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern -I$(srcdir)/kern $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_corecmd.o")
-include kernel_mod-kern_corecmd.d

kernel_mod-kern_i386_tsc.o: kern/i386/tsc.c $(kern/i386/tsc.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_tsc.o")
-include kernel_mod-kern_i386_tsc.d

kernel_mod-kern_i386_pit.o: kern/i386/pit.c $(kern/i386/pit.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/i386 -I$(srcdir)/kern/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_i386_pit.o")
-include kernel_mod-kern_i386_pit.d

kernel_mod-kern_generic_millisleep.o: kern/generic/millisleep.c $(kern/generic/millisleep.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/generic -I$(srcdir)/kern/generic $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_generic_millisleep.o")
-include kernel_mod-kern_generic_millisleep.d

kernel_mod-kern_generic_rtc_get_time_ms.o: kern/generic/rtc_get_time_ms.c $(kern/generic/rtc_get_time_ms.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ikern/generic -I$(srcdir)/kern/generic $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-kern_generic_rtc_get_time_ms.o")
-include kernel_mod-kern_generic_rtc_get_time_ms.d

kernel_mod-term_efi_console.o: term/efi/console.c $(term/efi/console.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iterm/efi -I$(srcdir)/term/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-term_efi_console.o")
-include kernel_mod-term_efi_console.d

kernel_mod-disk_efi_efidisk.o: disk/efi/efidisk.c $(disk/efi/efidisk.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Idisk/efi -I$(srcdir)/disk/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-disk_efi_efidisk.o")
-include kernel_mod-disk_efi_efidisk.d

kernel_mod-lib_charset.o: lib/charset.c $(lib/charset.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib -I$(srcdir)/lib $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(kernel_mod_CFLAGS) -MD -c -o $@ $<,"  CC    kernel_mod-lib_charset.o")
-include kernel_mod-lib_charset.d

kernel_mod_CFLAGS = $(COMMON_CFLAGS)
kernel_mod_ASFLAGS = $(COMMON_ASFLAGS)
kernel_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For boot.mod.
pkglib_MODULES += boot.mod 
boot_mod_SOURCES = commands/boot.c lib/i386/pc/biosnum.c

clean-module-boot.mod.1:
	rm -f boot.mod boot_mod-commands_boot.o boot_mod-lib_i386_pc_biosnum.o

CLEAN_MODULE_TARGETS += clean-module-boot.mod.1

mostlyclean-module-boot.mod.1:
	rm -f boot_mod-commands_boot.d boot_mod-lib_i386_pc_biosnum.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-boot.mod.1

boot.mod: $(boot_mod_DEPENDENCIES) boot_mod-commands_boot.o boot_mod-lib_i386_pc_biosnum.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   boot.mod")

MODFILES += boot.mod

boot_mod-commands_boot.o: commands/boot.c $(commands/boot.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(boot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    boot_mod-commands_boot.o")
-include boot_mod-commands_boot.d

boot_mod-lib_i386_pc_biosnum.o: lib/i386/pc/biosnum.c $(lib/i386/pc/biosnum.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/i386/pc -I$(srcdir)/lib/i386/pc $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(boot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    boot_mod-lib_i386_pc_biosnum.o")
-include boot_mod-lib_i386_pc_biosnum.d

boot_mod_CFLAGS = $(COMMON_CFLAGS)
boot_mod_LDFLAGS = $(COMMON_LDFLAGS)


# For acpi.mod.
acpi_mod_SOURCES = commands/acpi.c commands/efi/acpi.c

clean-module-acpi.mod.1:
	rm -f acpi.mod acpi_mod-commands_acpi.o acpi_mod-commands_efi_acpi.o

CLEAN_MODULE_TARGETS += clean-module-acpi.mod.1

mostlyclean-module-acpi.mod.1:
	rm -f acpi_mod-commands_acpi.d acpi_mod-commands_efi_acpi.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-acpi.mod.1

acpi.mod: $(acpi_mod_DEPENDENCIES) acpi_mod-commands_acpi.o acpi_mod-commands_efi_acpi.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   acpi.mod")

MODFILES += acpi.mod

acpi_mod-commands_acpi.o: commands/acpi.c $(commands/acpi.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(acpi_mod_CFLAGS) -MD -c -o $@ $<,"  CC    acpi_mod-commands_acpi.o")
-include acpi_mod-commands_acpi.d

acpi_mod-commands_efi_acpi.o: commands/efi/acpi.c $(commands/efi/acpi.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/efi -I$(srcdir)/commands/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(acpi_mod_CFLAGS) -MD -c -o $@ $<,"  CC    acpi_mod-commands_efi_acpi.o")
-include acpi_mod-commands_efi_acpi.d

acpi_mod_CFLAGS = $(COMMON_CFLAGS)
acpi_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For mmap.mod.
mmap_mod_SOURCES = mmap/mmap.c mmap/i386/uppermem.c mmap/i386/mmap.c \
		   mmap/efi/mmap.c

clean-module-mmap.mod.1:
	rm -f mmap.mod mmap_mod-mmap_mmap.o mmap_mod-mmap_i386_uppermem.o mmap_mod-mmap_i386_mmap.o mmap_mod-mmap_efi_mmap.o

CLEAN_MODULE_TARGETS += clean-module-mmap.mod.1

mostlyclean-module-mmap.mod.1:
	rm -f mmap_mod-mmap_mmap.d mmap_mod-mmap_i386_uppermem.d mmap_mod-mmap_i386_mmap.d mmap_mod-mmap_efi_mmap.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-mmap.mod.1

mmap.mod: $(mmap_mod_DEPENDENCIES) mmap_mod-mmap_mmap.o mmap_mod-mmap_i386_uppermem.o mmap_mod-mmap_i386_mmap.o mmap_mod-mmap_efi_mmap.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   mmap.mod")

MODFILES += mmap.mod

mmap_mod-mmap_mmap.o: mmap/mmap.c $(mmap/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap -I$(srcdir)/mmap $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_mmap.o")
-include mmap_mod-mmap_mmap.d

mmap_mod-mmap_i386_uppermem.o: mmap/i386/uppermem.c $(mmap/i386/uppermem.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap/i386 -I$(srcdir)/mmap/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_i386_uppermem.o")
-include mmap_mod-mmap_i386_uppermem.d

mmap_mod-mmap_i386_mmap.o: mmap/i386/mmap.c $(mmap/i386/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap/i386 -I$(srcdir)/mmap/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_i386_mmap.o")
-include mmap_mod-mmap_i386_mmap.d

mmap_mod-mmap_efi_mmap.o: mmap/efi/mmap.c $(mmap/efi/mmap.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Immap/efi -I$(srcdir)/mmap/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(mmap_mod_CFLAGS) -MD -c -o $@ $<,"  CC    mmap_mod-mmap_efi_mmap.o")
-include mmap_mod-mmap_efi_mmap.d

mmap_mod_CFLAGS = $(COMMON_CFLAGS)
mmap_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For chain.mod.
chain_mod_SOURCES = loader/efi/chainloader.c

clean-module-chain.mod.1:
	rm -f chain.mod chain_mod-loader_efi_chainloader.o

CLEAN_MODULE_TARGETS += clean-module-chain.mod.1

mostlyclean-module-chain.mod.1:
	rm -f chain_mod-loader_efi_chainloader.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-chain.mod.1

chain.mod: $(chain_mod_DEPENDENCIES) chain_mod-loader_efi_chainloader.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   chain.mod")

MODFILES += chain.mod

chain_mod-loader_efi_chainloader.o: loader/efi/chainloader.c $(loader/efi/chainloader.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/efi -I$(srcdir)/loader/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(chain_mod_CFLAGS) -MD -c -o $@ $<,"  CC    chain_mod-loader_efi_chainloader.o")
-include chain_mod-loader_efi_chainloader.d

chain_mod_CFLAGS = $(COMMON_CFLAGS)
chain_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For appleldr.mod.
appleldr_mod_SOURCES = loader/efi/appleloader.c

clean-module-appleldr.mod.1:
	rm -f appleldr.mod appleldr_mod-loader_efi_appleloader.o

CLEAN_MODULE_TARGETS += clean-module-appleldr.mod.1

mostlyclean-module-appleldr.mod.1:
	rm -f appleldr_mod-loader_efi_appleloader.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-appleldr.mod.1

appleldr.mod: $(appleldr_mod_DEPENDENCIES) appleldr_mod-loader_efi_appleloader.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   appleldr.mod")

MODFILES += appleldr.mod

appleldr_mod-loader_efi_appleloader.o: loader/efi/appleloader.c $(loader/efi/appleloader.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/efi -I$(srcdir)/loader/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(appleldr_mod_CFLAGS) -MD -c -o $@ $<,"  CC    appleldr_mod-loader_efi_appleloader.o")
-include appleldr_mod-loader_efi_appleloader.d

appleldr_mod_CFLAGS = $(COMMON_CFLAGS)
appleldr_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For linux.mod.
linux_mod_SOURCES = loader/i386/efi/linux.c loader/i386/linux_trampoline.S

clean-module-linux.mod.1:
	rm -f linux.mod linux_mod-loader_i386_efi_linux.o linux_mod-loader_i386_linux_trampoline.o

CLEAN_MODULE_TARGETS += clean-module-linux.mod.1

mostlyclean-module-linux.mod.1:
	rm -f linux_mod-loader_i386_efi_linux.d linux_mod-loader_i386_linux_trampoline.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-linux.mod.1

linux.mod: $(linux_mod_DEPENDENCIES) linux_mod-loader_i386_efi_linux.o linux_mod-loader_i386_linux_trampoline.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   linux.mod")

MODFILES += linux.mod

linux_mod-loader_i386_efi_linux.o: loader/i386/efi/linux.c $(loader/i386/efi/linux.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386/efi -I$(srcdir)/loader/i386/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(linux_mod_CFLAGS) -MD -c -o $@ $<,"  CC    linux_mod-loader_i386_efi_linux.o")
-include linux_mod-loader_i386_efi_linux.d

linux_mod-loader_i386_linux_trampoline.o: loader/i386/linux_trampoline.S $(loader/i386/linux_trampoline.S_DEPENDENCIES)
ifeq ($(AS),)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(linux_mod_ASFLAGS) -MD -c -o $@ $<,"  AS    linux_mod-loader_i386_linux_trampoline.o")
else
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(linux_mod_ASFLAGS) -MD -S $< | $(AS) -o $@,"  AS    linux_mod-loader_i386_linux_trampoline.o")
endif
-include linux_mod-loader_i386_linux_trampoline.d

linux_mod_CFLAGS = $(COMMON_CFLAGS)
linux_mod_ASFLAGS = $(COMMON_ASFLAGS)
linux_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For halt.mod.
halt_mod_SOURCES = commands/halt.c

clean-module-halt.mod.1:
	rm -f halt.mod halt_mod-commands_halt.o

CLEAN_MODULE_TARGETS += clean-module-halt.mod.1

mostlyclean-module-halt.mod.1:
	rm -f halt_mod-commands_halt.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-halt.mod.1

halt.mod: $(halt_mod_DEPENDENCIES) halt_mod-commands_halt.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   halt.mod")

MODFILES += halt.mod

halt_mod-commands_halt.o: commands/halt.c $(commands/halt.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(halt_mod_CFLAGS) -MD -c -o $@ $<,"  CC    halt_mod-commands_halt.o")
-include halt_mod-commands_halt.d

halt_mod_CFLAGS = $(COMMON_CFLAGS)
halt_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For reboot.mod.
reboot_mod_SOURCES = commands/reboot.c

clean-module-reboot.mod.1:
	rm -f reboot.mod reboot_mod-commands_reboot.o

CLEAN_MODULE_TARGETS += clean-module-reboot.mod.1

mostlyclean-module-reboot.mod.1:
	rm -f reboot_mod-commands_reboot.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-reboot.mod.1

reboot.mod: $(reboot_mod_DEPENDENCIES) reboot_mod-commands_reboot.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   reboot.mod")

MODFILES += reboot.mod

reboot_mod-commands_reboot.o: commands/reboot.c $(commands/reboot.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(reboot_mod_CFLAGS) -MD -c -o $@ $<,"  CC    reboot_mod-commands_reboot.o")
-include reboot_mod-commands_reboot.d

reboot_mod_CFLAGS = $(COMMON_CFLAGS)
reboot_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For pci.mod
pci_mod_SOURCES = bus/pci.c

clean-module-pci.mod.1:
	rm -f pci.mod pci_mod-bus_pci.o

CLEAN_MODULE_TARGETS += clean-module-pci.mod.1

mostlyclean-module-pci.mod.1:
	rm -f pci_mod-bus_pci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-pci.mod.1

pci.mod: $(pci_mod_DEPENDENCIES) pci_mod-bus_pci.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   pci.mod")

MODFILES += pci.mod

pci_mod-bus_pci.o: bus/pci.c $(bus/pci.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ibus -I$(srcdir)/bus $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(pci_mod_CFLAGS) -MD -c -o $@ $<,"  CC    pci_mod-bus_pci.o")
-include pci_mod-bus_pci.d

pci_mod_CFLAGS = $(COMMON_CFLAGS)
pci_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For lspci.mod
lspci_mod_SOURCES = commands/lspci.c

clean-module-lspci.mod.1:
	rm -f lspci.mod lspci_mod-commands_lspci.o

CLEAN_MODULE_TARGETS += clean-module-lspci.mod.1

mostlyclean-module-lspci.mod.1:
	rm -f lspci_mod-commands_lspci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-lspci.mod.1

lspci.mod: $(lspci_mod_DEPENDENCIES) lspci_mod-commands_lspci.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   lspci.mod")

MODFILES += lspci.mod

lspci_mod-commands_lspci.o: commands/lspci.c $(commands/lspci.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(lspci_mod_CFLAGS) -MD -c -o $@ $<,"  CC    lspci_mod-commands_lspci.o")
-include lspci_mod-commands_lspci.d

lspci_mod_CFLAGS = $(COMMON_CFLAGS)
lspci_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For datetime.mod
datetime_mod_SOURCES = lib/efi/datetime.c

clean-module-datetime.mod.1:
	rm -f datetime.mod datetime_mod-lib_efi_datetime.o

CLEAN_MODULE_TARGETS += clean-module-datetime.mod.1

mostlyclean-module-datetime.mod.1:
	rm -f datetime_mod-lib_efi_datetime.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-datetime.mod.1

datetime.mod: $(datetime_mod_DEPENDENCIES) datetime_mod-lib_efi_datetime.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   datetime.mod")

MODFILES += datetime.mod

datetime_mod-lib_efi_datetime.o: lib/efi/datetime.c $(lib/efi/datetime.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ilib/efi -I$(srcdir)/lib/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(datetime_mod_CFLAGS) -MD -c -o $@ $<,"  CC    datetime_mod-lib_efi_datetime.o")
-include datetime_mod-lib_efi_datetime.d

datetime_mod_CFLAGS = $(COMMON_CFLAGS)
datetime_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For date.mod
date_mod_SOURCES = commands/date.c

clean-module-date.mod.1:
	rm -f date.mod date_mod-commands_date.o

CLEAN_MODULE_TARGETS += clean-module-date.mod.1

mostlyclean-module-date.mod.1:
	rm -f date_mod-commands_date.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-date.mod.1

date.mod: $(date_mod_DEPENDENCIES) date_mod-commands_date.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   date.mod")

MODFILES += date.mod

date_mod-commands_date.o: commands/date.c $(commands/date.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(date_mod_CFLAGS) -MD -c -o $@ $<,"  CC    date_mod-commands_date.o")
-include date_mod-commands_date.d

date_mod_CFLAGS = $(COMMON_CFLAGS)
date_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For datehook.mod
datehook_mod_SOURCES = hook/datehook.c

clean-module-datehook.mod.1:
	rm -f datehook.mod datehook_mod-hook_datehook.o

CLEAN_MODULE_TARGETS += clean-module-datehook.mod.1

mostlyclean-module-datehook.mod.1:
	rm -f datehook_mod-hook_datehook.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-datehook.mod.1

datehook.mod: $(datehook_mod_DEPENDENCIES) datehook_mod-hook_datehook.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   datehook.mod")

MODFILES += datehook.mod

datehook_mod-hook_datehook.o: hook/datehook.c $(hook/datehook.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ihook -I$(srcdir)/hook $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(datehook_mod_CFLAGS) -MD -c -o $@ $<,"  CC    datehook_mod-hook_datehook.o")
-include datehook_mod-hook_datehook.d

datehook_mod_CFLAGS = $(COMMON_CFLAGS)
datehook_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For loadbios.mod
loadbios_mod_SOURCES = commands/efi/loadbios.c

clean-module-loadbios.mod.1:
	rm -f loadbios.mod loadbios_mod-commands_efi_loadbios.o

CLEAN_MODULE_TARGETS += clean-module-loadbios.mod.1

mostlyclean-module-loadbios.mod.1:
	rm -f loadbios_mod-commands_efi_loadbios.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-loadbios.mod.1

loadbios.mod: $(loadbios_mod_DEPENDENCIES) loadbios_mod-commands_efi_loadbios.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   loadbios.mod")

MODFILES += loadbios.mod

loadbios_mod-commands_efi_loadbios.o: commands/efi/loadbios.c $(commands/efi/loadbios.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/efi -I$(srcdir)/commands/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(loadbios_mod_CFLAGS) -MD -c -o $@ $<,"  CC    loadbios_mod-commands_efi_loadbios.o")
-include loadbios_mod-commands_efi_loadbios.d

loadbios_mod_CFLAGS = $(COMMON_CFLAGS)
loadbios_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For fixvideo.mod
fixvideo_mod_SOURCES = commands/efi/fixvideo.c

clean-module-fixvideo.mod.1:
	rm -f fixvideo.mod fixvideo_mod-commands_efi_fixvideo.o

CLEAN_MODULE_TARGETS += clean-module-fixvideo.mod.1

mostlyclean-module-fixvideo.mod.1:
	rm -f fixvideo_mod-commands_efi_fixvideo.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-fixvideo.mod.1

fixvideo.mod: $(fixvideo_mod_DEPENDENCIES) fixvideo_mod-commands_efi_fixvideo.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   fixvideo.mod")

MODFILES += fixvideo.mod

fixvideo_mod-commands_efi_fixvideo.o: commands/efi/fixvideo.c $(commands/efi/fixvideo.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/efi -I$(srcdir)/commands/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(fixvideo_mod_CFLAGS) -MD -c -o $@ $<,"  CC    fixvideo_mod-commands_efi_fixvideo.o")
-include fixvideo_mod-commands_efi_fixvideo.d

fixvideo_mod_CFLAGS = $(COMMON_CFLAGS)
fixvideo_mod_LDFLAGS = $(COMMON_LDFLAGS)


# For fwsetup.mod
fwsetup_mod_SOURCES = commands/efi/efifwsetup.c

clean-module-fwsetup.mod.1:
	rm -f fwsetup.mod fwsetup_mod-commands_efi_efifwsetup.o

CLEAN_MODULE_TARGETS += clean-module-fwsetup.mod.1

mostlyclean-module-fwsetup.mod.1:
	rm -f fwsetup_mod-commands_efi_efifwsetup.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-fwsetup.mod.1

fwsetup.mod: $(fwsetup_mod_DEPENDENCIES) fwsetup_mod-commands_efi_efifwsetup.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   fwsetup.mod")

MODFILES += fwsetup.mod

fwsetup_mod-commands_efi_efifwsetup.o: commands/efi/efifwsetup.c $(commands/efi/efifwsetup.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/efi -I$(srcdir)/commands/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(fwsetup_mod_CFLAGS) -MD -c -o $@ $<,"  CC    fwsetup_mod-commands_efi_efifwsetup.o")
-include fwsetup_mod-commands_efi_efifwsetup.d

fwsetup_mod_CFLAGS = $(COMMON_CFLAGS)
fwsetup_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For efi_gop.mod
efi_gop_mod_SOURCES = video/efi/efi_gop.c

clean-module-efi_gop.mod.1:
	rm -f efi_gop.mod efi_gop_mod-video_efi_efi_gop.o

CLEAN_MODULE_TARGETS += clean-module-efi_gop.mod.1

mostlyclean-module-efi_gop.mod.1:
	rm -f efi_gop_mod-video_efi_efi_gop.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-efi_gop.mod.1

efi_gop.mod: $(efi_gop_mod_DEPENDENCIES) efi_gop_mod-video_efi_efi_gop.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   efi_gop.mod")

MODFILES += efi_gop.mod

efi_gop_mod-video_efi_efi_gop.o: video/efi/efi_gop.c $(video/efi/efi_gop.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ivideo/efi -I$(srcdir)/video/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efi_gop_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efi_gop_mod-video_efi_efi_gop.o")
-include efi_gop_mod-video_efi_efi_gop.d

efi_gop_mod_CFLAGS = $(COMMON_CFLAGS)
efi_gop_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For efi_uga.mod
efi_uga_mod_SOURCES = video/efi/efi_uga.c

clean-module-efi_uga.mod.1:
	rm -f efi_uga.mod efi_uga_mod-video_efi_efi_uga.o

CLEAN_MODULE_TARGETS += clean-module-efi_uga.mod.1

mostlyclean-module-efi_uga.mod.1:
	rm -f efi_uga_mod-video_efi_efi_uga.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-efi_uga.mod.1

efi_uga.mod: $(efi_uga_mod_DEPENDENCIES) efi_uga_mod-video_efi_efi_uga.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   efi_uga.mod")

MODFILES += efi_uga.mod

efi_uga_mod-video_efi_efi_uga.o: video/efi/efi_uga.c $(video/efi/efi_uga.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ivideo/efi -I$(srcdir)/video/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efi_uga_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efi_uga_mod-video_efi_efi_uga.o")
-include efi_uga_mod-video_efi_efi_uga.d

efi_uga_mod_CFLAGS = $(COMMON_CFLAGS)
efi_uga_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += xnu.mod
xnu_mod_SOURCES = loader/xnu_resume.c loader/i386/xnu.c loader/i386/efi/xnu.c \
	loader/macho32.c loader/macho64.c loader/macho.c loader/xnu.c

clean-module-xnu.mod.1:
	rm -f xnu.mod xnu_mod-loader_xnu_resume.o xnu_mod-loader_i386_xnu.o xnu_mod-loader_i386_efi_xnu.o xnu_mod-loader_macho32.o xnu_mod-loader_macho64.o xnu_mod-loader_macho.o xnu_mod-loader_xnu.o

CLEAN_MODULE_TARGETS += clean-module-xnu.mod.1

mostlyclean-module-xnu.mod.1:
	rm -f xnu_mod-loader_xnu_resume.d xnu_mod-loader_i386_xnu.d xnu_mod-loader_i386_efi_xnu.d xnu_mod-loader_macho32.d xnu_mod-loader_macho64.d xnu_mod-loader_macho.d xnu_mod-loader_xnu.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-xnu.mod.1

xnu.mod: $(xnu_mod_DEPENDENCIES) xnu_mod-loader_xnu_resume.o xnu_mod-loader_i386_xnu.o xnu_mod-loader_i386_efi_xnu.o xnu_mod-loader_macho32.o xnu_mod-loader_macho64.o xnu_mod-loader_macho.o xnu_mod-loader_xnu.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   xnu.mod")

MODFILES += xnu.mod

xnu_mod-loader_xnu_resume.o: loader/xnu_resume.c $(loader/xnu_resume.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_xnu_resume.o")
-include xnu_mod-loader_xnu_resume.d

xnu_mod-loader_i386_xnu.o: loader/i386/xnu.c $(loader/i386/xnu.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_i386_xnu.o")
-include xnu_mod-loader_i386_xnu.d

xnu_mod-loader_i386_efi_xnu.o: loader/i386/efi/xnu.c $(loader/i386/efi/xnu.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader/i386/efi -I$(srcdir)/loader/i386/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_i386_efi_xnu.o")
-include xnu_mod-loader_i386_efi_xnu.d

xnu_mod-loader_macho32.o: loader/macho32.c $(loader/macho32.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_macho32.o")
-include xnu_mod-loader_macho32.d

xnu_mod-loader_macho64.o: loader/macho64.c $(loader/macho64.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_macho64.o")
-include xnu_mod-loader_macho64.d

xnu_mod-loader_macho.o: loader/macho.c $(loader/macho.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_macho.o")
-include xnu_mod-loader_macho.d

xnu_mod-loader_xnu.o: loader/xnu.c $(loader/xnu.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(xnu_mod_CFLAGS) -MD -c -o $@ $<,"  CC    xnu_mod-loader_xnu.o")
-include xnu_mod-loader_xnu.d

xnu_mod_CFLAGS = $(COMMON_CFLAGS)
xnu_mod_LDFLAGS = $(COMMON_LDFLAGS)
xnu_mod_ASFLAGS = $(COMMON_ASFLAGS)

pkglib_MODULES += efivars.mod
efivars_mod_SOURCES = commands/efi/efivars.c

clean-module-efivars.mod.1:
	rm -f efivars.mod efivars_mod-commands_efi_efivars.o

CLEAN_MODULE_TARGETS += clean-module-efivars.mod.1

mostlyclean-module-efivars.mod.1:
	rm -f efivars_mod-commands_efi_efivars.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-efivars.mod.1

efivars.mod: $(efivars_mod_DEPENDENCIES) efivars_mod-commands_efi_efivars.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   efivars.mod")

MODFILES += efivars.mod

efivars_mod-commands_efi_efivars.o: commands/efi/efivars.c $(commands/efi/efivars.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Icommands/efi -I$(srcdir)/commands/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(efivars_mod_CFLAGS) -MD -c -o $@ $<,"  CC    efivars_mod-commands_efi_efivars.o")
-include efivars_mod-commands_efi_efivars.d

efivars_mod_CFLAGS = $(COMMON_CFLAGS)
efivars_mod_ASFLAGS = $(COMMON_ASFLAGS)

pkglib_MODULES += netfs.mod
netfs_mod_SOURCES = fs/efi/netfs.c

clean-module-netfs.mod.1:
	rm -f netfs.mod netfs_mod-fs_efi_netfs.o

CLEAN_MODULE_TARGETS += clean-module-netfs.mod.1

mostlyclean-module-netfs.mod.1:
	rm -f netfs_mod-fs_efi_netfs.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-netfs.mod.1

netfs.mod: $(netfs_mod_DEPENDENCIES) netfs_mod-fs_efi_netfs.o grub-mkmod
	$(call quiet-command,./grub-mkmod -o $@ $(filter %.o, $^),"  MOD   netfs.mod")

MODFILES += netfs.mod

netfs_mod-fs_efi_netfs.o: fs/efi/netfs.c $(fs/efi/netfs.c_DEPENDENCIES)
	$(call quiet-command,$(TARGET_CC) -Ifs/efi -I$(srcdir)/fs/efi $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(netfs_mod_CFLAGS) -MD -c -o $@ $<,"  CC    netfs_mod-fs_efi_netfs.o")
-include netfs_mod-fs_efi_netfs.d

netfs_mod_CFLAGS = $(COMMON_CFLAGS)
netfs_mod_ASFLAGS = $(COMMON_ASFLAGS)

include $(srcdir)/conf/i386.mk
include $(srcdir)/conf/common.mk
grub-mkimage: $(grub_mkimage_DEPENDENCIES) $(grub_mkimage_OBJECTS)
	$(call quiet-command,$(CC) -o $@ $(grub_mkimage_OBJECTS) $(LDFLAGS) $(grub_mkimage_LDFLAGS),"  LINK  grub-mkimage")

